################################################################################
# Automatically-generated file. Do not edit!
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
C_SRCS += \
../lib/cpython/Modules/_abc.c \
../lib/cpython/Modules/_asynciomodule.c \
../lib/cpython/Modules/_bisectmodule.c \
../lib/cpython/Modules/_bz2module.c \
../lib/cpython/Modules/_codecsmodule.c \
../lib/cpython/Modules/_collectionsmodule.c \
../lib/cpython/Modules/_contextvarsmodule.c \
../lib/cpython/Modules/_cryptmodule.c \
../lib/cpython/Modules/_csv.c \
../lib/cpython/Modules/_curses_panel.c \
../lib/cpython/Modules/_cursesmodule.c \
../lib/cpython/Modules/_datetimemodule.c \
../lib/cpython/Modules/_dbmmodule.c \
../lib/cpython/Modules/_elementtree.c \
../lib/cpython/Modules/_functoolsmodule.c \
../lib/cpython/Modules/_gdbmmodule.c \
../lib/cpython/Modules/_hashopenssl.c \
../lib/cpython/Modules/_heapqmodule.c \
../lib/cpython/Modules/_json.c \
../lib/cpython/Modules/_localemodule.c \
../lib/cpython/Modules/_lsprof.c \
../lib/cpython/Modules/_lzmamodule.c \
../lib/cpython/Modules/_math.c \
../lib/cpython/Modules/_opcode.c \
../lib/cpython/Modules/_operator.c \
../lib/cpython/Modules/_pickle.c \
../lib/cpython/Modules/_posixsubprocess.c \
../lib/cpython/Modules/_queuemodule.c \
../lib/cpython/Modules/_randommodule.c \
../lib/cpython/Modules/_scproxy.c \
../lib/cpython/Modules/_sre.c \
../lib/cpython/Modules/_ssl.c \
../lib/cpython/Modules/_stat.c \
../lib/cpython/Modules/_struct.c \
../lib/cpython/Modules/_testbuffer.c \
../lib/cpython/Modules/_testcapimodule.c \
../lib/cpython/Modules/_testimportmultiple.c \
../lib/cpython/Modules/_testmultiphase.c \
../lib/cpython/Modules/_threadmodule.c \
../lib/cpython/Modules/_tkinter.c \
../lib/cpython/Modules/_tracemalloc.c \
../lib/cpython/Modules/_uuidmodule.c \
../lib/cpython/Modules/_weakref.c \
../lib/cpython/Modules/_winapi.c \
../lib/cpython/Modules/_xxsubinterpretersmodule.c \
../lib/cpython/Modules/arraymodule.c \
../lib/cpython/Modules/atexitmodule.c \
../lib/cpython/Modules/audioop.c \
../lib/cpython/Modules/binascii.c \
../lib/cpython/Modules/cmathmodule.c \
../lib/cpython/Modules/config.c \
../lib/cpython/Modules/errnomodule.c \
../lib/cpython/Modules/faulthandler.c \
../lib/cpython/Modules/fcntlmodule.c \
../lib/cpython/Modules/gcmodule.c \
../lib/cpython/Modules/getaddrinfo.c \
../lib/cpython/Modules/getbuildinfo.c \
../lib/cpython/Modules/getnameinfo.c \
../lib/cpython/Modules/getpath.c \
../lib/cpython/Modules/grpmodule.c \
../lib/cpython/Modules/hashtable.c \
../lib/cpython/Modules/itertoolsmodule.c \
../lib/cpython/Modules/main.c \
../lib/cpython/Modules/mathmodule.c \
../lib/cpython/Modules/md5module.c \
../lib/cpython/Modules/mmapmodule.c \
../lib/cpython/Modules/nismodule.c \
../lib/cpython/Modules/ossaudiodev.c \
../lib/cpython/Modules/overlapped.c \
../lib/cpython/Modules/parsermodule.c \
../lib/cpython/Modules/posixmodule.c \
../lib/cpython/Modules/pwdmodule.c \
../lib/cpython/Modules/pyexpat.c \
../lib/cpython/Modules/readline.c \
../lib/cpython/Modules/resource.c \
../lib/cpython/Modules/rotatingtree.c \
../lib/cpython/Modules/selectmodule.c \
../lib/cpython/Modules/sha1module.c \
../lib/cpython/Modules/sha256module.c \
../lib/cpython/Modules/sha512module.c \
../lib/cpython/Modules/signalmodule.c \
../lib/cpython/Modules/socketmodule.c \
../lib/cpython/Modules/spwdmodule.c \
../lib/cpython/Modules/symtablemodule.c \
../lib/cpython/Modules/syslogmodule.c \
../lib/cpython/Modules/termios.c \
../lib/cpython/Modules/timemodule.c \
../lib/cpython/Modules/tkappinit.c \
../lib/cpython/Modules/unicodedata.c \
../lib/cpython/Modules/xxlimited.c \
../lib/cpython/Modules/xxmodule.c \
../lib/cpython/Modules/xxsubtype.c \
../lib/cpython/Modules/zlibmodule.c 

O_SRCS += \
../lib/cpython/Modules/_abc.o \
../lib/cpython/Modules/_codecsmodule.o \
../lib/cpython/Modules/_collectionsmodule.o \
../lib/cpython/Modules/_functoolsmodule.o \
../lib/cpython/Modules/_iomodule.o \
../lib/cpython/Modules/_localemodule.o \
../lib/cpython/Modules/_math.o \
../lib/cpython/Modules/_operator.o \
../lib/cpython/Modules/_sre.o \
../lib/cpython/Modules/_stat.o \
../lib/cpython/Modules/_threadmodule.o \
../lib/cpython/Modules/_tracemalloc.o \
../lib/cpython/Modules/_weakref.o \
../lib/cpython/Modules/atexitmodule.o \
../lib/cpython/Modules/bufferedio.o \
../lib/cpython/Modules/bytesio.o \
../lib/cpython/Modules/config.o \
../lib/cpython/Modules/errnomodule.o \
../lib/cpython/Modules/faulthandler.o \
../lib/cpython/Modules/fileio.o \
../lib/cpython/Modules/gcmodule.o \
../lib/cpython/Modules/getbuildinfo.o \
../lib/cpython/Modules/getpath.o \
../lib/cpython/Modules/hashtable.o \
../lib/cpython/Modules/iobase.o \
../lib/cpython/Modules/itertoolsmodule.o \
../lib/cpython/Modules/main.o \
../lib/cpython/Modules/posixmodule.o \
../lib/cpython/Modules/pwdmodule.o \
../lib/cpython/Modules/signalmodule.o \
../lib/cpython/Modules/stringio.o \
../lib/cpython/Modules/symtablemodule.o \
../lib/cpython/Modules/textio.o \
../lib/cpython/Modules/timemodule.o \
../lib/cpython/Modules/xxsubtype.o 

OBJS += \
./lib/cpython/Modules/_abc.o \
./lib/cpython/Modules/_asynciomodule.o \
./lib/cpython/Modules/_bisectmodule.o \
./lib/cpython/Modules/_bz2module.o \
./lib/cpython/Modules/_codecsmodule.o \
./lib/cpython/Modules/_collectionsmodule.o \
./lib/cpython/Modules/_contextvarsmodule.o \
./lib/cpython/Modules/_cryptmodule.o \
./lib/cpython/Modules/_csv.o \
./lib/cpython/Modules/_curses_panel.o \
./lib/cpython/Modules/_cursesmodule.o \
./lib/cpython/Modules/_datetimemodule.o \
./lib/cpython/Modules/_dbmmodule.o \
./lib/cpython/Modules/_elementtree.o \
./lib/cpython/Modules/_functoolsmodule.o \
./lib/cpython/Modules/_gdbmmodule.o \
./lib/cpython/Modules/_hashopenssl.o \
./lib/cpython/Modules/_heapqmodule.o \
./lib/cpython/Modules/_json.o \
./lib/cpython/Modules/_localemodule.o \
./lib/cpython/Modules/_lsprof.o \
./lib/cpython/Modules/_lzmamodule.o \
./lib/cpython/Modules/_math.o \
./lib/cpython/Modules/_opcode.o \
./lib/cpython/Modules/_operator.o \
./lib/cpython/Modules/_pickle.o \
./lib/cpython/Modules/_posixsubprocess.o \
./lib/cpython/Modules/_queuemodule.o \
./lib/cpython/Modules/_randommodule.o \
./lib/cpython/Modules/_scproxy.o \
./lib/cpython/Modules/_sre.o \
./lib/cpython/Modules/_ssl.o \
./lib/cpython/Modules/_stat.o \
./lib/cpython/Modules/_struct.o \
./lib/cpython/Modules/_testbuffer.o \
./lib/cpython/Modules/_testcapimodule.o \
./lib/cpython/Modules/_testimportmultiple.o \
./lib/cpython/Modules/_testmultiphase.o \
./lib/cpython/Modules/_threadmodule.o \
./lib/cpython/Modules/_tkinter.o \
./lib/cpython/Modules/_tracemalloc.o \
./lib/cpython/Modules/_uuidmodule.o \
./lib/cpython/Modules/_weakref.o \
./lib/cpython/Modules/_winapi.o \
./lib/cpython/Modules/_xxsubinterpretersmodule.o \
./lib/cpython/Modules/arraymodule.o \
./lib/cpython/Modules/atexitmodule.o \
./lib/cpython/Modules/audioop.o \
./lib/cpython/Modules/binascii.o \
./lib/cpython/Modules/cmathmodule.o \
./lib/cpython/Modules/config.o \
./lib/cpython/Modules/errnomodule.o \
./lib/cpython/Modules/faulthandler.o \
./lib/cpython/Modules/fcntlmodule.o \
./lib/cpython/Modules/gcmodule.o \
./lib/cpython/Modules/getaddrinfo.o \
./lib/cpython/Modules/getbuildinfo.o \
./lib/cpython/Modules/getnameinfo.o \
./lib/cpython/Modules/getpath.o \
./lib/cpython/Modules/grpmodule.o \
./lib/cpython/Modules/hashtable.o \
./lib/cpython/Modules/itertoolsmodule.o \
./lib/cpython/Modules/main.o \
./lib/cpython/Modules/mathmodule.o \
./lib/cpython/Modules/md5module.o \
./lib/cpython/Modules/mmapmodule.o \
./lib/cpython/Modules/nismodule.o \
./lib/cpython/Modules/ossaudiodev.o \
./lib/cpython/Modules/overlapped.o \
./lib/cpython/Modules/parsermodule.o \
./lib/cpython/Modules/posixmodule.o \
./lib/cpython/Modules/pwdmodule.o \
./lib/cpython/Modules/pyexpat.o \
./lib/cpython/Modules/readline.o \
./lib/cpython/Modules/resource.o \
./lib/cpython/Modules/rotatingtree.o \
./lib/cpython/Modules/selectmodule.o \
./lib/cpython/Modules/sha1module.o \
./lib/cpython/Modules/sha256module.o \
./lib/cpython/Modules/sha512module.o \
./lib/cpython/Modules/signalmodule.o \
./lib/cpython/Modules/socketmodule.o \
./lib/cpython/Modules/spwdmodule.o \
./lib/cpython/Modules/symtablemodule.o \
./lib/cpython/Modules/syslogmodule.o \
./lib/cpython/Modules/termios.o \
./lib/cpython/Modules/timemodule.o \
./lib/cpython/Modules/tkappinit.o \
./lib/cpython/Modules/unicodedata.o \
./lib/cpython/Modules/xxlimited.o \
./lib/cpython/Modules/xxmodule.o \
./lib/cpython/Modules/xxsubtype.o \
./lib/cpython/Modules/zlibmodule.o 

C_DEPS += \
./lib/cpython/Modules/_abc.d \
./lib/cpython/Modules/_asynciomodule.d \
./lib/cpython/Modules/_bisectmodule.d \
./lib/cpython/Modules/_bz2module.d \
./lib/cpython/Modules/_codecsmodule.d \
./lib/cpython/Modules/_collectionsmodule.d \
./lib/cpython/Modules/_contextvarsmodule.d \
./lib/cpython/Modules/_cryptmodule.d \
./lib/cpython/Modules/_csv.d \
./lib/cpython/Modules/_curses_panel.d \
./lib/cpython/Modules/_cursesmodule.d \
./lib/cpython/Modules/_datetimemodule.d \
./lib/cpython/Modules/_dbmmodule.d \
./lib/cpython/Modules/_elementtree.d \
./lib/cpython/Modules/_functoolsmodule.d \
./lib/cpython/Modules/_gdbmmodule.d \
./lib/cpython/Modules/_hashopenssl.d \
./lib/cpython/Modules/_heapqmodule.d \
./lib/cpython/Modules/_json.d \
./lib/cpython/Modules/_localemodule.d \
./lib/cpython/Modules/_lsprof.d \
./lib/cpython/Modules/_lzmamodule.d \
./lib/cpython/Modules/_math.d \
./lib/cpython/Modules/_opcode.d \
./lib/cpython/Modules/_operator.d \
./lib/cpython/Modules/_pickle.d \
./lib/cpython/Modules/_posixsubprocess.d \
./lib/cpython/Modules/_queuemodule.d \
./lib/cpython/Modules/_randommodule.d \
./lib/cpython/Modules/_scproxy.d \
./lib/cpython/Modules/_sre.d \
./lib/cpython/Modules/_ssl.d \
./lib/cpython/Modules/_stat.d \
./lib/cpython/Modules/_struct.d \
./lib/cpython/Modules/_testbuffer.d \
./lib/cpython/Modules/_testcapimodule.d \
./lib/cpython/Modules/_testimportmultiple.d \
./lib/cpython/Modules/_testmultiphase.d \
./lib/cpython/Modules/_threadmodule.d \
./lib/cpython/Modules/_tkinter.d \
./lib/cpython/Modules/_tracemalloc.d \
./lib/cpython/Modules/_uuidmodule.d \
./lib/cpython/Modules/_weakref.d \
./lib/cpython/Modules/_winapi.d \
./lib/cpython/Modules/_xxsubinterpretersmodule.d \
./lib/cpython/Modules/arraymodule.d \
./lib/cpython/Modules/atexitmodule.d \
./lib/cpython/Modules/audioop.d \
./lib/cpython/Modules/binascii.d \
./lib/cpython/Modules/cmathmodule.d \
./lib/cpython/Modules/config.d \
./lib/cpython/Modules/errnomodule.d \
./lib/cpython/Modules/faulthandler.d \
./lib/cpython/Modules/fcntlmodule.d \
./lib/cpython/Modules/gcmodule.d \
./lib/cpython/Modules/getaddrinfo.d \
./lib/cpython/Modules/getbuildinfo.d \
./lib/cpython/Modules/getnameinfo.d \
./lib/cpython/Modules/getpath.d \
./lib/cpython/Modules/grpmodule.d \
./lib/cpython/Modules/hashtable.d \
./lib/cpython/Modules/itertoolsmodule.d \
./lib/cpython/Modules/main.d \
./lib/cpython/Modules/mathmodule.d \
./lib/cpython/Modules/md5module.d \
./lib/cpython/Modules/mmapmodule.d \
./lib/cpython/Modules/nismodule.d \
./lib/cpython/Modules/ossaudiodev.d \
./lib/cpython/Modules/overlapped.d \
./lib/cpython/Modules/parsermodule.d \
./lib/cpython/Modules/posixmodule.d \
./lib/cpython/Modules/pwdmodule.d \
./lib/cpython/Modules/pyexpat.d \
./lib/cpython/Modules/readline.d \
./lib/cpython/Modules/resource.d \
./lib/cpython/Modules/rotatingtree.d \
./lib/cpython/Modules/selectmodule.d \
./lib/cpython/Modules/sha1module.d \
./lib/cpython/Modules/sha256module.d \
./lib/cpython/Modules/sha512module.d \
./lib/cpython/Modules/signalmodule.d \
./lib/cpython/Modules/socketmodule.d \
./lib/cpython/Modules/spwdmodule.d \
./lib/cpython/Modules/symtablemodule.d \
./lib/cpython/Modules/syslogmodule.d \
./lib/cpython/Modules/termios.d \
./lib/cpython/Modules/timemodule.d \
./lib/cpython/Modules/tkappinit.d \
./lib/cpython/Modules/unicodedata.d \
./lib/cpython/Modules/xxlimited.d \
./lib/cpython/Modules/xxmodule.d \
./lib/cpython/Modules/xxsubtype.d \
./lib/cpython/Modules/zlibmodule.d 


# Each subdirectory must supply rules for building sources it contributes
lib/cpython/Modules/%.o: ../lib/cpython/Modules/%.c
	@echo 'Building file: $<'
	@echo 'Invoking: GCC C Compiler'
	gcc -O0 -g3 -Wall -c -fmessage-length=0 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@)" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '


