################################################################################
# Automatically-generated file. Do not edit!
################################################################################

C_UPPER_SRCS := 
CXX_SRCS := 
OBJ_SRCS := 
C++_SRCS := 
CC_SRCS := 
ASM_SRCS := 
CPP_SRCS := 
C_SRCS := 
O_SRCS := 
S_UPPER_SRCS := 
CC_DEPS := 
C++_DEPS := 
ARCHIVES := 
C_UPPER_DEPS := 
CXX_DEPS := 
OBJS := 
CPP_DEPS := 
C_DEPS := 

# Every subdirectory with source files must be described here
SUBDIRS := \
CMakeFiles/3.12.1/CompilerIdC \
CMakeFiles/3.12.1/CompilerIdCXX \
CMakeFiles/Engine.dir/CMakeFiles/3.12.1/CompilerIdC \
CMakeFiles/Engine.dir/CMakeFiles/3.12.1/CompilerIdCXX \
CMakeFiles/Engine.dir/CMakeFiles \
CMakeFiles/Engine.dir/lib/FFmpeg/compat/atomics/pthread \
CMakeFiles/Engine.dir/lib/FFmpeg/compat/djgpp \
CMakeFiles/Engine.dir/lib/FFmpeg/compat \
CMakeFiles/Engine.dir/src/AI \
CMakeFiles/Engine.dir/src/Config \
CMakeFiles/Engine.dir/src/EncryptedData \
CMakeFiles/Engine.dir/src/Event_old \
CMakeFiles/Engine.dir/src/Events \
CMakeFiles/Engine.dir/src/Exporting \
CMakeFiles/Engine.dir/src/GUI/DevEnv/DevGUIs \
CMakeFiles/Engine.dir/src/GUI \
CMakeFiles/Engine.dir/src/Helper \
CMakeFiles/Engine.dir/src/Model \
CMakeFiles/Engine.dir/src/Networking \
CMakeFiles \
FBXCommon \
data/Model \
lib/FFmpeg/compat/atomics/pthread \
lib/FFmpeg/compat/djgpp \
lib/FFmpeg/compat \
lib/FFmpeg/compat/msvcrt \
lib/FFmpeg \
lib/FFmpeg/doc/examples \
lib/FFmpeg/doc \
lib/FFmpeg/fftools \
lib/FFmpeg/libavcodec \
lib/FFmpeg/libavcodec/aarch64 \
lib/FFmpeg/libavcodec/alpha \
lib/FFmpeg/libavcodec/arm \
lib/FFmpeg/libavcodec/mips \
lib/FFmpeg/libavcodec/neon \
lib/FFmpeg/libavcodec/ppc \
lib/FFmpeg/libavcodec/tests/aarch64 \
lib/FFmpeg/libavcodec/tests/arm \
lib/FFmpeg/libavcodec/tests \
lib/FFmpeg/libavcodec/tests/ppc \
lib/FFmpeg/libavcodec/tests/x86 \
lib/FFmpeg/libavcodec/x86 \
lib/FFmpeg/libavdevice \
lib/FFmpeg/libavdevice/tests \
lib/FFmpeg/libavfilter/aarch64 \
lib/FFmpeg/libavfilter \
lib/FFmpeg/libavfilter/tests \
lib/FFmpeg/libavfilter/x86 \
lib/FFmpeg/libavformat \
lib/FFmpeg/libavformat/tests \
lib/FFmpeg/libavresample/aarch64 \
lib/FFmpeg/libavresample/arm \
lib/FFmpeg/libavresample \
lib/FFmpeg/libavresample/tests \
lib/FFmpeg/libavresample/x86 \
lib/FFmpeg/libavutil/aarch64 \
lib/FFmpeg/libavutil \
lib/FFmpeg/libavutil/arm \
lib/FFmpeg/libavutil/mips \
lib/FFmpeg/libavutil/ppc \
lib/FFmpeg/libavutil/tests \
lib/FFmpeg/libavutil/x86 \
lib/FFmpeg/libpostproc \
lib/FFmpeg/libswresample/aarch64 \
lib/FFmpeg/libswresample/arm \
lib/FFmpeg/libswresample \
lib/FFmpeg/libswresample/tests \
lib/FFmpeg/libswresample/x86 \
lib/FFmpeg/libswscale/aarch64 \
lib/FFmpeg/libswscale \
lib/FFmpeg/libswscale/arm \
lib/FFmpeg/libswscale/ppc \
lib/FFmpeg/libswscale/tests \
lib/FFmpeg/libswscale/x86 \
lib/FFmpeg/tests/api \
lib/FFmpeg/tests \
lib/FFmpeg/tests/checkasm \
lib/FFmpeg/tests/checkasm/aarch64 \
lib/FFmpeg/tests/checkasm/arm \
lib/FFmpeg/tests/checkasm/x86 \
lib/FFmpeg/tools \
lib/ImageMagick/Magick++/demo \
lib/ImageMagick/Magick++/fuzz \
lib/ImageMagick/Magick++/lib/.libs \
lib/ImageMagick/Magick++/lib \
lib/ImageMagick/Magick++/tests \
lib/ImageMagick/MagickCore/.libs \
lib/ImageMagick/MagickCore \
lib/ImageMagick/MagickWand/.libs \
lib/ImageMagick/MagickWand \
lib/ImageMagick/MagickWand/tests \
lib/ImageMagick/api_examples \
lib/ImageMagick/coders/.libs \
lib/ImageMagick/coders \
lib/ImageMagick/filters/.libs \
lib/ImageMagick/filters \
lib/ImageMagick/tests \
lib/ImageMagick/utilities \
lib/ImageMagick/www/source \
lib/ImageMagick/www/source/core \
lib/ImageMagick/www/source/wand \
lib/cpython/Doc/includes \
lib/cpython/Mac/Tools \
lib/cpython/Misc \
lib/cpython/Modules \
lib/cpython/Modules/_blake2 \
lib/cpython/Modules/_blake2/impl \
lib/cpython/Modules/_ctypes \
lib/cpython/Modules/_ctypes/darwin \
lib/cpython/Modules/_ctypes/libffi_msvc \
lib/cpython/Modules/_ctypes/libffi_osx \
lib/cpython/Modules/_ctypes/libffi_osx/powerpc \
lib/cpython/Modules/_ctypes/libffi_osx/x86 \
lib/cpython/Modules/_decimal \
lib/cpython/Modules/_decimal/libmpdec \
lib/cpython/Modules/_io \
lib/cpython/Modules/_multiprocessing \
lib/cpython/Modules/_sha3/kcp \
lib/cpython/Modules/_sha3 \
lib/cpython/Modules/_sqlite \
lib/cpython/Modules/_xxtestfuzz \
lib/cpython/Modules/cjkcodecs \
lib/cpython/Modules/expat \
lib/cpython/Objects \
lib/cpython/PC \
lib/cpython/PC/bdist_wininst \
lib/cpython/Parser \
lib/cpython/Programs \
lib/cpython/Python \
lib/cpython/Tools/msi/bundle/bootstrap \
lib/cpython/build/temp.linux-x86_64-3.8/media/NBackups/Dev/Cpp/EterniaEngine/Engine/lib/cpython/Modules \
lib/cpython/build/temp.linux-x86_64-3.8/media/NBackups/Dev/Cpp/EterniaEngine/Engine/lib/cpython/Modules/_blake2 \
lib/cpython/build/temp.linux-x86_64-3.8/media/NBackups/Dev/Cpp/EterniaEngine/Engine/lib/cpython/Modules/_ctypes \
lib/cpython/build/temp.linux-x86_64-3.8/media/NBackups/Dev/Cpp/EterniaEngine/Engine/lib/cpython/Modules/_decimal \
lib/cpython/build/temp.linux-x86_64-3.8/media/NBackups/Dev/Cpp/EterniaEngine/Engine/lib/cpython/Modules/_decimal/libmpdec \
lib/cpython/build/temp.linux-x86_64-3.8/media/NBackups/Dev/Cpp/EterniaEngine/Engine/lib/cpython/Modules/_multiprocessing \
lib/cpython/build/temp.linux-x86_64-3.8/media/NBackups/Dev/Cpp/EterniaEngine/Engine/lib/cpython/Modules/_sha3 \
lib/cpython/build/temp.linux-x86_64-3.8/media/NBackups/Dev/Cpp/EterniaEngine/Engine/lib/cpython/Modules/_xxtestfuzz \
lib/cpython/build/temp.linux-x86_64-3.8/media/NBackups/Dev/Cpp/EterniaEngine/Engine/lib/cpython/Modules/cjkcodecs \
lib/cpython/build/temp.linux-x86_64-3.8/media/NBackups/Dev/Cpp/EterniaEngine/Engine/lib/cpython/Modules/expat \
lib/freealut/examples \
lib/freealut/src/.libs \
lib/freealut/src \
lib/freealut/test_suite \
lib/lua \
lib/lua/testes/libs \
lib/openal-soft/Alc \
lib/openal-soft/Alc/backends \
lib/openal-soft/Alc/effects \
lib/openal-soft/Alc/filters \
lib/openal-soft/Alc/mixer \
lib/openal-soft/CMakeFiles/3.12.1/CompilerIdC \
lib/openal-soft/CMakeFiles/3.12.1/CompilerIdCXX \
lib/openal-soft/CMakeFiles/CheckIncludeFiles \
lib/openal-soft/CMakeFiles/CheckTypeSize \
lib/openal-soft/CMakeFiles/OpenAL.dir/Alc \
lib/openal-soft/CMakeFiles/OpenAL.dir/Alc/backends \
lib/openal-soft/CMakeFiles/OpenAL.dir/Alc/effects \
lib/openal-soft/CMakeFiles/OpenAL.dir/Alc/filters \
lib/openal-soft/CMakeFiles/OpenAL.dir/Alc/mixer \
lib/openal-soft/CMakeFiles/OpenAL.dir/OpenAL32 \
lib/openal-soft/CMakeFiles/alrecord.dir/examples \
lib/openal-soft/CMakeFiles/altonegen.dir/examples \
lib/openal-soft/CMakeFiles/altonegen.dir/examples/common \
lib/openal-soft/CMakeFiles/common.dir/common \
lib/openal-soft/CMakeFiles/ex-common.dir/examples/common \
lib/openal-soft/CMakeFiles \
lib/openal-soft/CMakeFiles/makehrtf.dir/utils \
lib/openal-soft/CMakeFiles/openal-info.dir/utils \
lib/openal-soft/OpenAL32 \
lib/openal-soft/cmake \
lib/openal-soft/common \
lib/openal-soft/examples \
lib/openal-soft/examples/common \
lib/openal-soft/native-tools/CMakeFiles/3.12.1/CompilerIdC \
lib/openal-soft/native-tools/CMakeFiles/3.12.1/CompilerIdCXX \
lib/openal-soft/native-tools/CMakeFiles/bin2h.dir \
lib/openal-soft/native-tools/CMakeFiles/bsincgen.dir \
lib/openal-soft/native-tools/CMakeFiles \
lib/openal-soft/native-tools \
lib/openal-soft/router \
lib/openal-soft/utils/alsoft-config/CMakeFiles/alsoft-config.dir \
lib/openal-soft/utils/alsoft-config \
lib/openal-soft/utils \
lib/zlib/CMakeFiles/example.dir/test \
lib/zlib/CMakeFiles/example64.dir/test \
lib/zlib/CMakeFiles/minigzip.dir/test \
lib/zlib/CMakeFiles/minigzip64.dir/test \
lib/zlib/CMakeFiles/zlib.dir \
lib/zlib/CMakeFiles/zlibstatic.dir \
lib/zlib \
lib/zlib/contrib/amd64 \
lib/zlib/contrib/asm686 \
lib/zlib/contrib/blast \
lib/zlib/contrib/gcc_gvmat64 \
lib/zlib/contrib/infback9 \
lib/zlib/contrib/inflate86 \
lib/zlib/contrib/iostream \
lib/zlib/contrib/iostream2 \
lib/zlib/contrib/iostream3 \
lib/zlib/contrib/masmx64 \
lib/zlib/contrib/masmx86 \
lib/zlib/contrib/minizip \
lib/zlib/contrib/puff \
lib/zlib/contrib/testzlib \
lib/zlib/contrib/untgz \
lib/zlib/examples \
lib/zlib/test \
obj/Debug/src/AI \
obj/Debug/src \
obj/Debug/src/Config \
obj/Debug/src/EncryptedData \
obj/Debug/src/Event_old \
obj/Debug/src/Events \
obj/Debug/src/Exporting \
obj/Debug/src/GUI/DevEnv \
obj/Debug/src/GUI/DevEnv/DevGUIs \
obj/Debug/src/GUI/DevEnv/DevViews \
obj/Debug/src/GUI \
obj/Debug/src/Helper \
obj/Debug/src/Model \
obj/Debug/src/Networking \
obj/Debug/src/Scripts \
obj/Debug/src/Sound \
obj/Debug/src/Sprite2D \
src/AI \
src \
src/EncryptedData \
src/Exporting \
src/GUI/DevEnv \
src/GUI/DevEnv/DevGUIs \
src/GUI/DevEnv/DevViews \
src/GUI \
src/Helper \
src/Model \
src/Networking \
src/Scripts \
src/Scripts/Python \
src/Sound \
src/Sprite2D \
src_old/Config_old \
src_old/Event_old \
src_old/Events_old \

