################################################################################
# Automatically-generated file. Do not edit!
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
C_SRCS += \
../lib/FFmpeg/libavformat/3dostr.c \
../lib/FFmpeg/libavformat/4xm.c \
../lib/FFmpeg/libavformat/a64.c \
../lib/FFmpeg/libavformat/aacdec.c \
../lib/FFmpeg/libavformat/aadec.c \
../lib/FFmpeg/libavformat/ac3dec.c \
../lib/FFmpeg/libavformat/acm.c \
../lib/FFmpeg/libavformat/act.c \
../lib/FFmpeg/libavformat/adp.c \
../lib/FFmpeg/libavformat/ads.c \
../lib/FFmpeg/libavformat/adtsenc.c \
../lib/FFmpeg/libavformat/adxdec.c \
../lib/FFmpeg/libavformat/aea.c \
../lib/FFmpeg/libavformat/afc.c \
../lib/FFmpeg/libavformat/aiffdec.c \
../lib/FFmpeg/libavformat/aiffenc.c \
../lib/FFmpeg/libavformat/aixdec.c \
../lib/FFmpeg/libavformat/allformats.c \
../lib/FFmpeg/libavformat/amr.c \
../lib/FFmpeg/libavformat/anm.c \
../lib/FFmpeg/libavformat/apc.c \
../lib/FFmpeg/libavformat/ape.c \
../lib/FFmpeg/libavformat/apetag.c \
../lib/FFmpeg/libavformat/apngdec.c \
../lib/FFmpeg/libavformat/apngenc.c \
../lib/FFmpeg/libavformat/aptxdec.c \
../lib/FFmpeg/libavformat/aqtitledec.c \
../lib/FFmpeg/libavformat/asf.c \
../lib/FFmpeg/libavformat/asfcrypt.c \
../lib/FFmpeg/libavformat/asfdec_f.c \
../lib/FFmpeg/libavformat/asfdec_o.c \
../lib/FFmpeg/libavformat/asfenc.c \
../lib/FFmpeg/libavformat/assdec.c \
../lib/FFmpeg/libavformat/assenc.c \
../lib/FFmpeg/libavformat/ast.c \
../lib/FFmpeg/libavformat/astdec.c \
../lib/FFmpeg/libavformat/astenc.c \
../lib/FFmpeg/libavformat/async.c \
../lib/FFmpeg/libavformat/au.c \
../lib/FFmpeg/libavformat/audiointerleave.c \
../lib/FFmpeg/libavformat/av1.c \
../lib/FFmpeg/libavformat/avc.c \
../lib/FFmpeg/libavformat/avidec.c \
../lib/FFmpeg/libavformat/avienc.c \
../lib/FFmpeg/libavformat/avio.c \
../lib/FFmpeg/libavformat/aviobuf.c \
../lib/FFmpeg/libavformat/avisynth.c \
../lib/FFmpeg/libavformat/avlanguage.c \
../lib/FFmpeg/libavformat/avr.c \
../lib/FFmpeg/libavformat/avs.c \
../lib/FFmpeg/libavformat/bethsoftvid.c \
../lib/FFmpeg/libavformat/bfi.c \
../lib/FFmpeg/libavformat/bink.c \
../lib/FFmpeg/libavformat/bintext.c \
../lib/FFmpeg/libavformat/bit.c \
../lib/FFmpeg/libavformat/bluray.c \
../lib/FFmpeg/libavformat/bmv.c \
../lib/FFmpeg/libavformat/boadec.c \
../lib/FFmpeg/libavformat/brstm.c \
../lib/FFmpeg/libavformat/c93.c \
../lib/FFmpeg/libavformat/cache.c \
../lib/FFmpeg/libavformat/caf.c \
../lib/FFmpeg/libavformat/cafdec.c \
../lib/FFmpeg/libavformat/cafenc.c \
../lib/FFmpeg/libavformat/cavsvideodec.c \
../lib/FFmpeg/libavformat/cdg.c \
../lib/FFmpeg/libavformat/cdxl.c \
../lib/FFmpeg/libavformat/chromaprint.c \
../lib/FFmpeg/libavformat/cinedec.c \
../lib/FFmpeg/libavformat/codec2.c \
../lib/FFmpeg/libavformat/concat.c \
../lib/FFmpeg/libavformat/concatdec.c \
../lib/FFmpeg/libavformat/crcenc.c \
../lib/FFmpeg/libavformat/crypto.c \
../lib/FFmpeg/libavformat/cutils.c \
../lib/FFmpeg/libavformat/dash.c \
../lib/FFmpeg/libavformat/dashdec.c \
../lib/FFmpeg/libavformat/dashenc.c \
../lib/FFmpeg/libavformat/data_uri.c \
../lib/FFmpeg/libavformat/dauddec.c \
../lib/FFmpeg/libavformat/daudenc.c \
../lib/FFmpeg/libavformat/davs2.c \
../lib/FFmpeg/libavformat/dcstr.c \
../lib/FFmpeg/libavformat/demuxer_list.c \
../lib/FFmpeg/libavformat/dfa.c \
../lib/FFmpeg/libavformat/dhav.c \
../lib/FFmpeg/libavformat/diracdec.c \
../lib/FFmpeg/libavformat/dnxhddec.c \
../lib/FFmpeg/libavformat/dsfdec.c \
../lib/FFmpeg/libavformat/dsicin.c \
../lib/FFmpeg/libavformat/dss.c \
../lib/FFmpeg/libavformat/dtsdec.c \
../lib/FFmpeg/libavformat/dtshddec.c \
../lib/FFmpeg/libavformat/dump.c \
../lib/FFmpeg/libavformat/dv.c \
../lib/FFmpeg/libavformat/dvbsub.c \
../lib/FFmpeg/libavformat/dvbtxt.c \
../lib/FFmpeg/libavformat/dvenc.c \
../lib/FFmpeg/libavformat/dxa.c \
../lib/FFmpeg/libavformat/eacdata.c \
../lib/FFmpeg/libavformat/electronicarts.c \
../lib/FFmpeg/libavformat/epafdec.c \
../lib/FFmpeg/libavformat/ffmetadec.c \
../lib/FFmpeg/libavformat/ffmetaenc.c \
../lib/FFmpeg/libavformat/fifo.c \
../lib/FFmpeg/libavformat/fifo_test.c \
../lib/FFmpeg/libavformat/file.c \
../lib/FFmpeg/libavformat/file_open.c \
../lib/FFmpeg/libavformat/filmstripdec.c \
../lib/FFmpeg/libavformat/filmstripenc.c \
../lib/FFmpeg/libavformat/fitsdec.c \
../lib/FFmpeg/libavformat/fitsenc.c \
../lib/FFmpeg/libavformat/flac_picture.c \
../lib/FFmpeg/libavformat/flacdec.c \
../lib/FFmpeg/libavformat/flacenc.c \
../lib/FFmpeg/libavformat/flacenc_header.c \
../lib/FFmpeg/libavformat/flic.c \
../lib/FFmpeg/libavformat/flvdec.c \
../lib/FFmpeg/libavformat/flvenc.c \
../lib/FFmpeg/libavformat/format.c \
../lib/FFmpeg/libavformat/framecrcenc.c \
../lib/FFmpeg/libavformat/framehash.c \
../lib/FFmpeg/libavformat/frmdec.c \
../lib/FFmpeg/libavformat/fsb.c \
../lib/FFmpeg/libavformat/ftp.c \
../lib/FFmpeg/libavformat/g722.c \
../lib/FFmpeg/libavformat/g723_1.c \
../lib/FFmpeg/libavformat/g726.c \
../lib/FFmpeg/libavformat/g729dec.c \
../lib/FFmpeg/libavformat/gdv.c \
../lib/FFmpeg/libavformat/genh.c \
../lib/FFmpeg/libavformat/gif.c \
../lib/FFmpeg/libavformat/gifdec.c \
../lib/FFmpeg/libavformat/golomb_tab.c \
../lib/FFmpeg/libavformat/gopher.c \
../lib/FFmpeg/libavformat/gsmdec.c \
../lib/FFmpeg/libavformat/gxf.c \
../lib/FFmpeg/libavformat/gxfenc.c \
../lib/FFmpeg/libavformat/h261dec.c \
../lib/FFmpeg/libavformat/h263dec.c \
../lib/FFmpeg/libavformat/h264dec.c \
../lib/FFmpeg/libavformat/hashenc.c \
../lib/FFmpeg/libavformat/hdsenc.c \
../lib/FFmpeg/libavformat/hevc.c \
../lib/FFmpeg/libavformat/hevcdec.c \
../lib/FFmpeg/libavformat/hls.c \
../lib/FFmpeg/libavformat/hlsenc.c \
../lib/FFmpeg/libavformat/hlsplaylist.c \
../lib/FFmpeg/libavformat/hlsproto.c \
../lib/FFmpeg/libavformat/hnm.c \
../lib/FFmpeg/libavformat/http.c \
../lib/FFmpeg/libavformat/httpauth.c \
../lib/FFmpeg/libavformat/icecast.c \
../lib/FFmpeg/libavformat/icodec.c \
../lib/FFmpeg/libavformat/icoenc.c \
../lib/FFmpeg/libavformat/id3v1.c \
../lib/FFmpeg/libavformat/id3v2.c \
../lib/FFmpeg/libavformat/id3v2enc.c \
../lib/FFmpeg/libavformat/idcin.c \
../lib/FFmpeg/libavformat/idroqdec.c \
../lib/FFmpeg/libavformat/idroqenc.c \
../lib/FFmpeg/libavformat/iff.c \
../lib/FFmpeg/libavformat/ilbc.c \
../lib/FFmpeg/libavformat/img2.c \
../lib/FFmpeg/libavformat/img2_alias_pix.c \
../lib/FFmpeg/libavformat/img2_brender_pix.c \
../lib/FFmpeg/libavformat/img2dec.c \
../lib/FFmpeg/libavformat/img2enc.c \
../lib/FFmpeg/libavformat/ingenientdec.c \
../lib/FFmpeg/libavformat/ip.c \
../lib/FFmpeg/libavformat/ipmovie.c \
../lib/FFmpeg/libavformat/ircam.c \
../lib/FFmpeg/libavformat/ircamdec.c \
../lib/FFmpeg/libavformat/ircamenc.c \
../lib/FFmpeg/libavformat/isom.c \
../lib/FFmpeg/libavformat/iss.c \
../lib/FFmpeg/libavformat/iv8.c \
../lib/FFmpeg/libavformat/ivfdec.c \
../lib/FFmpeg/libavformat/ivfenc.c \
../lib/FFmpeg/libavformat/jacosubdec.c \
../lib/FFmpeg/libavformat/jacosubenc.c \
../lib/FFmpeg/libavformat/jvdec.c \
../lib/FFmpeg/libavformat/latmenc.c \
../lib/FFmpeg/libavformat/libgme.c \
../lib/FFmpeg/libavformat/libmodplug.c \
../lib/FFmpeg/libavformat/libopenmpt.c \
../lib/FFmpeg/libavformat/librtmp.c \
../lib/FFmpeg/libavformat/libsmbclient.c \
../lib/FFmpeg/libavformat/libsrt.c \
../lib/FFmpeg/libavformat/libssh.c \
../lib/FFmpeg/libavformat/lmlm4.c \
../lib/FFmpeg/libavformat/loasdec.c \
../lib/FFmpeg/libavformat/log2_tab.c \
../lib/FFmpeg/libavformat/lrc.c \
../lib/FFmpeg/libavformat/lrcdec.c \
../lib/FFmpeg/libavformat/lrcenc.c \
../lib/FFmpeg/libavformat/lvfdec.c \
../lib/FFmpeg/libavformat/lxfdec.c \
../lib/FFmpeg/libavformat/m4vdec.c \
../lib/FFmpeg/libavformat/matroska.c \
../lib/FFmpeg/libavformat/matroskadec.c \
../lib/FFmpeg/libavformat/matroskaenc.c \
../lib/FFmpeg/libavformat/md5proto.c \
../lib/FFmpeg/libavformat/metadata.c \
../lib/FFmpeg/libavformat/mgsts.c \
../lib/FFmpeg/libavformat/microdvddec.c \
../lib/FFmpeg/libavformat/microdvdenc.c \
../lib/FFmpeg/libavformat/mj2kdec.c \
../lib/FFmpeg/libavformat/mkvtimestamp_v2.c \
../lib/FFmpeg/libavformat/mlpdec.c \
../lib/FFmpeg/libavformat/mlvdec.c \
../lib/FFmpeg/libavformat/mm.c \
../lib/FFmpeg/libavformat/mmf.c \
../lib/FFmpeg/libavformat/mms.c \
../lib/FFmpeg/libavformat/mmsh.c \
../lib/FFmpeg/libavformat/mmst.c \
../lib/FFmpeg/libavformat/mov.c \
../lib/FFmpeg/libavformat/mov_chan.c \
../lib/FFmpeg/libavformat/mov_esds.c \
../lib/FFmpeg/libavformat/movenc.c \
../lib/FFmpeg/libavformat/movenccenc.c \
../lib/FFmpeg/libavformat/movenchint.c \
../lib/FFmpeg/libavformat/mp3dec.c \
../lib/FFmpeg/libavformat/mp3enc.c \
../lib/FFmpeg/libavformat/mpc.c \
../lib/FFmpeg/libavformat/mpc8.c \
../lib/FFmpeg/libavformat/mpeg.c \
../lib/FFmpeg/libavformat/mpegenc.c \
../lib/FFmpeg/libavformat/mpegts.c \
../lib/FFmpeg/libavformat/mpegtsenc.c \
../lib/FFmpeg/libavformat/mpegvideodec.c \
../lib/FFmpeg/libavformat/mpjpeg.c \
../lib/FFmpeg/libavformat/mpjpegdec.c \
../lib/FFmpeg/libavformat/mpl2dec.c \
../lib/FFmpeg/libavformat/mpsubdec.c \
../lib/FFmpeg/libavformat/msf.c \
../lib/FFmpeg/libavformat/msnwc_tcp.c \
../lib/FFmpeg/libavformat/mtaf.c \
../lib/FFmpeg/libavformat/mtv.c \
../lib/FFmpeg/libavformat/musx.c \
../lib/FFmpeg/libavformat/mux.c \
../lib/FFmpeg/libavformat/muxer_list.c \
../lib/FFmpeg/libavformat/mvdec.c \
../lib/FFmpeg/libavformat/mvi.c \
../lib/FFmpeg/libavformat/mxf.c \
../lib/FFmpeg/libavformat/mxfdec.c \
../lib/FFmpeg/libavformat/mxfenc.c \
../lib/FFmpeg/libavformat/mxg.c \
../lib/FFmpeg/libavformat/ncdec.c \
../lib/FFmpeg/libavformat/network.c \
../lib/FFmpeg/libavformat/nistspheredec.c \
../lib/FFmpeg/libavformat/nspdec.c \
../lib/FFmpeg/libavformat/nsvdec.c \
../lib/FFmpeg/libavformat/nullenc.c \
../lib/FFmpeg/libavformat/nut.c \
../lib/FFmpeg/libavformat/nutdec.c \
../lib/FFmpeg/libavformat/nutenc.c \
../lib/FFmpeg/libavformat/nuv.c \
../lib/FFmpeg/libavformat/oggdec.c \
../lib/FFmpeg/libavformat/oggenc.c \
../lib/FFmpeg/libavformat/oggparsecelt.c \
../lib/FFmpeg/libavformat/oggparsedaala.c \
../lib/FFmpeg/libavformat/oggparsedirac.c \
../lib/FFmpeg/libavformat/oggparseflac.c \
../lib/FFmpeg/libavformat/oggparseogm.c \
../lib/FFmpeg/libavformat/oggparseopus.c \
../lib/FFmpeg/libavformat/oggparseskeleton.c \
../lib/FFmpeg/libavformat/oggparsespeex.c \
../lib/FFmpeg/libavformat/oggparsetheora.c \
../lib/FFmpeg/libavformat/oggparsevorbis.c \
../lib/FFmpeg/libavformat/oggparsevp8.c \
../lib/FFmpeg/libavformat/oma.c \
../lib/FFmpeg/libavformat/omadec.c \
../lib/FFmpeg/libavformat/omaenc.c \
../lib/FFmpeg/libavformat/options.c \
../lib/FFmpeg/libavformat/os_support.c \
../lib/FFmpeg/libavformat/paf.c \
../lib/FFmpeg/libavformat/pcm.c \
../lib/FFmpeg/libavformat/pcmdec.c \
../lib/FFmpeg/libavformat/pcmenc.c \
../lib/FFmpeg/libavformat/pjsdec.c \
../lib/FFmpeg/libavformat/pmpdec.c \
../lib/FFmpeg/libavformat/prompeg.c \
../lib/FFmpeg/libavformat/protocol_list.c \
../lib/FFmpeg/libavformat/protocols.c \
../lib/FFmpeg/libavformat/psxstr.c \
../lib/FFmpeg/libavformat/pva.c \
../lib/FFmpeg/libavformat/pvfdec.c \
../lib/FFmpeg/libavformat/qcp.c \
../lib/FFmpeg/libavformat/qtpalette.c \
../lib/FFmpeg/libavformat/r3d.c \
../lib/FFmpeg/libavformat/rawdec.c \
../lib/FFmpeg/libavformat/rawenc.c \
../lib/FFmpeg/libavformat/rawutils.c \
../lib/FFmpeg/libavformat/rawvideodec.c \
../lib/FFmpeg/libavformat/rdt.c \
../lib/FFmpeg/libavformat/realtextdec.c \
../lib/FFmpeg/libavformat/redspark.c \
../lib/FFmpeg/libavformat/replaygain.c \
../lib/FFmpeg/libavformat/riff.c \
../lib/FFmpeg/libavformat/riffdec.c \
../lib/FFmpeg/libavformat/riffenc.c \
../lib/FFmpeg/libavformat/rl2.c \
../lib/FFmpeg/libavformat/rm.c \
../lib/FFmpeg/libavformat/rmdec.c \
../lib/FFmpeg/libavformat/rmenc.c \
../lib/FFmpeg/libavformat/rmsipr.c \
../lib/FFmpeg/libavformat/rpl.c \
../lib/FFmpeg/libavformat/rsd.c \
../lib/FFmpeg/libavformat/rso.c \
../lib/FFmpeg/libavformat/rsodec.c \
../lib/FFmpeg/libavformat/rsoenc.c \
../lib/FFmpeg/libavformat/rtmpcrypt.c \
../lib/FFmpeg/libavformat/rtmpdh.c \
../lib/FFmpeg/libavformat/rtmpdigest.c \
../lib/FFmpeg/libavformat/rtmphttp.c \
../lib/FFmpeg/libavformat/rtmppkt.c \
../lib/FFmpeg/libavformat/rtmpproto.c \
../lib/FFmpeg/libavformat/rtp.c \
../lib/FFmpeg/libavformat/rtpdec.c \
../lib/FFmpeg/libavformat/rtpdec_ac3.c \
../lib/FFmpeg/libavformat/rtpdec_amr.c \
../lib/FFmpeg/libavformat/rtpdec_asf.c \
../lib/FFmpeg/libavformat/rtpdec_dv.c \
../lib/FFmpeg/libavformat/rtpdec_g726.c \
../lib/FFmpeg/libavformat/rtpdec_h261.c \
../lib/FFmpeg/libavformat/rtpdec_h263.c \
../lib/FFmpeg/libavformat/rtpdec_h263_rfc2190.c \
../lib/FFmpeg/libavformat/rtpdec_h264.c \
../lib/FFmpeg/libavformat/rtpdec_hevc.c \
../lib/FFmpeg/libavformat/rtpdec_ilbc.c \
../lib/FFmpeg/libavformat/rtpdec_jpeg.c \
../lib/FFmpeg/libavformat/rtpdec_latm.c \
../lib/FFmpeg/libavformat/rtpdec_mpa_robust.c \
../lib/FFmpeg/libavformat/rtpdec_mpeg12.c \
../lib/FFmpeg/libavformat/rtpdec_mpeg4.c \
../lib/FFmpeg/libavformat/rtpdec_mpegts.c \
../lib/FFmpeg/libavformat/rtpdec_qcelp.c \
../lib/FFmpeg/libavformat/rtpdec_qdm2.c \
../lib/FFmpeg/libavformat/rtpdec_qt.c \
../lib/FFmpeg/libavformat/rtpdec_rfc4175.c \
../lib/FFmpeg/libavformat/rtpdec_svq3.c \
../lib/FFmpeg/libavformat/rtpdec_vc2hq.c \
../lib/FFmpeg/libavformat/rtpdec_vp8.c \
../lib/FFmpeg/libavformat/rtpdec_vp9.c \
../lib/FFmpeg/libavformat/rtpdec_xiph.c \
../lib/FFmpeg/libavformat/rtpenc.c \
../lib/FFmpeg/libavformat/rtpenc_aac.c \
../lib/FFmpeg/libavformat/rtpenc_amr.c \
../lib/FFmpeg/libavformat/rtpenc_chain.c \
../lib/FFmpeg/libavformat/rtpenc_h261.c \
../lib/FFmpeg/libavformat/rtpenc_h263.c \
../lib/FFmpeg/libavformat/rtpenc_h263_rfc2190.c \
../lib/FFmpeg/libavformat/rtpenc_h264_hevc.c \
../lib/FFmpeg/libavformat/rtpenc_jpeg.c \
../lib/FFmpeg/libavformat/rtpenc_latm.c \
../lib/FFmpeg/libavformat/rtpenc_mpegts.c \
../lib/FFmpeg/libavformat/rtpenc_mpv.c \
../lib/FFmpeg/libavformat/rtpenc_vc2hq.c \
../lib/FFmpeg/libavformat/rtpenc_vp8.c \
../lib/FFmpeg/libavformat/rtpenc_vp9.c \
../lib/FFmpeg/libavformat/rtpenc_xiph.c \
../lib/FFmpeg/libavformat/rtpproto.c \
../lib/FFmpeg/libavformat/rtsp.c \
../lib/FFmpeg/libavformat/rtspdec.c \
../lib/FFmpeg/libavformat/rtspenc.c \
../lib/FFmpeg/libavformat/s337m.c \
../lib/FFmpeg/libavformat/samidec.c \
../lib/FFmpeg/libavformat/sapdec.c \
../lib/FFmpeg/libavformat/sapenc.c \
../lib/FFmpeg/libavformat/sauce.c \
../lib/FFmpeg/libavformat/sbcdec.c \
../lib/FFmpeg/libavformat/sbgdec.c \
../lib/FFmpeg/libavformat/sccdec.c \
../lib/FFmpeg/libavformat/sccenc.c \
../lib/FFmpeg/libavformat/sctp.c \
../lib/FFmpeg/libavformat/sdp.c \
../lib/FFmpeg/libavformat/sdr2.c \
../lib/FFmpeg/libavformat/sdsdec.c \
../lib/FFmpeg/libavformat/sdxdec.c \
../lib/FFmpeg/libavformat/segafilm.c \
../lib/FFmpeg/libavformat/segafilmenc.c \
../lib/FFmpeg/libavformat/segment.c \
../lib/FFmpeg/libavformat/serdec.c \
../lib/FFmpeg/libavformat/shortendec.c \
../lib/FFmpeg/libavformat/sierravmd.c \
../lib/FFmpeg/libavformat/siff.c \
../lib/FFmpeg/libavformat/smacker.c \
../lib/FFmpeg/libavformat/smjpeg.c \
../lib/FFmpeg/libavformat/smjpegdec.c \
../lib/FFmpeg/libavformat/smjpegenc.c \
../lib/FFmpeg/libavformat/smoothstreamingenc.c \
../lib/FFmpeg/libavformat/smush.c \
../lib/FFmpeg/libavformat/sol.c \
../lib/FFmpeg/libavformat/soxdec.c \
../lib/FFmpeg/libavformat/soxenc.c \
../lib/FFmpeg/libavformat/spdif.c \
../lib/FFmpeg/libavformat/spdifdec.c \
../lib/FFmpeg/libavformat/spdifenc.c \
../lib/FFmpeg/libavformat/srtdec.c \
../lib/FFmpeg/libavformat/srtenc.c \
../lib/FFmpeg/libavformat/srtp.c \
../lib/FFmpeg/libavformat/srtpproto.c \
../lib/FFmpeg/libavformat/stldec.c \
../lib/FFmpeg/libavformat/subfile.c \
../lib/FFmpeg/libavformat/subtitles.c \
../lib/FFmpeg/libavformat/subviewer1dec.c \
../lib/FFmpeg/libavformat/subviewerdec.c \
../lib/FFmpeg/libavformat/supdec.c \
../lib/FFmpeg/libavformat/supenc.c \
../lib/FFmpeg/libavformat/svag.c \
../lib/FFmpeg/libavformat/swf.c \
../lib/FFmpeg/libavformat/swfdec.c \
../lib/FFmpeg/libavformat/swfenc.c \
../lib/FFmpeg/libavformat/takdec.c \
../lib/FFmpeg/libavformat/tcp.c \
../lib/FFmpeg/libavformat/tedcaptionsdec.c \
../lib/FFmpeg/libavformat/tee.c \
../lib/FFmpeg/libavformat/tee_common.c \
../lib/FFmpeg/libavformat/teeproto.c \
../lib/FFmpeg/libavformat/thp.c \
../lib/FFmpeg/libavformat/tiertexseq.c \
../lib/FFmpeg/libavformat/tls.c \
../lib/FFmpeg/libavformat/tls_gnutls.c \
../lib/FFmpeg/libavformat/tls_libtls.c \
../lib/FFmpeg/libavformat/tls_mbedtls.c \
../lib/FFmpeg/libavformat/tls_openssl.c \
../lib/FFmpeg/libavformat/tls_schannel.c \
../lib/FFmpeg/libavformat/tls_securetransport.c \
../lib/FFmpeg/libavformat/tmv.c \
../lib/FFmpeg/libavformat/tta.c \
../lib/FFmpeg/libavformat/ttaenc.c \
../lib/FFmpeg/libavformat/tty.c \
../lib/FFmpeg/libavformat/txd.c \
../lib/FFmpeg/libavformat/ty.c \
../lib/FFmpeg/libavformat/udp.c \
../lib/FFmpeg/libavformat/uncodedframecrcenc.c \
../lib/FFmpeg/libavformat/unix.c \
../lib/FFmpeg/libavformat/url.c \
../lib/FFmpeg/libavformat/urldecode.c \
../lib/FFmpeg/libavformat/utils.c \
../lib/FFmpeg/libavformat/v210.c \
../lib/FFmpeg/libavformat/vag.c \
../lib/FFmpeg/libavformat/vapoursynth.c \
../lib/FFmpeg/libavformat/vc1dec.c \
../lib/FFmpeg/libavformat/vc1test.c \
../lib/FFmpeg/libavformat/vc1testenc.c \
../lib/FFmpeg/libavformat/vividas.c \
../lib/FFmpeg/libavformat/vivo.c \
../lib/FFmpeg/libavformat/voc.c \
../lib/FFmpeg/libavformat/voc_packet.c \
../lib/FFmpeg/libavformat/vocdec.c \
../lib/FFmpeg/libavformat/vocenc.c \
../lib/FFmpeg/libavformat/vorbiscomment.c \
../lib/FFmpeg/libavformat/vpcc.c \
../lib/FFmpeg/libavformat/vpk.c \
../lib/FFmpeg/libavformat/vplayerdec.c \
../lib/FFmpeg/libavformat/vqf.c \
../lib/FFmpeg/libavformat/w64.c \
../lib/FFmpeg/libavformat/wavdec.c \
../lib/FFmpeg/libavformat/wavenc.c \
../lib/FFmpeg/libavformat/wc3movie.c \
../lib/FFmpeg/libavformat/webm_chunk.c \
../lib/FFmpeg/libavformat/webmdashenc.c \
../lib/FFmpeg/libavformat/webpenc.c \
../lib/FFmpeg/libavformat/webvttdec.c \
../lib/FFmpeg/libavformat/webvttenc.c \
../lib/FFmpeg/libavformat/westwood_aud.c \
../lib/FFmpeg/libavformat/westwood_vqa.c \
../lib/FFmpeg/libavformat/wsddec.c \
../lib/FFmpeg/libavformat/wtv_common.c \
../lib/FFmpeg/libavformat/wtvdec.c \
../lib/FFmpeg/libavformat/wtvenc.c \
../lib/FFmpeg/libavformat/wv.c \
../lib/FFmpeg/libavformat/wvdec.c \
../lib/FFmpeg/libavformat/wvedec.c \
../lib/FFmpeg/libavformat/wvenc.c \
../lib/FFmpeg/libavformat/xa.c \
../lib/FFmpeg/libavformat/xmv.c \
../lib/FFmpeg/libavformat/xvag.c \
../lib/FFmpeg/libavformat/xwma.c \
../lib/FFmpeg/libavformat/yop.c \
../lib/FFmpeg/libavformat/yuv4mpegdec.c \
../lib/FFmpeg/libavformat/yuv4mpegenc.c 

O_SRCS += \
../lib/FFmpeg/libavformat/3dostr.o \
../lib/FFmpeg/libavformat/4xm.o \
../lib/FFmpeg/libavformat/a64.o \
../lib/FFmpeg/libavformat/aacdec.o \
../lib/FFmpeg/libavformat/aadec.o \
../lib/FFmpeg/libavformat/ac3dec.o \
../lib/FFmpeg/libavformat/acm.o \
../lib/FFmpeg/libavformat/act.o \
../lib/FFmpeg/libavformat/adp.o \
../lib/FFmpeg/libavformat/ads.o \
../lib/FFmpeg/libavformat/adtsenc.o \
../lib/FFmpeg/libavformat/adxdec.o \
../lib/FFmpeg/libavformat/aea.o \
../lib/FFmpeg/libavformat/afc.o \
../lib/FFmpeg/libavformat/aiffdec.o \
../lib/FFmpeg/libavformat/aiffenc.o \
../lib/FFmpeg/libavformat/aixdec.o \
../lib/FFmpeg/libavformat/allformats.o \
../lib/FFmpeg/libavformat/amr.o \
../lib/FFmpeg/libavformat/anm.o \
../lib/FFmpeg/libavformat/apc.o \
../lib/FFmpeg/libavformat/ape.o \
../lib/FFmpeg/libavformat/apetag.o \
../lib/FFmpeg/libavformat/apngdec.o \
../lib/FFmpeg/libavformat/apngenc.o \
../lib/FFmpeg/libavformat/aptxdec.o \
../lib/FFmpeg/libavformat/aqtitledec.o \
../lib/FFmpeg/libavformat/asf.o \
../lib/FFmpeg/libavformat/asfcrypt.o \
../lib/FFmpeg/libavformat/asfdec_f.o \
../lib/FFmpeg/libavformat/asfdec_o.o \
../lib/FFmpeg/libavformat/asfenc.o \
../lib/FFmpeg/libavformat/assdec.o \
../lib/FFmpeg/libavformat/assenc.o \
../lib/FFmpeg/libavformat/ast.o \
../lib/FFmpeg/libavformat/astdec.o \
../lib/FFmpeg/libavformat/astenc.o \
../lib/FFmpeg/libavformat/async.o \
../lib/FFmpeg/libavformat/au.o \
../lib/FFmpeg/libavformat/audiointerleave.o \
../lib/FFmpeg/libavformat/av1.o \
../lib/FFmpeg/libavformat/avc.o \
../lib/FFmpeg/libavformat/avidec.o \
../lib/FFmpeg/libavformat/avienc.o \
../lib/FFmpeg/libavformat/avio.o \
../lib/FFmpeg/libavformat/aviobuf.o \
../lib/FFmpeg/libavformat/avlanguage.o \
../lib/FFmpeg/libavformat/avr.o \
../lib/FFmpeg/libavformat/avs.o \
../lib/FFmpeg/libavformat/bethsoftvid.o \
../lib/FFmpeg/libavformat/bfi.o \
../lib/FFmpeg/libavformat/bink.o \
../lib/FFmpeg/libavformat/bintext.o \
../lib/FFmpeg/libavformat/bit.o \
../lib/FFmpeg/libavformat/bmv.o \
../lib/FFmpeg/libavformat/boadec.o \
../lib/FFmpeg/libavformat/brstm.o \
../lib/FFmpeg/libavformat/c93.o \
../lib/FFmpeg/libavformat/cache.o \
../lib/FFmpeg/libavformat/caf.o \
../lib/FFmpeg/libavformat/cafdec.o \
../lib/FFmpeg/libavformat/cafenc.o \
../lib/FFmpeg/libavformat/cavsvideodec.o \
../lib/FFmpeg/libavformat/cdg.o \
../lib/FFmpeg/libavformat/cdxl.o \
../lib/FFmpeg/libavformat/cinedec.o \
../lib/FFmpeg/libavformat/codec2.o \
../lib/FFmpeg/libavformat/concat.o \
../lib/FFmpeg/libavformat/concatdec.o \
../lib/FFmpeg/libavformat/crcenc.o \
../lib/FFmpeg/libavformat/crypto.o \
../lib/FFmpeg/libavformat/cutils.o \
../lib/FFmpeg/libavformat/dash.o \
../lib/FFmpeg/libavformat/dashenc.o \
../lib/FFmpeg/libavformat/data_uri.o \
../lib/FFmpeg/libavformat/dauddec.o \
../lib/FFmpeg/libavformat/daudenc.o \
../lib/FFmpeg/libavformat/davs2.o \
../lib/FFmpeg/libavformat/dcstr.o \
../lib/FFmpeg/libavformat/dfa.o \
../lib/FFmpeg/libavformat/dhav.o \
../lib/FFmpeg/libavformat/diracdec.o \
../lib/FFmpeg/libavformat/dnxhddec.o \
../lib/FFmpeg/libavformat/dsfdec.o \
../lib/FFmpeg/libavformat/dsicin.o \
../lib/FFmpeg/libavformat/dss.o \
../lib/FFmpeg/libavformat/dtsdec.o \
../lib/FFmpeg/libavformat/dtshddec.o \
../lib/FFmpeg/libavformat/dump.o \
../lib/FFmpeg/libavformat/dv.o \
../lib/FFmpeg/libavformat/dvbsub.o \
../lib/FFmpeg/libavformat/dvbtxt.o \
../lib/FFmpeg/libavformat/dvenc.o \
../lib/FFmpeg/libavformat/dxa.o \
../lib/FFmpeg/libavformat/eacdata.o \
../lib/FFmpeg/libavformat/electronicarts.o \
../lib/FFmpeg/libavformat/epafdec.o \
../lib/FFmpeg/libavformat/ffmetadec.o \
../lib/FFmpeg/libavformat/ffmetaenc.o \
../lib/FFmpeg/libavformat/fifo.o \
../lib/FFmpeg/libavformat/fifo_test.o \
../lib/FFmpeg/libavformat/file.o \
../lib/FFmpeg/libavformat/filmstripdec.o \
../lib/FFmpeg/libavformat/filmstripenc.o \
../lib/FFmpeg/libavformat/fitsdec.o \
../lib/FFmpeg/libavformat/fitsenc.o \
../lib/FFmpeg/libavformat/flac_picture.o \
../lib/FFmpeg/libavformat/flacdec.o \
../lib/FFmpeg/libavformat/flacenc.o \
../lib/FFmpeg/libavformat/flacenc_header.o \
../lib/FFmpeg/libavformat/flic.o \
../lib/FFmpeg/libavformat/flvdec.o \
../lib/FFmpeg/libavformat/flvenc.o \
../lib/FFmpeg/libavformat/format.o \
../lib/FFmpeg/libavformat/framecrcenc.o \
../lib/FFmpeg/libavformat/framehash.o \
../lib/FFmpeg/libavformat/frmdec.o \
../lib/FFmpeg/libavformat/fsb.o \
../lib/FFmpeg/libavformat/ftp.o \
../lib/FFmpeg/libavformat/g722.o \
../lib/FFmpeg/libavformat/g723_1.o \
../lib/FFmpeg/libavformat/g726.o \
../lib/FFmpeg/libavformat/g729dec.o \
../lib/FFmpeg/libavformat/gdv.o \
../lib/FFmpeg/libavformat/genh.o \
../lib/FFmpeg/libavformat/gif.o \
../lib/FFmpeg/libavformat/gifdec.o \
../lib/FFmpeg/libavformat/gopher.o \
../lib/FFmpeg/libavformat/gsmdec.o \
../lib/FFmpeg/libavformat/gxf.o \
../lib/FFmpeg/libavformat/gxfenc.o \
../lib/FFmpeg/libavformat/h261dec.o \
../lib/FFmpeg/libavformat/h263dec.o \
../lib/FFmpeg/libavformat/h264dec.o \
../lib/FFmpeg/libavformat/hashenc.o \
../lib/FFmpeg/libavformat/hdsenc.o \
../lib/FFmpeg/libavformat/hevc.o \
../lib/FFmpeg/libavformat/hevcdec.o \
../lib/FFmpeg/libavformat/hls.o \
../lib/FFmpeg/libavformat/hlsenc.o \
../lib/FFmpeg/libavformat/hlsplaylist.o \
../lib/FFmpeg/libavformat/hlsproto.o \
../lib/FFmpeg/libavformat/hnm.o \
../lib/FFmpeg/libavformat/http.o \
../lib/FFmpeg/libavformat/httpauth.o \
../lib/FFmpeg/libavformat/icecast.o \
../lib/FFmpeg/libavformat/icodec.o \
../lib/FFmpeg/libavformat/icoenc.o \
../lib/FFmpeg/libavformat/id3v1.o \
../lib/FFmpeg/libavformat/id3v2.o \
../lib/FFmpeg/libavformat/id3v2enc.o \
../lib/FFmpeg/libavformat/idcin.o \
../lib/FFmpeg/libavformat/idroqdec.o \
../lib/FFmpeg/libavformat/idroqenc.o \
../lib/FFmpeg/libavformat/iff.o \
../lib/FFmpeg/libavformat/ilbc.o \
../lib/FFmpeg/libavformat/img2.o \
../lib/FFmpeg/libavformat/img2_alias_pix.o \
../lib/FFmpeg/libavformat/img2_brender_pix.o \
../lib/FFmpeg/libavformat/img2dec.o \
../lib/FFmpeg/libavformat/img2enc.o \
../lib/FFmpeg/libavformat/ingenientdec.o \
../lib/FFmpeg/libavformat/ip.o \
../lib/FFmpeg/libavformat/ipmovie.o \
../lib/FFmpeg/libavformat/ircam.o \
../lib/FFmpeg/libavformat/ircamdec.o \
../lib/FFmpeg/libavformat/ircamenc.o \
../lib/FFmpeg/libavformat/isom.o \
../lib/FFmpeg/libavformat/iss.o \
../lib/FFmpeg/libavformat/iv8.o \
../lib/FFmpeg/libavformat/ivfdec.o \
../lib/FFmpeg/libavformat/ivfenc.o \
../lib/FFmpeg/libavformat/jacosubdec.o \
../lib/FFmpeg/libavformat/jacosubenc.o \
../lib/FFmpeg/libavformat/jvdec.o \
../lib/FFmpeg/libavformat/latmenc.o \
../lib/FFmpeg/libavformat/lmlm4.o \
../lib/FFmpeg/libavformat/loasdec.o \
../lib/FFmpeg/libavformat/lrc.o \
../lib/FFmpeg/libavformat/lrcdec.o \
../lib/FFmpeg/libavformat/lrcenc.o \
../lib/FFmpeg/libavformat/lvfdec.o \
../lib/FFmpeg/libavformat/lxfdec.o \
../lib/FFmpeg/libavformat/m4vdec.o \
../lib/FFmpeg/libavformat/matroska.o \
../lib/FFmpeg/libavformat/matroskadec.o \
../lib/FFmpeg/libavformat/matroskaenc.o \
../lib/FFmpeg/libavformat/md5proto.o \
../lib/FFmpeg/libavformat/metadata.o \
../lib/FFmpeg/libavformat/mgsts.o \
../lib/FFmpeg/libavformat/microdvddec.o \
../lib/FFmpeg/libavformat/microdvdenc.o \
../lib/FFmpeg/libavformat/mj2kdec.o \
../lib/FFmpeg/libavformat/mkvtimestamp_v2.o \
../lib/FFmpeg/libavformat/mlpdec.o \
../lib/FFmpeg/libavformat/mlvdec.o \
../lib/FFmpeg/libavformat/mm.o \
../lib/FFmpeg/libavformat/mmf.o \
../lib/FFmpeg/libavformat/mms.o \
../lib/FFmpeg/libavformat/mmsh.o \
../lib/FFmpeg/libavformat/mmst.o \
../lib/FFmpeg/libavformat/mov.o \
../lib/FFmpeg/libavformat/mov_chan.o \
../lib/FFmpeg/libavformat/mov_esds.o \
../lib/FFmpeg/libavformat/movenc.o \
../lib/FFmpeg/libavformat/movenccenc.o \
../lib/FFmpeg/libavformat/movenchint.o \
../lib/FFmpeg/libavformat/mp3dec.o \
../lib/FFmpeg/libavformat/mp3enc.o \
../lib/FFmpeg/libavformat/mpc.o \
../lib/FFmpeg/libavformat/mpc8.o \
../lib/FFmpeg/libavformat/mpeg.o \
../lib/FFmpeg/libavformat/mpegenc.o \
../lib/FFmpeg/libavformat/mpegts.o \
../lib/FFmpeg/libavformat/mpegtsenc.o \
../lib/FFmpeg/libavformat/mpegvideodec.o \
../lib/FFmpeg/libavformat/mpjpeg.o \
../lib/FFmpeg/libavformat/mpjpegdec.o \
../lib/FFmpeg/libavformat/mpl2dec.o \
../lib/FFmpeg/libavformat/mpsubdec.o \
../lib/FFmpeg/libavformat/msf.o \
../lib/FFmpeg/libavformat/msnwc_tcp.o \
../lib/FFmpeg/libavformat/mtaf.o \
../lib/FFmpeg/libavformat/mtv.o \
../lib/FFmpeg/libavformat/musx.o \
../lib/FFmpeg/libavformat/mux.o \
../lib/FFmpeg/libavformat/mvdec.o \
../lib/FFmpeg/libavformat/mvi.o \
../lib/FFmpeg/libavformat/mxf.o \
../lib/FFmpeg/libavformat/mxfdec.o \
../lib/FFmpeg/libavformat/mxfenc.o \
../lib/FFmpeg/libavformat/mxg.o \
../lib/FFmpeg/libavformat/ncdec.o \
../lib/FFmpeg/libavformat/network.o \
../lib/FFmpeg/libavformat/nistspheredec.o \
../lib/FFmpeg/libavformat/nspdec.o \
../lib/FFmpeg/libavformat/nsvdec.o \
../lib/FFmpeg/libavformat/nullenc.o \
../lib/FFmpeg/libavformat/nut.o \
../lib/FFmpeg/libavformat/nutdec.o \
../lib/FFmpeg/libavformat/nutenc.o \
../lib/FFmpeg/libavformat/nuv.o \
../lib/FFmpeg/libavformat/oggdec.o \
../lib/FFmpeg/libavformat/oggenc.o \
../lib/FFmpeg/libavformat/oggparsecelt.o \
../lib/FFmpeg/libavformat/oggparsedaala.o \
../lib/FFmpeg/libavformat/oggparsedirac.o \
../lib/FFmpeg/libavformat/oggparseflac.o \
../lib/FFmpeg/libavformat/oggparseogm.o \
../lib/FFmpeg/libavformat/oggparseopus.o \
../lib/FFmpeg/libavformat/oggparseskeleton.o \
../lib/FFmpeg/libavformat/oggparsespeex.o \
../lib/FFmpeg/libavformat/oggparsetheora.o \
../lib/FFmpeg/libavformat/oggparsevorbis.o \
../lib/FFmpeg/libavformat/oggparsevp8.o \
../lib/FFmpeg/libavformat/oma.o \
../lib/FFmpeg/libavformat/omadec.o \
../lib/FFmpeg/libavformat/omaenc.o \
../lib/FFmpeg/libavformat/options.o \
../lib/FFmpeg/libavformat/os_support.o \
../lib/FFmpeg/libavformat/paf.o \
../lib/FFmpeg/libavformat/pcm.o \
../lib/FFmpeg/libavformat/pcmdec.o \
../lib/FFmpeg/libavformat/pcmenc.o \
../lib/FFmpeg/libavformat/pjsdec.o \
../lib/FFmpeg/libavformat/pmpdec.o \
../lib/FFmpeg/libavformat/prompeg.o \
../lib/FFmpeg/libavformat/protocols.o \
../lib/FFmpeg/libavformat/psxstr.o \
../lib/FFmpeg/libavformat/pva.o \
../lib/FFmpeg/libavformat/pvfdec.o \
../lib/FFmpeg/libavformat/qcp.o \
../lib/FFmpeg/libavformat/qtpalette.o \
../lib/FFmpeg/libavformat/r3d.o \
../lib/FFmpeg/libavformat/rawdec.o \
../lib/FFmpeg/libavformat/rawenc.o \
../lib/FFmpeg/libavformat/rawutils.o \
../lib/FFmpeg/libavformat/rawvideodec.o \
../lib/FFmpeg/libavformat/rdt.o \
../lib/FFmpeg/libavformat/realtextdec.o \
../lib/FFmpeg/libavformat/redspark.o \
../lib/FFmpeg/libavformat/replaygain.o \
../lib/FFmpeg/libavformat/riff.o \
../lib/FFmpeg/libavformat/riffdec.o \
../lib/FFmpeg/libavformat/riffenc.o \
../lib/FFmpeg/libavformat/rl2.o \
../lib/FFmpeg/libavformat/rm.o \
../lib/FFmpeg/libavformat/rmdec.o \
../lib/FFmpeg/libavformat/rmenc.o \
../lib/FFmpeg/libavformat/rmsipr.o \
../lib/FFmpeg/libavformat/rpl.o \
../lib/FFmpeg/libavformat/rsd.o \
../lib/FFmpeg/libavformat/rso.o \
../lib/FFmpeg/libavformat/rsodec.o \
../lib/FFmpeg/libavformat/rsoenc.o \
../lib/FFmpeg/libavformat/rtmpdigest.o \
../lib/FFmpeg/libavformat/rtmphttp.o \
../lib/FFmpeg/libavformat/rtmppkt.o \
../lib/FFmpeg/libavformat/rtmpproto.o \
../lib/FFmpeg/libavformat/rtp.o \
../lib/FFmpeg/libavformat/rtpdec.o \
../lib/FFmpeg/libavformat/rtpdec_ac3.o \
../lib/FFmpeg/libavformat/rtpdec_amr.o \
../lib/FFmpeg/libavformat/rtpdec_asf.o \
../lib/FFmpeg/libavformat/rtpdec_dv.o \
../lib/FFmpeg/libavformat/rtpdec_g726.o \
../lib/FFmpeg/libavformat/rtpdec_h261.o \
../lib/FFmpeg/libavformat/rtpdec_h263.o \
../lib/FFmpeg/libavformat/rtpdec_h263_rfc2190.o \
../lib/FFmpeg/libavformat/rtpdec_h264.o \
../lib/FFmpeg/libavformat/rtpdec_hevc.o \
../lib/FFmpeg/libavformat/rtpdec_ilbc.o \
../lib/FFmpeg/libavformat/rtpdec_jpeg.o \
../lib/FFmpeg/libavformat/rtpdec_latm.o \
../lib/FFmpeg/libavformat/rtpdec_mpa_robust.o \
../lib/FFmpeg/libavformat/rtpdec_mpeg12.o \
../lib/FFmpeg/libavformat/rtpdec_mpeg4.o \
../lib/FFmpeg/libavformat/rtpdec_mpegts.o \
../lib/FFmpeg/libavformat/rtpdec_qcelp.o \
../lib/FFmpeg/libavformat/rtpdec_qdm2.o \
../lib/FFmpeg/libavformat/rtpdec_qt.o \
../lib/FFmpeg/libavformat/rtpdec_rfc4175.o \
../lib/FFmpeg/libavformat/rtpdec_svq3.o \
../lib/FFmpeg/libavformat/rtpdec_vc2hq.o \
../lib/FFmpeg/libavformat/rtpdec_vp8.o \
../lib/FFmpeg/libavformat/rtpdec_vp9.o \
../lib/FFmpeg/libavformat/rtpdec_xiph.o \
../lib/FFmpeg/libavformat/rtpenc.o \
../lib/FFmpeg/libavformat/rtpenc_aac.o \
../lib/FFmpeg/libavformat/rtpenc_amr.o \
../lib/FFmpeg/libavformat/rtpenc_chain.o \
../lib/FFmpeg/libavformat/rtpenc_h261.o \
../lib/FFmpeg/libavformat/rtpenc_h263.o \
../lib/FFmpeg/libavformat/rtpenc_h263_rfc2190.o \
../lib/FFmpeg/libavformat/rtpenc_h264_hevc.o \
../lib/FFmpeg/libavformat/rtpenc_jpeg.o \
../lib/FFmpeg/libavformat/rtpenc_latm.o \
../lib/FFmpeg/libavformat/rtpenc_mpegts.o \
../lib/FFmpeg/libavformat/rtpenc_mpv.o \
../lib/FFmpeg/libavformat/rtpenc_vc2hq.o \
../lib/FFmpeg/libavformat/rtpenc_vp8.o \
../lib/FFmpeg/libavformat/rtpenc_vp9.o \
../lib/FFmpeg/libavformat/rtpenc_xiph.o \
../lib/FFmpeg/libavformat/rtpproto.o \
../lib/FFmpeg/libavformat/rtsp.o \
../lib/FFmpeg/libavformat/rtspdec.o \
../lib/FFmpeg/libavformat/rtspenc.o \
../lib/FFmpeg/libavformat/s337m.o \
../lib/FFmpeg/libavformat/samidec.o \
../lib/FFmpeg/libavformat/sapdec.o \
../lib/FFmpeg/libavformat/sapenc.o \
../lib/FFmpeg/libavformat/sauce.o \
../lib/FFmpeg/libavformat/sbcdec.o \
../lib/FFmpeg/libavformat/sbgdec.o \
../lib/FFmpeg/libavformat/sccdec.o \
../lib/FFmpeg/libavformat/sccenc.o \
../lib/FFmpeg/libavformat/sdp.o \
../lib/FFmpeg/libavformat/sdr2.o \
../lib/FFmpeg/libavformat/sdsdec.o \
../lib/FFmpeg/libavformat/sdxdec.o \
../lib/FFmpeg/libavformat/segafilm.o \
../lib/FFmpeg/libavformat/segafilmenc.o \
../lib/FFmpeg/libavformat/segment.o \
../lib/FFmpeg/libavformat/serdec.o \
../lib/FFmpeg/libavformat/shortendec.o \
../lib/FFmpeg/libavformat/sierravmd.o \
../lib/FFmpeg/libavformat/siff.o \
../lib/FFmpeg/libavformat/smacker.o \
../lib/FFmpeg/libavformat/smjpeg.o \
../lib/FFmpeg/libavformat/smjpegdec.o \
../lib/FFmpeg/libavformat/smjpegenc.o \
../lib/FFmpeg/libavformat/smoothstreamingenc.o \
../lib/FFmpeg/libavformat/smush.o \
../lib/FFmpeg/libavformat/sol.o \
../lib/FFmpeg/libavformat/soxdec.o \
../lib/FFmpeg/libavformat/soxenc.o \
../lib/FFmpeg/libavformat/spdif.o \
../lib/FFmpeg/libavformat/spdifdec.o \
../lib/FFmpeg/libavformat/spdifenc.o \
../lib/FFmpeg/libavformat/srtdec.o \
../lib/FFmpeg/libavformat/srtenc.o \
../lib/FFmpeg/libavformat/srtp.o \
../lib/FFmpeg/libavformat/srtpproto.o \
../lib/FFmpeg/libavformat/stldec.o \
../lib/FFmpeg/libavformat/subfile.o \
../lib/FFmpeg/libavformat/subtitles.o \
../lib/FFmpeg/libavformat/subviewer1dec.o \
../lib/FFmpeg/libavformat/subviewerdec.o \
../lib/FFmpeg/libavformat/supdec.o \
../lib/FFmpeg/libavformat/supenc.o \
../lib/FFmpeg/libavformat/svag.o \
../lib/FFmpeg/libavformat/swf.o \
../lib/FFmpeg/libavformat/swfdec.o \
../lib/FFmpeg/libavformat/swfenc.o \
../lib/FFmpeg/libavformat/takdec.o \
../lib/FFmpeg/libavformat/tcp.o \
../lib/FFmpeg/libavformat/tedcaptionsdec.o \
../lib/FFmpeg/libavformat/tee.o \
../lib/FFmpeg/libavformat/tee_common.o \
../lib/FFmpeg/libavformat/teeproto.o \
../lib/FFmpeg/libavformat/thp.o \
../lib/FFmpeg/libavformat/tiertexseq.o \
../lib/FFmpeg/libavformat/tmv.o \
../lib/FFmpeg/libavformat/tta.o \
../lib/FFmpeg/libavformat/ttaenc.o \
../lib/FFmpeg/libavformat/tty.o \
../lib/FFmpeg/libavformat/txd.o \
../lib/FFmpeg/libavformat/ty.o \
../lib/FFmpeg/libavformat/udp.o \
../lib/FFmpeg/libavformat/uncodedframecrcenc.o \
../lib/FFmpeg/libavformat/unix.o \
../lib/FFmpeg/libavformat/url.o \
../lib/FFmpeg/libavformat/urldecode.o \
../lib/FFmpeg/libavformat/utils.o \
../lib/FFmpeg/libavformat/v210.o \
../lib/FFmpeg/libavformat/vag.o \
../lib/FFmpeg/libavformat/vc1dec.o \
../lib/FFmpeg/libavformat/vc1test.o \
../lib/FFmpeg/libavformat/vc1testenc.o \
../lib/FFmpeg/libavformat/vividas.o \
../lib/FFmpeg/libavformat/vivo.o \
../lib/FFmpeg/libavformat/voc.o \
../lib/FFmpeg/libavformat/voc_packet.o \
../lib/FFmpeg/libavformat/vocdec.o \
../lib/FFmpeg/libavformat/vocenc.o \
../lib/FFmpeg/libavformat/vorbiscomment.o \
../lib/FFmpeg/libavformat/vpcc.o \
../lib/FFmpeg/libavformat/vpk.o \
../lib/FFmpeg/libavformat/vplayerdec.o \
../lib/FFmpeg/libavformat/vqf.o \
../lib/FFmpeg/libavformat/w64.o \
../lib/FFmpeg/libavformat/wavdec.o \
../lib/FFmpeg/libavformat/wavenc.o \
../lib/FFmpeg/libavformat/wc3movie.o \
../lib/FFmpeg/libavformat/webm_chunk.o \
../lib/FFmpeg/libavformat/webmdashenc.o \
../lib/FFmpeg/libavformat/webpenc.o \
../lib/FFmpeg/libavformat/webvttdec.o \
../lib/FFmpeg/libavformat/webvttenc.o \
../lib/FFmpeg/libavformat/westwood_aud.o \
../lib/FFmpeg/libavformat/westwood_vqa.o \
../lib/FFmpeg/libavformat/wsddec.o \
../lib/FFmpeg/libavformat/wtv_common.o \
../lib/FFmpeg/libavformat/wtvdec.o \
../lib/FFmpeg/libavformat/wtvenc.o \
../lib/FFmpeg/libavformat/wv.o \
../lib/FFmpeg/libavformat/wvdec.o \
../lib/FFmpeg/libavformat/wvedec.o \
../lib/FFmpeg/libavformat/wvenc.o \
../lib/FFmpeg/libavformat/xa.o \
../lib/FFmpeg/libavformat/xmv.o \
../lib/FFmpeg/libavformat/xvag.o \
../lib/FFmpeg/libavformat/xwma.o \
../lib/FFmpeg/libavformat/yop.o \
../lib/FFmpeg/libavformat/yuv4mpegdec.o \
../lib/FFmpeg/libavformat/yuv4mpegenc.o 

OBJS += \
./lib/FFmpeg/libavformat/3dostr.o \
./lib/FFmpeg/libavformat/4xm.o \
./lib/FFmpeg/libavformat/a64.o \
./lib/FFmpeg/libavformat/aacdec.o \
./lib/FFmpeg/libavformat/aadec.o \
./lib/FFmpeg/libavformat/ac3dec.o \
./lib/FFmpeg/libavformat/acm.o \
./lib/FFmpeg/libavformat/act.o \
./lib/FFmpeg/libavformat/adp.o \
./lib/FFmpeg/libavformat/ads.o \
./lib/FFmpeg/libavformat/adtsenc.o \
./lib/FFmpeg/libavformat/adxdec.o \
./lib/FFmpeg/libavformat/aea.o \
./lib/FFmpeg/libavformat/afc.o \
./lib/FFmpeg/libavformat/aiffdec.o \
./lib/FFmpeg/libavformat/aiffenc.o \
./lib/FFmpeg/libavformat/aixdec.o \
./lib/FFmpeg/libavformat/allformats.o \
./lib/FFmpeg/libavformat/amr.o \
./lib/FFmpeg/libavformat/anm.o \
./lib/FFmpeg/libavformat/apc.o \
./lib/FFmpeg/libavformat/ape.o \
./lib/FFmpeg/libavformat/apetag.o \
./lib/FFmpeg/libavformat/apngdec.o \
./lib/FFmpeg/libavformat/apngenc.o \
./lib/FFmpeg/libavformat/aptxdec.o \
./lib/FFmpeg/libavformat/aqtitledec.o \
./lib/FFmpeg/libavformat/asf.o \
./lib/FFmpeg/libavformat/asfcrypt.o \
./lib/FFmpeg/libavformat/asfdec_f.o \
./lib/FFmpeg/libavformat/asfdec_o.o \
./lib/FFmpeg/libavformat/asfenc.o \
./lib/FFmpeg/libavformat/assdec.o \
./lib/FFmpeg/libavformat/assenc.o \
./lib/FFmpeg/libavformat/ast.o \
./lib/FFmpeg/libavformat/astdec.o \
./lib/FFmpeg/libavformat/astenc.o \
./lib/FFmpeg/libavformat/async.o \
./lib/FFmpeg/libavformat/au.o \
./lib/FFmpeg/libavformat/audiointerleave.o \
./lib/FFmpeg/libavformat/av1.o \
./lib/FFmpeg/libavformat/avc.o \
./lib/FFmpeg/libavformat/avidec.o \
./lib/FFmpeg/libavformat/avienc.o \
./lib/FFmpeg/libavformat/avio.o \
./lib/FFmpeg/libavformat/aviobuf.o \
./lib/FFmpeg/libavformat/avisynth.o \
./lib/FFmpeg/libavformat/avlanguage.o \
./lib/FFmpeg/libavformat/avr.o \
./lib/FFmpeg/libavformat/avs.o \
./lib/FFmpeg/libavformat/bethsoftvid.o \
./lib/FFmpeg/libavformat/bfi.o \
./lib/FFmpeg/libavformat/bink.o \
./lib/FFmpeg/libavformat/bintext.o \
./lib/FFmpeg/libavformat/bit.o \
./lib/FFmpeg/libavformat/bluray.o \
./lib/FFmpeg/libavformat/bmv.o \
./lib/FFmpeg/libavformat/boadec.o \
./lib/FFmpeg/libavformat/brstm.o \
./lib/FFmpeg/libavformat/c93.o \
./lib/FFmpeg/libavformat/cache.o \
./lib/FFmpeg/libavformat/caf.o \
./lib/FFmpeg/libavformat/cafdec.o \
./lib/FFmpeg/libavformat/cafenc.o \
./lib/FFmpeg/libavformat/cavsvideodec.o \
./lib/FFmpeg/libavformat/cdg.o \
./lib/FFmpeg/libavformat/cdxl.o \
./lib/FFmpeg/libavformat/chromaprint.o \
./lib/FFmpeg/libavformat/cinedec.o \
./lib/FFmpeg/libavformat/codec2.o \
./lib/FFmpeg/libavformat/concat.o \
./lib/FFmpeg/libavformat/concatdec.o \
./lib/FFmpeg/libavformat/crcenc.o \
./lib/FFmpeg/libavformat/crypto.o \
./lib/FFmpeg/libavformat/cutils.o \
./lib/FFmpeg/libavformat/dash.o \
./lib/FFmpeg/libavformat/dashdec.o \
./lib/FFmpeg/libavformat/dashenc.o \
./lib/FFmpeg/libavformat/data_uri.o \
./lib/FFmpeg/libavformat/dauddec.o \
./lib/FFmpeg/libavformat/daudenc.o \
./lib/FFmpeg/libavformat/davs2.o \
./lib/FFmpeg/libavformat/dcstr.o \
./lib/FFmpeg/libavformat/demuxer_list.o \
./lib/FFmpeg/libavformat/dfa.o \
./lib/FFmpeg/libavformat/dhav.o \
./lib/FFmpeg/libavformat/diracdec.o \
./lib/FFmpeg/libavformat/dnxhddec.o \
./lib/FFmpeg/libavformat/dsfdec.o \
./lib/FFmpeg/libavformat/dsicin.o \
./lib/FFmpeg/libavformat/dss.o \
./lib/FFmpeg/libavformat/dtsdec.o \
./lib/FFmpeg/libavformat/dtshddec.o \
./lib/FFmpeg/libavformat/dump.o \
./lib/FFmpeg/libavformat/dv.o \
./lib/FFmpeg/libavformat/dvbsub.o \
./lib/FFmpeg/libavformat/dvbtxt.o \
./lib/FFmpeg/libavformat/dvenc.o \
./lib/FFmpeg/libavformat/dxa.o \
./lib/FFmpeg/libavformat/eacdata.o \
./lib/FFmpeg/libavformat/electronicarts.o \
./lib/FFmpeg/libavformat/epafdec.o \
./lib/FFmpeg/libavformat/ffmetadec.o \
./lib/FFmpeg/libavformat/ffmetaenc.o \
./lib/FFmpeg/libavformat/fifo.o \
./lib/FFmpeg/libavformat/fifo_test.o \
./lib/FFmpeg/libavformat/file.o \
./lib/FFmpeg/libavformat/file_open.o \
./lib/FFmpeg/libavformat/filmstripdec.o \
./lib/FFmpeg/libavformat/filmstripenc.o \
./lib/FFmpeg/libavformat/fitsdec.o \
./lib/FFmpeg/libavformat/fitsenc.o \
./lib/FFmpeg/libavformat/flac_picture.o \
./lib/FFmpeg/libavformat/flacdec.o \
./lib/FFmpeg/libavformat/flacenc.o \
./lib/FFmpeg/libavformat/flacenc_header.o \
./lib/FFmpeg/libavformat/flic.o \
./lib/FFmpeg/libavformat/flvdec.o \
./lib/FFmpeg/libavformat/flvenc.o \
./lib/FFmpeg/libavformat/format.o \
./lib/FFmpeg/libavformat/framecrcenc.o \
./lib/FFmpeg/libavformat/framehash.o \
./lib/FFmpeg/libavformat/frmdec.o \
./lib/FFmpeg/libavformat/fsb.o \
./lib/FFmpeg/libavformat/ftp.o \
./lib/FFmpeg/libavformat/g722.o \
./lib/FFmpeg/libavformat/g723_1.o \
./lib/FFmpeg/libavformat/g726.o \
./lib/FFmpeg/libavformat/g729dec.o \
./lib/FFmpeg/libavformat/gdv.o \
./lib/FFmpeg/libavformat/genh.o \
./lib/FFmpeg/libavformat/gif.o \
./lib/FFmpeg/libavformat/gifdec.o \
./lib/FFmpeg/libavformat/golomb_tab.o \
./lib/FFmpeg/libavformat/gopher.o \
./lib/FFmpeg/libavformat/gsmdec.o \
./lib/FFmpeg/libavformat/gxf.o \
./lib/FFmpeg/libavformat/gxfenc.o \
./lib/FFmpeg/libavformat/h261dec.o \
./lib/FFmpeg/libavformat/h263dec.o \
./lib/FFmpeg/libavformat/h264dec.o \
./lib/FFmpeg/libavformat/hashenc.o \
./lib/FFmpeg/libavformat/hdsenc.o \
./lib/FFmpeg/libavformat/hevc.o \
./lib/FFmpeg/libavformat/hevcdec.o \
./lib/FFmpeg/libavformat/hls.o \
./lib/FFmpeg/libavformat/hlsenc.o \
./lib/FFmpeg/libavformat/hlsplaylist.o \
./lib/FFmpeg/libavformat/hlsproto.o \
./lib/FFmpeg/libavformat/hnm.o \
./lib/FFmpeg/libavformat/http.o \
./lib/FFmpeg/libavformat/httpauth.o \
./lib/FFmpeg/libavformat/icecast.o \
./lib/FFmpeg/libavformat/icodec.o \
./lib/FFmpeg/libavformat/icoenc.o \
./lib/FFmpeg/libavformat/id3v1.o \
./lib/FFmpeg/libavformat/id3v2.o \
./lib/FFmpeg/libavformat/id3v2enc.o \
./lib/FFmpeg/libavformat/idcin.o \
./lib/FFmpeg/libavformat/idroqdec.o \
./lib/FFmpeg/libavformat/idroqenc.o \
./lib/FFmpeg/libavformat/iff.o \
./lib/FFmpeg/libavformat/ilbc.o \
./lib/FFmpeg/libavformat/img2.o \
./lib/FFmpeg/libavformat/img2_alias_pix.o \
./lib/FFmpeg/libavformat/img2_brender_pix.o \
./lib/FFmpeg/libavformat/img2dec.o \
./lib/FFmpeg/libavformat/img2enc.o \
./lib/FFmpeg/libavformat/ingenientdec.o \
./lib/FFmpeg/libavformat/ip.o \
./lib/FFmpeg/libavformat/ipmovie.o \
./lib/FFmpeg/libavformat/ircam.o \
./lib/FFmpeg/libavformat/ircamdec.o \
./lib/FFmpeg/libavformat/ircamenc.o \
./lib/FFmpeg/libavformat/isom.o \
./lib/FFmpeg/libavformat/iss.o \
./lib/FFmpeg/libavformat/iv8.o \
./lib/FFmpeg/libavformat/ivfdec.o \
./lib/FFmpeg/libavformat/ivfenc.o \
./lib/FFmpeg/libavformat/jacosubdec.o \
./lib/FFmpeg/libavformat/jacosubenc.o \
./lib/FFmpeg/libavformat/jvdec.o \
./lib/FFmpeg/libavformat/latmenc.o \
./lib/FFmpeg/libavformat/libgme.o \
./lib/FFmpeg/libavformat/libmodplug.o \
./lib/FFmpeg/libavformat/libopenmpt.o \
./lib/FFmpeg/libavformat/librtmp.o \
./lib/FFmpeg/libavformat/libsmbclient.o \
./lib/FFmpeg/libavformat/libsrt.o \
./lib/FFmpeg/libavformat/libssh.o \
./lib/FFmpeg/libavformat/lmlm4.o \
./lib/FFmpeg/libavformat/loasdec.o \
./lib/FFmpeg/libavformat/log2_tab.o \
./lib/FFmpeg/libavformat/lrc.o \
./lib/FFmpeg/libavformat/lrcdec.o \
./lib/FFmpeg/libavformat/lrcenc.o \
./lib/FFmpeg/libavformat/lvfdec.o \
./lib/FFmpeg/libavformat/lxfdec.o \
./lib/FFmpeg/libavformat/m4vdec.o \
./lib/FFmpeg/libavformat/matroska.o \
./lib/FFmpeg/libavformat/matroskadec.o \
./lib/FFmpeg/libavformat/matroskaenc.o \
./lib/FFmpeg/libavformat/md5proto.o \
./lib/FFmpeg/libavformat/metadata.o \
./lib/FFmpeg/libavformat/mgsts.o \
./lib/FFmpeg/libavformat/microdvddec.o \
./lib/FFmpeg/libavformat/microdvdenc.o \
./lib/FFmpeg/libavformat/mj2kdec.o \
./lib/FFmpeg/libavformat/mkvtimestamp_v2.o \
./lib/FFmpeg/libavformat/mlpdec.o \
./lib/FFmpeg/libavformat/mlvdec.o \
./lib/FFmpeg/libavformat/mm.o \
./lib/FFmpeg/libavformat/mmf.o \
./lib/FFmpeg/libavformat/mms.o \
./lib/FFmpeg/libavformat/mmsh.o \
./lib/FFmpeg/libavformat/mmst.o \
./lib/FFmpeg/libavformat/mov.o \
./lib/FFmpeg/libavformat/mov_chan.o \
./lib/FFmpeg/libavformat/mov_esds.o \
./lib/FFmpeg/libavformat/movenc.o \
./lib/FFmpeg/libavformat/movenccenc.o \
./lib/FFmpeg/libavformat/movenchint.o \
./lib/FFmpeg/libavformat/mp3dec.o \
./lib/FFmpeg/libavformat/mp3enc.o \
./lib/FFmpeg/libavformat/mpc.o \
./lib/FFmpeg/libavformat/mpc8.o \
./lib/FFmpeg/libavformat/mpeg.o \
./lib/FFmpeg/libavformat/mpegenc.o \
./lib/FFmpeg/libavformat/mpegts.o \
./lib/FFmpeg/libavformat/mpegtsenc.o \
./lib/FFmpeg/libavformat/mpegvideodec.o \
./lib/FFmpeg/libavformat/mpjpeg.o \
./lib/FFmpeg/libavformat/mpjpegdec.o \
./lib/FFmpeg/libavformat/mpl2dec.o \
./lib/FFmpeg/libavformat/mpsubdec.o \
./lib/FFmpeg/libavformat/msf.o \
./lib/FFmpeg/libavformat/msnwc_tcp.o \
./lib/FFmpeg/libavformat/mtaf.o \
./lib/FFmpeg/libavformat/mtv.o \
./lib/FFmpeg/libavformat/musx.o \
./lib/FFmpeg/libavformat/mux.o \
./lib/FFmpeg/libavformat/muxer_list.o \
./lib/FFmpeg/libavformat/mvdec.o \
./lib/FFmpeg/libavformat/mvi.o \
./lib/FFmpeg/libavformat/mxf.o \
./lib/FFmpeg/libavformat/mxfdec.o \
./lib/FFmpeg/libavformat/mxfenc.o \
./lib/FFmpeg/libavformat/mxg.o \
./lib/FFmpeg/libavformat/ncdec.o \
./lib/FFmpeg/libavformat/network.o \
./lib/FFmpeg/libavformat/nistspheredec.o \
./lib/FFmpeg/libavformat/nspdec.o \
./lib/FFmpeg/libavformat/nsvdec.o \
./lib/FFmpeg/libavformat/nullenc.o \
./lib/FFmpeg/libavformat/nut.o \
./lib/FFmpeg/libavformat/nutdec.o \
./lib/FFmpeg/libavformat/nutenc.o \
./lib/FFmpeg/libavformat/nuv.o \
./lib/FFmpeg/libavformat/oggdec.o \
./lib/FFmpeg/libavformat/oggenc.o \
./lib/FFmpeg/libavformat/oggparsecelt.o \
./lib/FFmpeg/libavformat/oggparsedaala.o \
./lib/FFmpeg/libavformat/oggparsedirac.o \
./lib/FFmpeg/libavformat/oggparseflac.o \
./lib/FFmpeg/libavformat/oggparseogm.o \
./lib/FFmpeg/libavformat/oggparseopus.o \
./lib/FFmpeg/libavformat/oggparseskeleton.o \
./lib/FFmpeg/libavformat/oggparsespeex.o \
./lib/FFmpeg/libavformat/oggparsetheora.o \
./lib/FFmpeg/libavformat/oggparsevorbis.o \
./lib/FFmpeg/libavformat/oggparsevp8.o \
./lib/FFmpeg/libavformat/oma.o \
./lib/FFmpeg/libavformat/omadec.o \
./lib/FFmpeg/libavformat/omaenc.o \
./lib/FFmpeg/libavformat/options.o \
./lib/FFmpeg/libavformat/os_support.o \
./lib/FFmpeg/libavformat/paf.o \
./lib/FFmpeg/libavformat/pcm.o \
./lib/FFmpeg/libavformat/pcmdec.o \
./lib/FFmpeg/libavformat/pcmenc.o \
./lib/FFmpeg/libavformat/pjsdec.o \
./lib/FFmpeg/libavformat/pmpdec.o \
./lib/FFmpeg/libavformat/prompeg.o \
./lib/FFmpeg/libavformat/protocol_list.o \
./lib/FFmpeg/libavformat/protocols.o \
./lib/FFmpeg/libavformat/psxstr.o \
./lib/FFmpeg/libavformat/pva.o \
./lib/FFmpeg/libavformat/pvfdec.o \
./lib/FFmpeg/libavformat/qcp.o \
./lib/FFmpeg/libavformat/qtpalette.o \
./lib/FFmpeg/libavformat/r3d.o \
./lib/FFmpeg/libavformat/rawdec.o \
./lib/FFmpeg/libavformat/rawenc.o \
./lib/FFmpeg/libavformat/rawutils.o \
./lib/FFmpeg/libavformat/rawvideodec.o \
./lib/FFmpeg/libavformat/rdt.o \
./lib/FFmpeg/libavformat/realtextdec.o \
./lib/FFmpeg/libavformat/redspark.o \
./lib/FFmpeg/libavformat/replaygain.o \
./lib/FFmpeg/libavformat/riff.o \
./lib/FFmpeg/libavformat/riffdec.o \
./lib/FFmpeg/libavformat/riffenc.o \
./lib/FFmpeg/libavformat/rl2.o \
./lib/FFmpeg/libavformat/rm.o \
./lib/FFmpeg/libavformat/rmdec.o \
./lib/FFmpeg/libavformat/rmenc.o \
./lib/FFmpeg/libavformat/rmsipr.o \
./lib/FFmpeg/libavformat/rpl.o \
./lib/FFmpeg/libavformat/rsd.o \
./lib/FFmpeg/libavformat/rso.o \
./lib/FFmpeg/libavformat/rsodec.o \
./lib/FFmpeg/libavformat/rsoenc.o \
./lib/FFmpeg/libavformat/rtmpcrypt.o \
./lib/FFmpeg/libavformat/rtmpdh.o \
./lib/FFmpeg/libavformat/rtmpdigest.o \
./lib/FFmpeg/libavformat/rtmphttp.o \
./lib/FFmpeg/libavformat/rtmppkt.o \
./lib/FFmpeg/libavformat/rtmpproto.o \
./lib/FFmpeg/libavformat/rtp.o \
./lib/FFmpeg/libavformat/rtpdec.o \
./lib/FFmpeg/libavformat/rtpdec_ac3.o \
./lib/FFmpeg/libavformat/rtpdec_amr.o \
./lib/FFmpeg/libavformat/rtpdec_asf.o \
./lib/FFmpeg/libavformat/rtpdec_dv.o \
./lib/FFmpeg/libavformat/rtpdec_g726.o \
./lib/FFmpeg/libavformat/rtpdec_h261.o \
./lib/FFmpeg/libavformat/rtpdec_h263.o \
./lib/FFmpeg/libavformat/rtpdec_h263_rfc2190.o \
./lib/FFmpeg/libavformat/rtpdec_h264.o \
./lib/FFmpeg/libavformat/rtpdec_hevc.o \
./lib/FFmpeg/libavformat/rtpdec_ilbc.o \
./lib/FFmpeg/libavformat/rtpdec_jpeg.o \
./lib/FFmpeg/libavformat/rtpdec_latm.o \
./lib/FFmpeg/libavformat/rtpdec_mpa_robust.o \
./lib/FFmpeg/libavformat/rtpdec_mpeg12.o \
./lib/FFmpeg/libavformat/rtpdec_mpeg4.o \
./lib/FFmpeg/libavformat/rtpdec_mpegts.o \
./lib/FFmpeg/libavformat/rtpdec_qcelp.o \
./lib/FFmpeg/libavformat/rtpdec_qdm2.o \
./lib/FFmpeg/libavformat/rtpdec_qt.o \
./lib/FFmpeg/libavformat/rtpdec_rfc4175.o \
./lib/FFmpeg/libavformat/rtpdec_svq3.o \
./lib/FFmpeg/libavformat/rtpdec_vc2hq.o \
./lib/FFmpeg/libavformat/rtpdec_vp8.o \
./lib/FFmpeg/libavformat/rtpdec_vp9.o \
./lib/FFmpeg/libavformat/rtpdec_xiph.o \
./lib/FFmpeg/libavformat/rtpenc.o \
./lib/FFmpeg/libavformat/rtpenc_aac.o \
./lib/FFmpeg/libavformat/rtpenc_amr.o \
./lib/FFmpeg/libavformat/rtpenc_chain.o \
./lib/FFmpeg/libavformat/rtpenc_h261.o \
./lib/FFmpeg/libavformat/rtpenc_h263.o \
./lib/FFmpeg/libavformat/rtpenc_h263_rfc2190.o \
./lib/FFmpeg/libavformat/rtpenc_h264_hevc.o \
./lib/FFmpeg/libavformat/rtpenc_jpeg.o \
./lib/FFmpeg/libavformat/rtpenc_latm.o \
./lib/FFmpeg/libavformat/rtpenc_mpegts.o \
./lib/FFmpeg/libavformat/rtpenc_mpv.o \
./lib/FFmpeg/libavformat/rtpenc_vc2hq.o \
./lib/FFmpeg/libavformat/rtpenc_vp8.o \
./lib/FFmpeg/libavformat/rtpenc_vp9.o \
./lib/FFmpeg/libavformat/rtpenc_xiph.o \
./lib/FFmpeg/libavformat/rtpproto.o \
./lib/FFmpeg/libavformat/rtsp.o \
./lib/FFmpeg/libavformat/rtspdec.o \
./lib/FFmpeg/libavformat/rtspenc.o \
./lib/FFmpeg/libavformat/s337m.o \
./lib/FFmpeg/libavformat/samidec.o \
./lib/FFmpeg/libavformat/sapdec.o \
./lib/FFmpeg/libavformat/sapenc.o \
./lib/FFmpeg/libavformat/sauce.o \
./lib/FFmpeg/libavformat/sbcdec.o \
./lib/FFmpeg/libavformat/sbgdec.o \
./lib/FFmpeg/libavformat/sccdec.o \
./lib/FFmpeg/libavformat/sccenc.o \
./lib/FFmpeg/libavformat/sctp.o \
./lib/FFmpeg/libavformat/sdp.o \
./lib/FFmpeg/libavformat/sdr2.o \
./lib/FFmpeg/libavformat/sdsdec.o \
./lib/FFmpeg/libavformat/sdxdec.o \
./lib/FFmpeg/libavformat/segafilm.o \
./lib/FFmpeg/libavformat/segafilmenc.o \
./lib/FFmpeg/libavformat/segment.o \
./lib/FFmpeg/libavformat/serdec.o \
./lib/FFmpeg/libavformat/shortendec.o \
./lib/FFmpeg/libavformat/sierravmd.o \
./lib/FFmpeg/libavformat/siff.o \
./lib/FFmpeg/libavformat/smacker.o \
./lib/FFmpeg/libavformat/smjpeg.o \
./lib/FFmpeg/libavformat/smjpegdec.o \
./lib/FFmpeg/libavformat/smjpegenc.o \
./lib/FFmpeg/libavformat/smoothstreamingenc.o \
./lib/FFmpeg/libavformat/smush.o \
./lib/FFmpeg/libavformat/sol.o \
./lib/FFmpeg/libavformat/soxdec.o \
./lib/FFmpeg/libavformat/soxenc.o \
./lib/FFmpeg/libavformat/spdif.o \
./lib/FFmpeg/libavformat/spdifdec.o \
./lib/FFmpeg/libavformat/spdifenc.o \
./lib/FFmpeg/libavformat/srtdec.o \
./lib/FFmpeg/libavformat/srtenc.o \
./lib/FFmpeg/libavformat/srtp.o \
./lib/FFmpeg/libavformat/srtpproto.o \
./lib/FFmpeg/libavformat/stldec.o \
./lib/FFmpeg/libavformat/subfile.o \
./lib/FFmpeg/libavformat/subtitles.o \
./lib/FFmpeg/libavformat/subviewer1dec.o \
./lib/FFmpeg/libavformat/subviewerdec.o \
./lib/FFmpeg/libavformat/supdec.o \
./lib/FFmpeg/libavformat/supenc.o \
./lib/FFmpeg/libavformat/svag.o \
./lib/FFmpeg/libavformat/swf.o \
./lib/FFmpeg/libavformat/swfdec.o \
./lib/FFmpeg/libavformat/swfenc.o \
./lib/FFmpeg/libavformat/takdec.o \
./lib/FFmpeg/libavformat/tcp.o \
./lib/FFmpeg/libavformat/tedcaptionsdec.o \
./lib/FFmpeg/libavformat/tee.o \
./lib/FFmpeg/libavformat/tee_common.o \
./lib/FFmpeg/libavformat/teeproto.o \
./lib/FFmpeg/libavformat/thp.o \
./lib/FFmpeg/libavformat/tiertexseq.o \
./lib/FFmpeg/libavformat/tls.o \
./lib/FFmpeg/libavformat/tls_gnutls.o \
./lib/FFmpeg/libavformat/tls_libtls.o \
./lib/FFmpeg/libavformat/tls_mbedtls.o \
./lib/FFmpeg/libavformat/tls_openssl.o \
./lib/FFmpeg/libavformat/tls_schannel.o \
./lib/FFmpeg/libavformat/tls_securetransport.o \
./lib/FFmpeg/libavformat/tmv.o \
./lib/FFmpeg/libavformat/tta.o \
./lib/FFmpeg/libavformat/ttaenc.o \
./lib/FFmpeg/libavformat/tty.o \
./lib/FFmpeg/libavformat/txd.o \
./lib/FFmpeg/libavformat/ty.o \
./lib/FFmpeg/libavformat/udp.o \
./lib/FFmpeg/libavformat/uncodedframecrcenc.o \
./lib/FFmpeg/libavformat/unix.o \
./lib/FFmpeg/libavformat/url.o \
./lib/FFmpeg/libavformat/urldecode.o \
./lib/FFmpeg/libavformat/utils.o \
./lib/FFmpeg/libavformat/v210.o \
./lib/FFmpeg/libavformat/vag.o \
./lib/FFmpeg/libavformat/vapoursynth.o \
./lib/FFmpeg/libavformat/vc1dec.o \
./lib/FFmpeg/libavformat/vc1test.o \
./lib/FFmpeg/libavformat/vc1testenc.o \
./lib/FFmpeg/libavformat/vividas.o \
./lib/FFmpeg/libavformat/vivo.o \
./lib/FFmpeg/libavformat/voc.o \
./lib/FFmpeg/libavformat/voc_packet.o \
./lib/FFmpeg/libavformat/vocdec.o \
./lib/FFmpeg/libavformat/vocenc.o \
./lib/FFmpeg/libavformat/vorbiscomment.o \
./lib/FFmpeg/libavformat/vpcc.o \
./lib/FFmpeg/libavformat/vpk.o \
./lib/FFmpeg/libavformat/vplayerdec.o \
./lib/FFmpeg/libavformat/vqf.o \
./lib/FFmpeg/libavformat/w64.o \
./lib/FFmpeg/libavformat/wavdec.o \
./lib/FFmpeg/libavformat/wavenc.o \
./lib/FFmpeg/libavformat/wc3movie.o \
./lib/FFmpeg/libavformat/webm_chunk.o \
./lib/FFmpeg/libavformat/webmdashenc.o \
./lib/FFmpeg/libavformat/webpenc.o \
./lib/FFmpeg/libavformat/webvttdec.o \
./lib/FFmpeg/libavformat/webvttenc.o \
./lib/FFmpeg/libavformat/westwood_aud.o \
./lib/FFmpeg/libavformat/westwood_vqa.o \
./lib/FFmpeg/libavformat/wsddec.o \
./lib/FFmpeg/libavformat/wtv_common.o \
./lib/FFmpeg/libavformat/wtvdec.o \
./lib/FFmpeg/libavformat/wtvenc.o \
./lib/FFmpeg/libavformat/wv.o \
./lib/FFmpeg/libavformat/wvdec.o \
./lib/FFmpeg/libavformat/wvedec.o \
./lib/FFmpeg/libavformat/wvenc.o \
./lib/FFmpeg/libavformat/xa.o \
./lib/FFmpeg/libavformat/xmv.o \
./lib/FFmpeg/libavformat/xvag.o \
./lib/FFmpeg/libavformat/xwma.o \
./lib/FFmpeg/libavformat/yop.o \
./lib/FFmpeg/libavformat/yuv4mpegdec.o \
./lib/FFmpeg/libavformat/yuv4mpegenc.o 

C_DEPS += \
./lib/FFmpeg/libavformat/3dostr.d \
./lib/FFmpeg/libavformat/4xm.d \
./lib/FFmpeg/libavformat/a64.d \
./lib/FFmpeg/libavformat/aacdec.d \
./lib/FFmpeg/libavformat/aadec.d \
./lib/FFmpeg/libavformat/ac3dec.d \
./lib/FFmpeg/libavformat/acm.d \
./lib/FFmpeg/libavformat/act.d \
./lib/FFmpeg/libavformat/adp.d \
./lib/FFmpeg/libavformat/ads.d \
./lib/FFmpeg/libavformat/adtsenc.d \
./lib/FFmpeg/libavformat/adxdec.d \
./lib/FFmpeg/libavformat/aea.d \
./lib/FFmpeg/libavformat/afc.d \
./lib/FFmpeg/libavformat/aiffdec.d \
./lib/FFmpeg/libavformat/aiffenc.d \
./lib/FFmpeg/libavformat/aixdec.d \
./lib/FFmpeg/libavformat/allformats.d \
./lib/FFmpeg/libavformat/amr.d \
./lib/FFmpeg/libavformat/anm.d \
./lib/FFmpeg/libavformat/apc.d \
./lib/FFmpeg/libavformat/ape.d \
./lib/FFmpeg/libavformat/apetag.d \
./lib/FFmpeg/libavformat/apngdec.d \
./lib/FFmpeg/libavformat/apngenc.d \
./lib/FFmpeg/libavformat/aptxdec.d \
./lib/FFmpeg/libavformat/aqtitledec.d \
./lib/FFmpeg/libavformat/asf.d \
./lib/FFmpeg/libavformat/asfcrypt.d \
./lib/FFmpeg/libavformat/asfdec_f.d \
./lib/FFmpeg/libavformat/asfdec_o.d \
./lib/FFmpeg/libavformat/asfenc.d \
./lib/FFmpeg/libavformat/assdec.d \
./lib/FFmpeg/libavformat/assenc.d \
./lib/FFmpeg/libavformat/ast.d \
./lib/FFmpeg/libavformat/astdec.d \
./lib/FFmpeg/libavformat/astenc.d \
./lib/FFmpeg/libavformat/async.d \
./lib/FFmpeg/libavformat/au.d \
./lib/FFmpeg/libavformat/audiointerleave.d \
./lib/FFmpeg/libavformat/av1.d \
./lib/FFmpeg/libavformat/avc.d \
./lib/FFmpeg/libavformat/avidec.d \
./lib/FFmpeg/libavformat/avienc.d \
./lib/FFmpeg/libavformat/avio.d \
./lib/FFmpeg/libavformat/aviobuf.d \
./lib/FFmpeg/libavformat/avisynth.d \
./lib/FFmpeg/libavformat/avlanguage.d \
./lib/FFmpeg/libavformat/avr.d \
./lib/FFmpeg/libavformat/avs.d \
./lib/FFmpeg/libavformat/bethsoftvid.d \
./lib/FFmpeg/libavformat/bfi.d \
./lib/FFmpeg/libavformat/bink.d \
./lib/FFmpeg/libavformat/bintext.d \
./lib/FFmpeg/libavformat/bit.d \
./lib/FFmpeg/libavformat/bluray.d \
./lib/FFmpeg/libavformat/bmv.d \
./lib/FFmpeg/libavformat/boadec.d \
./lib/FFmpeg/libavformat/brstm.d \
./lib/FFmpeg/libavformat/c93.d \
./lib/FFmpeg/libavformat/cache.d \
./lib/FFmpeg/libavformat/caf.d \
./lib/FFmpeg/libavformat/cafdec.d \
./lib/FFmpeg/libavformat/cafenc.d \
./lib/FFmpeg/libavformat/cavsvideodec.d \
./lib/FFmpeg/libavformat/cdg.d \
./lib/FFmpeg/libavformat/cdxl.d \
./lib/FFmpeg/libavformat/chromaprint.d \
./lib/FFmpeg/libavformat/cinedec.d \
./lib/FFmpeg/libavformat/codec2.d \
./lib/FFmpeg/libavformat/concat.d \
./lib/FFmpeg/libavformat/concatdec.d \
./lib/FFmpeg/libavformat/crcenc.d \
./lib/FFmpeg/libavformat/crypto.d \
./lib/FFmpeg/libavformat/cutils.d \
./lib/FFmpeg/libavformat/dash.d \
./lib/FFmpeg/libavformat/dashdec.d \
./lib/FFmpeg/libavformat/dashenc.d \
./lib/FFmpeg/libavformat/data_uri.d \
./lib/FFmpeg/libavformat/dauddec.d \
./lib/FFmpeg/libavformat/daudenc.d \
./lib/FFmpeg/libavformat/davs2.d \
./lib/FFmpeg/libavformat/dcstr.d \
./lib/FFmpeg/libavformat/demuxer_list.d \
./lib/FFmpeg/libavformat/dfa.d \
./lib/FFmpeg/libavformat/dhav.d \
./lib/FFmpeg/libavformat/diracdec.d \
./lib/FFmpeg/libavformat/dnxhddec.d \
./lib/FFmpeg/libavformat/dsfdec.d \
./lib/FFmpeg/libavformat/dsicin.d \
./lib/FFmpeg/libavformat/dss.d \
./lib/FFmpeg/libavformat/dtsdec.d \
./lib/FFmpeg/libavformat/dtshddec.d \
./lib/FFmpeg/libavformat/dump.d \
./lib/FFmpeg/libavformat/dv.d \
./lib/FFmpeg/libavformat/dvbsub.d \
./lib/FFmpeg/libavformat/dvbtxt.d \
./lib/FFmpeg/libavformat/dvenc.d \
./lib/FFmpeg/libavformat/dxa.d \
./lib/FFmpeg/libavformat/eacdata.d \
./lib/FFmpeg/libavformat/electronicarts.d \
./lib/FFmpeg/libavformat/epafdec.d \
./lib/FFmpeg/libavformat/ffmetadec.d \
./lib/FFmpeg/libavformat/ffmetaenc.d \
./lib/FFmpeg/libavformat/fifo.d \
./lib/FFmpeg/libavformat/fifo_test.d \
./lib/FFmpeg/libavformat/file.d \
./lib/FFmpeg/libavformat/file_open.d \
./lib/FFmpeg/libavformat/filmstripdec.d \
./lib/FFmpeg/libavformat/filmstripenc.d \
./lib/FFmpeg/libavformat/fitsdec.d \
./lib/FFmpeg/libavformat/fitsenc.d \
./lib/FFmpeg/libavformat/flac_picture.d \
./lib/FFmpeg/libavformat/flacdec.d \
./lib/FFmpeg/libavformat/flacenc.d \
./lib/FFmpeg/libavformat/flacenc_header.d \
./lib/FFmpeg/libavformat/flic.d \
./lib/FFmpeg/libavformat/flvdec.d \
./lib/FFmpeg/libavformat/flvenc.d \
./lib/FFmpeg/libavformat/format.d \
./lib/FFmpeg/libavformat/framecrcenc.d \
./lib/FFmpeg/libavformat/framehash.d \
./lib/FFmpeg/libavformat/frmdec.d \
./lib/FFmpeg/libavformat/fsb.d \
./lib/FFmpeg/libavformat/ftp.d \
./lib/FFmpeg/libavformat/g722.d \
./lib/FFmpeg/libavformat/g723_1.d \
./lib/FFmpeg/libavformat/g726.d \
./lib/FFmpeg/libavformat/g729dec.d \
./lib/FFmpeg/libavformat/gdv.d \
./lib/FFmpeg/libavformat/genh.d \
./lib/FFmpeg/libavformat/gif.d \
./lib/FFmpeg/libavformat/gifdec.d \
./lib/FFmpeg/libavformat/golomb_tab.d \
./lib/FFmpeg/libavformat/gopher.d \
./lib/FFmpeg/libavformat/gsmdec.d \
./lib/FFmpeg/libavformat/gxf.d \
./lib/FFmpeg/libavformat/gxfenc.d \
./lib/FFmpeg/libavformat/h261dec.d \
./lib/FFmpeg/libavformat/h263dec.d \
./lib/FFmpeg/libavformat/h264dec.d \
./lib/FFmpeg/libavformat/hashenc.d \
./lib/FFmpeg/libavformat/hdsenc.d \
./lib/FFmpeg/libavformat/hevc.d \
./lib/FFmpeg/libavformat/hevcdec.d \
./lib/FFmpeg/libavformat/hls.d \
./lib/FFmpeg/libavformat/hlsenc.d \
./lib/FFmpeg/libavformat/hlsplaylist.d \
./lib/FFmpeg/libavformat/hlsproto.d \
./lib/FFmpeg/libavformat/hnm.d \
./lib/FFmpeg/libavformat/http.d \
./lib/FFmpeg/libavformat/httpauth.d \
./lib/FFmpeg/libavformat/icecast.d \
./lib/FFmpeg/libavformat/icodec.d \
./lib/FFmpeg/libavformat/icoenc.d \
./lib/FFmpeg/libavformat/id3v1.d \
./lib/FFmpeg/libavformat/id3v2.d \
./lib/FFmpeg/libavformat/id3v2enc.d \
./lib/FFmpeg/libavformat/idcin.d \
./lib/FFmpeg/libavformat/idroqdec.d \
./lib/FFmpeg/libavformat/idroqenc.d \
./lib/FFmpeg/libavformat/iff.d \
./lib/FFmpeg/libavformat/ilbc.d \
./lib/FFmpeg/libavformat/img2.d \
./lib/FFmpeg/libavformat/img2_alias_pix.d \
./lib/FFmpeg/libavformat/img2_brender_pix.d \
./lib/FFmpeg/libavformat/img2dec.d \
./lib/FFmpeg/libavformat/img2enc.d \
./lib/FFmpeg/libavformat/ingenientdec.d \
./lib/FFmpeg/libavformat/ip.d \
./lib/FFmpeg/libavformat/ipmovie.d \
./lib/FFmpeg/libavformat/ircam.d \
./lib/FFmpeg/libavformat/ircamdec.d \
./lib/FFmpeg/libavformat/ircamenc.d \
./lib/FFmpeg/libavformat/isom.d \
./lib/FFmpeg/libavformat/iss.d \
./lib/FFmpeg/libavformat/iv8.d \
./lib/FFmpeg/libavformat/ivfdec.d \
./lib/FFmpeg/libavformat/ivfenc.d \
./lib/FFmpeg/libavformat/jacosubdec.d \
./lib/FFmpeg/libavformat/jacosubenc.d \
./lib/FFmpeg/libavformat/jvdec.d \
./lib/FFmpeg/libavformat/latmenc.d \
./lib/FFmpeg/libavformat/libgme.d \
./lib/FFmpeg/libavformat/libmodplug.d \
./lib/FFmpeg/libavformat/libopenmpt.d \
./lib/FFmpeg/libavformat/librtmp.d \
./lib/FFmpeg/libavformat/libsmbclient.d \
./lib/FFmpeg/libavformat/libsrt.d \
./lib/FFmpeg/libavformat/libssh.d \
./lib/FFmpeg/libavformat/lmlm4.d \
./lib/FFmpeg/libavformat/loasdec.d \
./lib/FFmpeg/libavformat/log2_tab.d \
./lib/FFmpeg/libavformat/lrc.d \
./lib/FFmpeg/libavformat/lrcdec.d \
./lib/FFmpeg/libavformat/lrcenc.d \
./lib/FFmpeg/libavformat/lvfdec.d \
./lib/FFmpeg/libavformat/lxfdec.d \
./lib/FFmpeg/libavformat/m4vdec.d \
./lib/FFmpeg/libavformat/matroska.d \
./lib/FFmpeg/libavformat/matroskadec.d \
./lib/FFmpeg/libavformat/matroskaenc.d \
./lib/FFmpeg/libavformat/md5proto.d \
./lib/FFmpeg/libavformat/metadata.d \
./lib/FFmpeg/libavformat/mgsts.d \
./lib/FFmpeg/libavformat/microdvddec.d \
./lib/FFmpeg/libavformat/microdvdenc.d \
./lib/FFmpeg/libavformat/mj2kdec.d \
./lib/FFmpeg/libavformat/mkvtimestamp_v2.d \
./lib/FFmpeg/libavformat/mlpdec.d \
./lib/FFmpeg/libavformat/mlvdec.d \
./lib/FFmpeg/libavformat/mm.d \
./lib/FFmpeg/libavformat/mmf.d \
./lib/FFmpeg/libavformat/mms.d \
./lib/FFmpeg/libavformat/mmsh.d \
./lib/FFmpeg/libavformat/mmst.d \
./lib/FFmpeg/libavformat/mov.d \
./lib/FFmpeg/libavformat/mov_chan.d \
./lib/FFmpeg/libavformat/mov_esds.d \
./lib/FFmpeg/libavformat/movenc.d \
./lib/FFmpeg/libavformat/movenccenc.d \
./lib/FFmpeg/libavformat/movenchint.d \
./lib/FFmpeg/libavformat/mp3dec.d \
./lib/FFmpeg/libavformat/mp3enc.d \
./lib/FFmpeg/libavformat/mpc.d \
./lib/FFmpeg/libavformat/mpc8.d \
./lib/FFmpeg/libavformat/mpeg.d \
./lib/FFmpeg/libavformat/mpegenc.d \
./lib/FFmpeg/libavformat/mpegts.d \
./lib/FFmpeg/libavformat/mpegtsenc.d \
./lib/FFmpeg/libavformat/mpegvideodec.d \
./lib/FFmpeg/libavformat/mpjpeg.d \
./lib/FFmpeg/libavformat/mpjpegdec.d \
./lib/FFmpeg/libavformat/mpl2dec.d \
./lib/FFmpeg/libavformat/mpsubdec.d \
./lib/FFmpeg/libavformat/msf.d \
./lib/FFmpeg/libavformat/msnwc_tcp.d \
./lib/FFmpeg/libavformat/mtaf.d \
./lib/FFmpeg/libavformat/mtv.d \
./lib/FFmpeg/libavformat/musx.d \
./lib/FFmpeg/libavformat/mux.d \
./lib/FFmpeg/libavformat/muxer_list.d \
./lib/FFmpeg/libavformat/mvdec.d \
./lib/FFmpeg/libavformat/mvi.d \
./lib/FFmpeg/libavformat/mxf.d \
./lib/FFmpeg/libavformat/mxfdec.d \
./lib/FFmpeg/libavformat/mxfenc.d \
./lib/FFmpeg/libavformat/mxg.d \
./lib/FFmpeg/libavformat/ncdec.d \
./lib/FFmpeg/libavformat/network.d \
./lib/FFmpeg/libavformat/nistspheredec.d \
./lib/FFmpeg/libavformat/nspdec.d \
./lib/FFmpeg/libavformat/nsvdec.d \
./lib/FFmpeg/libavformat/nullenc.d \
./lib/FFmpeg/libavformat/nut.d \
./lib/FFmpeg/libavformat/nutdec.d \
./lib/FFmpeg/libavformat/nutenc.d \
./lib/FFmpeg/libavformat/nuv.d \
./lib/FFmpeg/libavformat/oggdec.d \
./lib/FFmpeg/libavformat/oggenc.d \
./lib/FFmpeg/libavformat/oggparsecelt.d \
./lib/FFmpeg/libavformat/oggparsedaala.d \
./lib/FFmpeg/libavformat/oggparsedirac.d \
./lib/FFmpeg/libavformat/oggparseflac.d \
./lib/FFmpeg/libavformat/oggparseogm.d \
./lib/FFmpeg/libavformat/oggparseopus.d \
./lib/FFmpeg/libavformat/oggparseskeleton.d \
./lib/FFmpeg/libavformat/oggparsespeex.d \
./lib/FFmpeg/libavformat/oggparsetheora.d \
./lib/FFmpeg/libavformat/oggparsevorbis.d \
./lib/FFmpeg/libavformat/oggparsevp8.d \
./lib/FFmpeg/libavformat/oma.d \
./lib/FFmpeg/libavformat/omadec.d \
./lib/FFmpeg/libavformat/omaenc.d \
./lib/FFmpeg/libavformat/options.d \
./lib/FFmpeg/libavformat/os_support.d \
./lib/FFmpeg/libavformat/paf.d \
./lib/FFmpeg/libavformat/pcm.d \
./lib/FFmpeg/libavformat/pcmdec.d \
./lib/FFmpeg/libavformat/pcmenc.d \
./lib/FFmpeg/libavformat/pjsdec.d \
./lib/FFmpeg/libavformat/pmpdec.d \
./lib/FFmpeg/libavformat/prompeg.d \
./lib/FFmpeg/libavformat/protocol_list.d \
./lib/FFmpeg/libavformat/protocols.d \
./lib/FFmpeg/libavformat/psxstr.d \
./lib/FFmpeg/libavformat/pva.d \
./lib/FFmpeg/libavformat/pvfdec.d \
./lib/FFmpeg/libavformat/qcp.d \
./lib/FFmpeg/libavformat/qtpalette.d \
./lib/FFmpeg/libavformat/r3d.d \
./lib/FFmpeg/libavformat/rawdec.d \
./lib/FFmpeg/libavformat/rawenc.d \
./lib/FFmpeg/libavformat/rawutils.d \
./lib/FFmpeg/libavformat/rawvideodec.d \
./lib/FFmpeg/libavformat/rdt.d \
./lib/FFmpeg/libavformat/realtextdec.d \
./lib/FFmpeg/libavformat/redspark.d \
./lib/FFmpeg/libavformat/replaygain.d \
./lib/FFmpeg/libavformat/riff.d \
./lib/FFmpeg/libavformat/riffdec.d \
./lib/FFmpeg/libavformat/riffenc.d \
./lib/FFmpeg/libavformat/rl2.d \
./lib/FFmpeg/libavformat/rm.d \
./lib/FFmpeg/libavformat/rmdec.d \
./lib/FFmpeg/libavformat/rmenc.d \
./lib/FFmpeg/libavformat/rmsipr.d \
./lib/FFmpeg/libavformat/rpl.d \
./lib/FFmpeg/libavformat/rsd.d \
./lib/FFmpeg/libavformat/rso.d \
./lib/FFmpeg/libavformat/rsodec.d \
./lib/FFmpeg/libavformat/rsoenc.d \
./lib/FFmpeg/libavformat/rtmpcrypt.d \
./lib/FFmpeg/libavformat/rtmpdh.d \
./lib/FFmpeg/libavformat/rtmpdigest.d \
./lib/FFmpeg/libavformat/rtmphttp.d \
./lib/FFmpeg/libavformat/rtmppkt.d \
./lib/FFmpeg/libavformat/rtmpproto.d \
./lib/FFmpeg/libavformat/rtp.d \
./lib/FFmpeg/libavformat/rtpdec.d \
./lib/FFmpeg/libavformat/rtpdec_ac3.d \
./lib/FFmpeg/libavformat/rtpdec_amr.d \
./lib/FFmpeg/libavformat/rtpdec_asf.d \
./lib/FFmpeg/libavformat/rtpdec_dv.d \
./lib/FFmpeg/libavformat/rtpdec_g726.d \
./lib/FFmpeg/libavformat/rtpdec_h261.d \
./lib/FFmpeg/libavformat/rtpdec_h263.d \
./lib/FFmpeg/libavformat/rtpdec_h263_rfc2190.d \
./lib/FFmpeg/libavformat/rtpdec_h264.d \
./lib/FFmpeg/libavformat/rtpdec_hevc.d \
./lib/FFmpeg/libavformat/rtpdec_ilbc.d \
./lib/FFmpeg/libavformat/rtpdec_jpeg.d \
./lib/FFmpeg/libavformat/rtpdec_latm.d \
./lib/FFmpeg/libavformat/rtpdec_mpa_robust.d \
./lib/FFmpeg/libavformat/rtpdec_mpeg12.d \
./lib/FFmpeg/libavformat/rtpdec_mpeg4.d \
./lib/FFmpeg/libavformat/rtpdec_mpegts.d \
./lib/FFmpeg/libavformat/rtpdec_qcelp.d \
./lib/FFmpeg/libavformat/rtpdec_qdm2.d \
./lib/FFmpeg/libavformat/rtpdec_qt.d \
./lib/FFmpeg/libavformat/rtpdec_rfc4175.d \
./lib/FFmpeg/libavformat/rtpdec_svq3.d \
./lib/FFmpeg/libavformat/rtpdec_vc2hq.d \
./lib/FFmpeg/libavformat/rtpdec_vp8.d \
./lib/FFmpeg/libavformat/rtpdec_vp9.d \
./lib/FFmpeg/libavformat/rtpdec_xiph.d \
./lib/FFmpeg/libavformat/rtpenc.d \
./lib/FFmpeg/libavformat/rtpenc_aac.d \
./lib/FFmpeg/libavformat/rtpenc_amr.d \
./lib/FFmpeg/libavformat/rtpenc_chain.d \
./lib/FFmpeg/libavformat/rtpenc_h261.d \
./lib/FFmpeg/libavformat/rtpenc_h263.d \
./lib/FFmpeg/libavformat/rtpenc_h263_rfc2190.d \
./lib/FFmpeg/libavformat/rtpenc_h264_hevc.d \
./lib/FFmpeg/libavformat/rtpenc_jpeg.d \
./lib/FFmpeg/libavformat/rtpenc_latm.d \
./lib/FFmpeg/libavformat/rtpenc_mpegts.d \
./lib/FFmpeg/libavformat/rtpenc_mpv.d \
./lib/FFmpeg/libavformat/rtpenc_vc2hq.d \
./lib/FFmpeg/libavformat/rtpenc_vp8.d \
./lib/FFmpeg/libavformat/rtpenc_vp9.d \
./lib/FFmpeg/libavformat/rtpenc_xiph.d \
./lib/FFmpeg/libavformat/rtpproto.d \
./lib/FFmpeg/libavformat/rtsp.d \
./lib/FFmpeg/libavformat/rtspdec.d \
./lib/FFmpeg/libavformat/rtspenc.d \
./lib/FFmpeg/libavformat/s337m.d \
./lib/FFmpeg/libavformat/samidec.d \
./lib/FFmpeg/libavformat/sapdec.d \
./lib/FFmpeg/libavformat/sapenc.d \
./lib/FFmpeg/libavformat/sauce.d \
./lib/FFmpeg/libavformat/sbcdec.d \
./lib/FFmpeg/libavformat/sbgdec.d \
./lib/FFmpeg/libavformat/sccdec.d \
./lib/FFmpeg/libavformat/sccenc.d \
./lib/FFmpeg/libavformat/sctp.d \
./lib/FFmpeg/libavformat/sdp.d \
./lib/FFmpeg/libavformat/sdr2.d \
./lib/FFmpeg/libavformat/sdsdec.d \
./lib/FFmpeg/libavformat/sdxdec.d \
./lib/FFmpeg/libavformat/segafilm.d \
./lib/FFmpeg/libavformat/segafilmenc.d \
./lib/FFmpeg/libavformat/segment.d \
./lib/FFmpeg/libavformat/serdec.d \
./lib/FFmpeg/libavformat/shortendec.d \
./lib/FFmpeg/libavformat/sierravmd.d \
./lib/FFmpeg/libavformat/siff.d \
./lib/FFmpeg/libavformat/smacker.d \
./lib/FFmpeg/libavformat/smjpeg.d \
./lib/FFmpeg/libavformat/smjpegdec.d \
./lib/FFmpeg/libavformat/smjpegenc.d \
./lib/FFmpeg/libavformat/smoothstreamingenc.d \
./lib/FFmpeg/libavformat/smush.d \
./lib/FFmpeg/libavformat/sol.d \
./lib/FFmpeg/libavformat/soxdec.d \
./lib/FFmpeg/libavformat/soxenc.d \
./lib/FFmpeg/libavformat/spdif.d \
./lib/FFmpeg/libavformat/spdifdec.d \
./lib/FFmpeg/libavformat/spdifenc.d \
./lib/FFmpeg/libavformat/srtdec.d \
./lib/FFmpeg/libavformat/srtenc.d \
./lib/FFmpeg/libavformat/srtp.d \
./lib/FFmpeg/libavformat/srtpproto.d \
./lib/FFmpeg/libavformat/stldec.d \
./lib/FFmpeg/libavformat/subfile.d \
./lib/FFmpeg/libavformat/subtitles.d \
./lib/FFmpeg/libavformat/subviewer1dec.d \
./lib/FFmpeg/libavformat/subviewerdec.d \
./lib/FFmpeg/libavformat/supdec.d \
./lib/FFmpeg/libavformat/supenc.d \
./lib/FFmpeg/libavformat/svag.d \
./lib/FFmpeg/libavformat/swf.d \
./lib/FFmpeg/libavformat/swfdec.d \
./lib/FFmpeg/libavformat/swfenc.d \
./lib/FFmpeg/libavformat/takdec.d \
./lib/FFmpeg/libavformat/tcp.d \
./lib/FFmpeg/libavformat/tedcaptionsdec.d \
./lib/FFmpeg/libavformat/tee.d \
./lib/FFmpeg/libavformat/tee_common.d \
./lib/FFmpeg/libavformat/teeproto.d \
./lib/FFmpeg/libavformat/thp.d \
./lib/FFmpeg/libavformat/tiertexseq.d \
./lib/FFmpeg/libavformat/tls.d \
./lib/FFmpeg/libavformat/tls_gnutls.d \
./lib/FFmpeg/libavformat/tls_libtls.d \
./lib/FFmpeg/libavformat/tls_mbedtls.d \
./lib/FFmpeg/libavformat/tls_openssl.d \
./lib/FFmpeg/libavformat/tls_schannel.d \
./lib/FFmpeg/libavformat/tls_securetransport.d \
./lib/FFmpeg/libavformat/tmv.d \
./lib/FFmpeg/libavformat/tta.d \
./lib/FFmpeg/libavformat/ttaenc.d \
./lib/FFmpeg/libavformat/tty.d \
./lib/FFmpeg/libavformat/txd.d \
./lib/FFmpeg/libavformat/ty.d \
./lib/FFmpeg/libavformat/udp.d \
./lib/FFmpeg/libavformat/uncodedframecrcenc.d \
./lib/FFmpeg/libavformat/unix.d \
./lib/FFmpeg/libavformat/url.d \
./lib/FFmpeg/libavformat/urldecode.d \
./lib/FFmpeg/libavformat/utils.d \
./lib/FFmpeg/libavformat/v210.d \
./lib/FFmpeg/libavformat/vag.d \
./lib/FFmpeg/libavformat/vapoursynth.d \
./lib/FFmpeg/libavformat/vc1dec.d \
./lib/FFmpeg/libavformat/vc1test.d \
./lib/FFmpeg/libavformat/vc1testenc.d \
./lib/FFmpeg/libavformat/vividas.d \
./lib/FFmpeg/libavformat/vivo.d \
./lib/FFmpeg/libavformat/voc.d \
./lib/FFmpeg/libavformat/voc_packet.d \
./lib/FFmpeg/libavformat/vocdec.d \
./lib/FFmpeg/libavformat/vocenc.d \
./lib/FFmpeg/libavformat/vorbiscomment.d \
./lib/FFmpeg/libavformat/vpcc.d \
./lib/FFmpeg/libavformat/vpk.d \
./lib/FFmpeg/libavformat/vplayerdec.d \
./lib/FFmpeg/libavformat/vqf.d \
./lib/FFmpeg/libavformat/w64.d \
./lib/FFmpeg/libavformat/wavdec.d \
./lib/FFmpeg/libavformat/wavenc.d \
./lib/FFmpeg/libavformat/wc3movie.d \
./lib/FFmpeg/libavformat/webm_chunk.d \
./lib/FFmpeg/libavformat/webmdashenc.d \
./lib/FFmpeg/libavformat/webpenc.d \
./lib/FFmpeg/libavformat/webvttdec.d \
./lib/FFmpeg/libavformat/webvttenc.d \
./lib/FFmpeg/libavformat/westwood_aud.d \
./lib/FFmpeg/libavformat/westwood_vqa.d \
./lib/FFmpeg/libavformat/wsddec.d \
./lib/FFmpeg/libavformat/wtv_common.d \
./lib/FFmpeg/libavformat/wtvdec.d \
./lib/FFmpeg/libavformat/wtvenc.d \
./lib/FFmpeg/libavformat/wv.d \
./lib/FFmpeg/libavformat/wvdec.d \
./lib/FFmpeg/libavformat/wvedec.d \
./lib/FFmpeg/libavformat/wvenc.d \
./lib/FFmpeg/libavformat/xa.d \
./lib/FFmpeg/libavformat/xmv.d \
./lib/FFmpeg/libavformat/xvag.d \
./lib/FFmpeg/libavformat/xwma.d \
./lib/FFmpeg/libavformat/yop.d \
./lib/FFmpeg/libavformat/yuv4mpegdec.d \
./lib/FFmpeg/libavformat/yuv4mpegenc.d 


# Each subdirectory must supply rules for building sources it contributes
lib/FFmpeg/libavformat/%.o: ../lib/FFmpeg/libavformat/%.c
	@echo 'Building file: $<'
	@echo 'Invoking: GCC C Compiler'
	gcc -O0 -g3 -Wall -c -fmessage-length=0 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@)" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '


