################################################################################
# Automatically-generated file. Do not edit!
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
C_SRCS += \
../lib/FFmpeg/libavcodec/mips/aaccoder_mips.c \
../lib/FFmpeg/libavcodec/mips/aacdec_mips.c \
../lib/FFmpeg/libavcodec/mips/aacpsdsp_mips.c \
../lib/FFmpeg/libavcodec/mips/aacsbr_mips.c \
../lib/FFmpeg/libavcodec/mips/ac3dsp_mips.c \
../lib/FFmpeg/libavcodec/mips/acelp_filters_mips.c \
../lib/FFmpeg/libavcodec/mips/acelp_vectors_mips.c \
../lib/FFmpeg/libavcodec/mips/amrwbdec_mips.c \
../lib/FFmpeg/libavcodec/mips/blockdsp_init_mips.c \
../lib/FFmpeg/libavcodec/mips/blockdsp_mmi.c \
../lib/FFmpeg/libavcodec/mips/blockdsp_msa.c \
../lib/FFmpeg/libavcodec/mips/celp_filters_mips.c \
../lib/FFmpeg/libavcodec/mips/celp_math_mips.c \
../lib/FFmpeg/libavcodec/mips/constants.c \
../lib/FFmpeg/libavcodec/mips/fft_mips.c \
../lib/FFmpeg/libavcodec/mips/fmtconvert_mips.c \
../lib/FFmpeg/libavcodec/mips/h263dsp_init_mips.c \
../lib/FFmpeg/libavcodec/mips/h263dsp_msa.c \
../lib/FFmpeg/libavcodec/mips/h264chroma_init_mips.c \
../lib/FFmpeg/libavcodec/mips/h264chroma_mmi.c \
../lib/FFmpeg/libavcodec/mips/h264chroma_msa.c \
../lib/FFmpeg/libavcodec/mips/h264dsp_init_mips.c \
../lib/FFmpeg/libavcodec/mips/h264dsp_mmi.c \
../lib/FFmpeg/libavcodec/mips/h264dsp_msa.c \
../lib/FFmpeg/libavcodec/mips/h264idct_msa.c \
../lib/FFmpeg/libavcodec/mips/h264pred_init_mips.c \
../lib/FFmpeg/libavcodec/mips/h264pred_mmi.c \
../lib/FFmpeg/libavcodec/mips/h264pred_msa.c \
../lib/FFmpeg/libavcodec/mips/h264qpel_init_mips.c \
../lib/FFmpeg/libavcodec/mips/h264qpel_mmi.c \
../lib/FFmpeg/libavcodec/mips/h264qpel_msa.c \
../lib/FFmpeg/libavcodec/mips/hevc_idct_msa.c \
../lib/FFmpeg/libavcodec/mips/hevc_lpf_sao_msa.c \
../lib/FFmpeg/libavcodec/mips/hevc_mc_bi_msa.c \
../lib/FFmpeg/libavcodec/mips/hevc_mc_biw_msa.c \
../lib/FFmpeg/libavcodec/mips/hevc_mc_uni_msa.c \
../lib/FFmpeg/libavcodec/mips/hevc_mc_uniw_msa.c \
../lib/FFmpeg/libavcodec/mips/hevcdsp_init_mips.c \
../lib/FFmpeg/libavcodec/mips/hevcdsp_msa.c \
../lib/FFmpeg/libavcodec/mips/hevcpred_init_mips.c \
../lib/FFmpeg/libavcodec/mips/hevcpred_msa.c \
../lib/FFmpeg/libavcodec/mips/hpeldsp_init_mips.c \
../lib/FFmpeg/libavcodec/mips/hpeldsp_mmi.c \
../lib/FFmpeg/libavcodec/mips/hpeldsp_msa.c \
../lib/FFmpeg/libavcodec/mips/idctdsp_init_mips.c \
../lib/FFmpeg/libavcodec/mips/idctdsp_mmi.c \
../lib/FFmpeg/libavcodec/mips/idctdsp_msa.c \
../lib/FFmpeg/libavcodec/mips/iirfilter_mips.c \
../lib/FFmpeg/libavcodec/mips/me_cmp_init_mips.c \
../lib/FFmpeg/libavcodec/mips/me_cmp_msa.c \
../lib/FFmpeg/libavcodec/mips/mpegaudiodsp_mips_fixed.c \
../lib/FFmpeg/libavcodec/mips/mpegaudiodsp_mips_float.c \
../lib/FFmpeg/libavcodec/mips/mpegvideo_init_mips.c \
../lib/FFmpeg/libavcodec/mips/mpegvideo_mmi.c \
../lib/FFmpeg/libavcodec/mips/mpegvideo_msa.c \
../lib/FFmpeg/libavcodec/mips/mpegvideoencdsp_init_mips.c \
../lib/FFmpeg/libavcodec/mips/mpegvideoencdsp_msa.c \
../lib/FFmpeg/libavcodec/mips/pixblockdsp_init_mips.c \
../lib/FFmpeg/libavcodec/mips/pixblockdsp_mmi.c \
../lib/FFmpeg/libavcodec/mips/pixblockdsp_msa.c \
../lib/FFmpeg/libavcodec/mips/qpeldsp_init_mips.c \
../lib/FFmpeg/libavcodec/mips/qpeldsp_msa.c \
../lib/FFmpeg/libavcodec/mips/sbrdsp_mips.c \
../lib/FFmpeg/libavcodec/mips/simple_idct_mmi.c \
../lib/FFmpeg/libavcodec/mips/simple_idct_msa.c \
../lib/FFmpeg/libavcodec/mips/vc1dsp_init_mips.c \
../lib/FFmpeg/libavcodec/mips/vc1dsp_mmi.c \
../lib/FFmpeg/libavcodec/mips/videodsp_init.c \
../lib/FFmpeg/libavcodec/mips/vp3dsp_idct_msa.c \
../lib/FFmpeg/libavcodec/mips/vp3dsp_init_mips.c \
../lib/FFmpeg/libavcodec/mips/vp8_idct_msa.c \
../lib/FFmpeg/libavcodec/mips/vp8_lpf_msa.c \
../lib/FFmpeg/libavcodec/mips/vp8_mc_msa.c \
../lib/FFmpeg/libavcodec/mips/vp8dsp_init_mips.c \
../lib/FFmpeg/libavcodec/mips/vp8dsp_mmi.c \
../lib/FFmpeg/libavcodec/mips/vp9_idct_msa.c \
../lib/FFmpeg/libavcodec/mips/vp9_intra_msa.c \
../lib/FFmpeg/libavcodec/mips/vp9_lpf_msa.c \
../lib/FFmpeg/libavcodec/mips/vp9_mc_msa.c \
../lib/FFmpeg/libavcodec/mips/vp9dsp_init_mips.c \
../lib/FFmpeg/libavcodec/mips/wmv2dsp_init_mips.c \
../lib/FFmpeg/libavcodec/mips/wmv2dsp_mmi.c \
../lib/FFmpeg/libavcodec/mips/xvid_idct_mmi.c \
../lib/FFmpeg/libavcodec/mips/xvididct_init_mips.c 

OBJS += \
./lib/FFmpeg/libavcodec/mips/aaccoder_mips.o \
./lib/FFmpeg/libavcodec/mips/aacdec_mips.o \
./lib/FFmpeg/libavcodec/mips/aacpsdsp_mips.o \
./lib/FFmpeg/libavcodec/mips/aacsbr_mips.o \
./lib/FFmpeg/libavcodec/mips/ac3dsp_mips.o \
./lib/FFmpeg/libavcodec/mips/acelp_filters_mips.o \
./lib/FFmpeg/libavcodec/mips/acelp_vectors_mips.o \
./lib/FFmpeg/libavcodec/mips/amrwbdec_mips.o \
./lib/FFmpeg/libavcodec/mips/blockdsp_init_mips.o \
./lib/FFmpeg/libavcodec/mips/blockdsp_mmi.o \
./lib/FFmpeg/libavcodec/mips/blockdsp_msa.o \
./lib/FFmpeg/libavcodec/mips/celp_filters_mips.o \
./lib/FFmpeg/libavcodec/mips/celp_math_mips.o \
./lib/FFmpeg/libavcodec/mips/constants.o \
./lib/FFmpeg/libavcodec/mips/fft_mips.o \
./lib/FFmpeg/libavcodec/mips/fmtconvert_mips.o \
./lib/FFmpeg/libavcodec/mips/h263dsp_init_mips.o \
./lib/FFmpeg/libavcodec/mips/h263dsp_msa.o \
./lib/FFmpeg/libavcodec/mips/h264chroma_init_mips.o \
./lib/FFmpeg/libavcodec/mips/h264chroma_mmi.o \
./lib/FFmpeg/libavcodec/mips/h264chroma_msa.o \
./lib/FFmpeg/libavcodec/mips/h264dsp_init_mips.o \
./lib/FFmpeg/libavcodec/mips/h264dsp_mmi.o \
./lib/FFmpeg/libavcodec/mips/h264dsp_msa.o \
./lib/FFmpeg/libavcodec/mips/h264idct_msa.o \
./lib/FFmpeg/libavcodec/mips/h264pred_init_mips.o \
./lib/FFmpeg/libavcodec/mips/h264pred_mmi.o \
./lib/FFmpeg/libavcodec/mips/h264pred_msa.o \
./lib/FFmpeg/libavcodec/mips/h264qpel_init_mips.o \
./lib/FFmpeg/libavcodec/mips/h264qpel_mmi.o \
./lib/FFmpeg/libavcodec/mips/h264qpel_msa.o \
./lib/FFmpeg/libavcodec/mips/hevc_idct_msa.o \
./lib/FFmpeg/libavcodec/mips/hevc_lpf_sao_msa.o \
./lib/FFmpeg/libavcodec/mips/hevc_mc_bi_msa.o \
./lib/FFmpeg/libavcodec/mips/hevc_mc_biw_msa.o \
./lib/FFmpeg/libavcodec/mips/hevc_mc_uni_msa.o \
./lib/FFmpeg/libavcodec/mips/hevc_mc_uniw_msa.o \
./lib/FFmpeg/libavcodec/mips/hevcdsp_init_mips.o \
./lib/FFmpeg/libavcodec/mips/hevcdsp_msa.o \
./lib/FFmpeg/libavcodec/mips/hevcpred_init_mips.o \
./lib/FFmpeg/libavcodec/mips/hevcpred_msa.o \
./lib/FFmpeg/libavcodec/mips/hpeldsp_init_mips.o \
./lib/FFmpeg/libavcodec/mips/hpeldsp_mmi.o \
./lib/FFmpeg/libavcodec/mips/hpeldsp_msa.o \
./lib/FFmpeg/libavcodec/mips/idctdsp_init_mips.o \
./lib/FFmpeg/libavcodec/mips/idctdsp_mmi.o \
./lib/FFmpeg/libavcodec/mips/idctdsp_msa.o \
./lib/FFmpeg/libavcodec/mips/iirfilter_mips.o \
./lib/FFmpeg/libavcodec/mips/me_cmp_init_mips.o \
./lib/FFmpeg/libavcodec/mips/me_cmp_msa.o \
./lib/FFmpeg/libavcodec/mips/mpegaudiodsp_mips_fixed.o \
./lib/FFmpeg/libavcodec/mips/mpegaudiodsp_mips_float.o \
./lib/FFmpeg/libavcodec/mips/mpegvideo_init_mips.o \
./lib/FFmpeg/libavcodec/mips/mpegvideo_mmi.o \
./lib/FFmpeg/libavcodec/mips/mpegvideo_msa.o \
./lib/FFmpeg/libavcodec/mips/mpegvideoencdsp_init_mips.o \
./lib/FFmpeg/libavcodec/mips/mpegvideoencdsp_msa.o \
./lib/FFmpeg/libavcodec/mips/pixblockdsp_init_mips.o \
./lib/FFmpeg/libavcodec/mips/pixblockdsp_mmi.o \
./lib/FFmpeg/libavcodec/mips/pixblockdsp_msa.o \
./lib/FFmpeg/libavcodec/mips/qpeldsp_init_mips.o \
./lib/FFmpeg/libavcodec/mips/qpeldsp_msa.o \
./lib/FFmpeg/libavcodec/mips/sbrdsp_mips.o \
./lib/FFmpeg/libavcodec/mips/simple_idct_mmi.o \
./lib/FFmpeg/libavcodec/mips/simple_idct_msa.o \
./lib/FFmpeg/libavcodec/mips/vc1dsp_init_mips.o \
./lib/FFmpeg/libavcodec/mips/vc1dsp_mmi.o \
./lib/FFmpeg/libavcodec/mips/videodsp_init.o \
./lib/FFmpeg/libavcodec/mips/vp3dsp_idct_msa.o \
./lib/FFmpeg/libavcodec/mips/vp3dsp_init_mips.o \
./lib/FFmpeg/libavcodec/mips/vp8_idct_msa.o \
./lib/FFmpeg/libavcodec/mips/vp8_lpf_msa.o \
./lib/FFmpeg/libavcodec/mips/vp8_mc_msa.o \
./lib/FFmpeg/libavcodec/mips/vp8dsp_init_mips.o \
./lib/FFmpeg/libavcodec/mips/vp8dsp_mmi.o \
./lib/FFmpeg/libavcodec/mips/vp9_idct_msa.o \
./lib/FFmpeg/libavcodec/mips/vp9_intra_msa.o \
./lib/FFmpeg/libavcodec/mips/vp9_lpf_msa.o \
./lib/FFmpeg/libavcodec/mips/vp9_mc_msa.o \
./lib/FFmpeg/libavcodec/mips/vp9dsp_init_mips.o \
./lib/FFmpeg/libavcodec/mips/wmv2dsp_init_mips.o \
./lib/FFmpeg/libavcodec/mips/wmv2dsp_mmi.o \
./lib/FFmpeg/libavcodec/mips/xvid_idct_mmi.o \
./lib/FFmpeg/libavcodec/mips/xvididct_init_mips.o 

C_DEPS += \
./lib/FFmpeg/libavcodec/mips/aaccoder_mips.d \
./lib/FFmpeg/libavcodec/mips/aacdec_mips.d \
./lib/FFmpeg/libavcodec/mips/aacpsdsp_mips.d \
./lib/FFmpeg/libavcodec/mips/aacsbr_mips.d \
./lib/FFmpeg/libavcodec/mips/ac3dsp_mips.d \
./lib/FFmpeg/libavcodec/mips/acelp_filters_mips.d \
./lib/FFmpeg/libavcodec/mips/acelp_vectors_mips.d \
./lib/FFmpeg/libavcodec/mips/amrwbdec_mips.d \
./lib/FFmpeg/libavcodec/mips/blockdsp_init_mips.d \
./lib/FFmpeg/libavcodec/mips/blockdsp_mmi.d \
./lib/FFmpeg/libavcodec/mips/blockdsp_msa.d \
./lib/FFmpeg/libavcodec/mips/celp_filters_mips.d \
./lib/FFmpeg/libavcodec/mips/celp_math_mips.d \
./lib/FFmpeg/libavcodec/mips/constants.d \
./lib/FFmpeg/libavcodec/mips/fft_mips.d \
./lib/FFmpeg/libavcodec/mips/fmtconvert_mips.d \
./lib/FFmpeg/libavcodec/mips/h263dsp_init_mips.d \
./lib/FFmpeg/libavcodec/mips/h263dsp_msa.d \
./lib/FFmpeg/libavcodec/mips/h264chroma_init_mips.d \
./lib/FFmpeg/libavcodec/mips/h264chroma_mmi.d \
./lib/FFmpeg/libavcodec/mips/h264chroma_msa.d \
./lib/FFmpeg/libavcodec/mips/h264dsp_init_mips.d \
./lib/FFmpeg/libavcodec/mips/h264dsp_mmi.d \
./lib/FFmpeg/libavcodec/mips/h264dsp_msa.d \
./lib/FFmpeg/libavcodec/mips/h264idct_msa.d \
./lib/FFmpeg/libavcodec/mips/h264pred_init_mips.d \
./lib/FFmpeg/libavcodec/mips/h264pred_mmi.d \
./lib/FFmpeg/libavcodec/mips/h264pred_msa.d \
./lib/FFmpeg/libavcodec/mips/h264qpel_init_mips.d \
./lib/FFmpeg/libavcodec/mips/h264qpel_mmi.d \
./lib/FFmpeg/libavcodec/mips/h264qpel_msa.d \
./lib/FFmpeg/libavcodec/mips/hevc_idct_msa.d \
./lib/FFmpeg/libavcodec/mips/hevc_lpf_sao_msa.d \
./lib/FFmpeg/libavcodec/mips/hevc_mc_bi_msa.d \
./lib/FFmpeg/libavcodec/mips/hevc_mc_biw_msa.d \
./lib/FFmpeg/libavcodec/mips/hevc_mc_uni_msa.d \
./lib/FFmpeg/libavcodec/mips/hevc_mc_uniw_msa.d \
./lib/FFmpeg/libavcodec/mips/hevcdsp_init_mips.d \
./lib/FFmpeg/libavcodec/mips/hevcdsp_msa.d \
./lib/FFmpeg/libavcodec/mips/hevcpred_init_mips.d \
./lib/FFmpeg/libavcodec/mips/hevcpred_msa.d \
./lib/FFmpeg/libavcodec/mips/hpeldsp_init_mips.d \
./lib/FFmpeg/libavcodec/mips/hpeldsp_mmi.d \
./lib/FFmpeg/libavcodec/mips/hpeldsp_msa.d \
./lib/FFmpeg/libavcodec/mips/idctdsp_init_mips.d \
./lib/FFmpeg/libavcodec/mips/idctdsp_mmi.d \
./lib/FFmpeg/libavcodec/mips/idctdsp_msa.d \
./lib/FFmpeg/libavcodec/mips/iirfilter_mips.d \
./lib/FFmpeg/libavcodec/mips/me_cmp_init_mips.d \
./lib/FFmpeg/libavcodec/mips/me_cmp_msa.d \
./lib/FFmpeg/libavcodec/mips/mpegaudiodsp_mips_fixed.d \
./lib/FFmpeg/libavcodec/mips/mpegaudiodsp_mips_float.d \
./lib/FFmpeg/libavcodec/mips/mpegvideo_init_mips.d \
./lib/FFmpeg/libavcodec/mips/mpegvideo_mmi.d \
./lib/FFmpeg/libavcodec/mips/mpegvideo_msa.d \
./lib/FFmpeg/libavcodec/mips/mpegvideoencdsp_init_mips.d \
./lib/FFmpeg/libavcodec/mips/mpegvideoencdsp_msa.d \
./lib/FFmpeg/libavcodec/mips/pixblockdsp_init_mips.d \
./lib/FFmpeg/libavcodec/mips/pixblockdsp_mmi.d \
./lib/FFmpeg/libavcodec/mips/pixblockdsp_msa.d \
./lib/FFmpeg/libavcodec/mips/qpeldsp_init_mips.d \
./lib/FFmpeg/libavcodec/mips/qpeldsp_msa.d \
./lib/FFmpeg/libavcodec/mips/sbrdsp_mips.d \
./lib/FFmpeg/libavcodec/mips/simple_idct_mmi.d \
./lib/FFmpeg/libavcodec/mips/simple_idct_msa.d \
./lib/FFmpeg/libavcodec/mips/vc1dsp_init_mips.d \
./lib/FFmpeg/libavcodec/mips/vc1dsp_mmi.d \
./lib/FFmpeg/libavcodec/mips/videodsp_init.d \
./lib/FFmpeg/libavcodec/mips/vp3dsp_idct_msa.d \
./lib/FFmpeg/libavcodec/mips/vp3dsp_init_mips.d \
./lib/FFmpeg/libavcodec/mips/vp8_idct_msa.d \
./lib/FFmpeg/libavcodec/mips/vp8_lpf_msa.d \
./lib/FFmpeg/libavcodec/mips/vp8_mc_msa.d \
./lib/FFmpeg/libavcodec/mips/vp8dsp_init_mips.d \
./lib/FFmpeg/libavcodec/mips/vp8dsp_mmi.d \
./lib/FFmpeg/libavcodec/mips/vp9_idct_msa.d \
./lib/FFmpeg/libavcodec/mips/vp9_intra_msa.d \
./lib/FFmpeg/libavcodec/mips/vp9_lpf_msa.d \
./lib/FFmpeg/libavcodec/mips/vp9_mc_msa.d \
./lib/FFmpeg/libavcodec/mips/vp9dsp_init_mips.d \
./lib/FFmpeg/libavcodec/mips/wmv2dsp_init_mips.d \
./lib/FFmpeg/libavcodec/mips/wmv2dsp_mmi.d \
./lib/FFmpeg/libavcodec/mips/xvid_idct_mmi.d \
./lib/FFmpeg/libavcodec/mips/xvididct_init_mips.d 


# Each subdirectory must supply rules for building sources it contributes
lib/FFmpeg/libavcodec/mips/%.o: ../lib/FFmpeg/libavcodec/mips/%.c
	@echo 'Building file: $<'
	@echo 'Invoking: GCC C Compiler'
	gcc -O0 -g3 -Wall -c -fmessage-length=0 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@)" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '


