################################################################################
# Automatically-generated file. Do not edit!
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
C_SRCS += \
../lib/ImageMagick/coders/aai.c \
../lib/ImageMagick/coders/art.c \
../lib/ImageMagick/coders/avs.c \
../lib/ImageMagick/coders/bgr.c \
../lib/ImageMagick/coders/bmp.c \
../lib/ImageMagick/coders/braille.c \
../lib/ImageMagick/coders/cals.c \
../lib/ImageMagick/coders/caption.c \
../lib/ImageMagick/coders/cin.c \
../lib/ImageMagick/coders/cip.c \
../lib/ImageMagick/coders/clip.c \
../lib/ImageMagick/coders/clipboard.c \
../lib/ImageMagick/coders/cmyk.c \
../lib/ImageMagick/coders/cube.c \
../lib/ImageMagick/coders/cut.c \
../lib/ImageMagick/coders/dcm.c \
../lib/ImageMagick/coders/dds.c \
../lib/ImageMagick/coders/debug.c \
../lib/ImageMagick/coders/dib.c \
../lib/ImageMagick/coders/djvu.c \
../lib/ImageMagick/coders/dng.c \
../lib/ImageMagick/coders/dot.c \
../lib/ImageMagick/coders/dps.c \
../lib/ImageMagick/coders/dpx.c \
../lib/ImageMagick/coders/emf.c \
../lib/ImageMagick/coders/ept.c \
../lib/ImageMagick/coders/exr.c \
../lib/ImageMagick/coders/fax.c \
../lib/ImageMagick/coders/fits.c \
../lib/ImageMagick/coders/flif.c \
../lib/ImageMagick/coders/fpx.c \
../lib/ImageMagick/coders/gif.c \
../lib/ImageMagick/coders/gradient.c \
../lib/ImageMagick/coders/gray.c \
../lib/ImageMagick/coders/hald.c \
../lib/ImageMagick/coders/hdr.c \
../lib/ImageMagick/coders/heic.c \
../lib/ImageMagick/coders/histogram.c \
../lib/ImageMagick/coders/hrz.c \
../lib/ImageMagick/coders/html.c \
../lib/ImageMagick/coders/icon.c \
../lib/ImageMagick/coders/info.c \
../lib/ImageMagick/coders/inline.c \
../lib/ImageMagick/coders/ipl.c \
../lib/ImageMagick/coders/jbig.c \
../lib/ImageMagick/coders/jnx.c \
../lib/ImageMagick/coders/jp2.c \
../lib/ImageMagick/coders/jpeg.c \
../lib/ImageMagick/coders/json.c \
../lib/ImageMagick/coders/label.c \
../lib/ImageMagick/coders/mac.c \
../lib/ImageMagick/coders/magick.c \
../lib/ImageMagick/coders/map.c \
../lib/ImageMagick/coders/mask.c \
../lib/ImageMagick/coders/mat.c \
../lib/ImageMagick/coders/matte.c \
../lib/ImageMagick/coders/meta.c \
../lib/ImageMagick/coders/miff.c \
../lib/ImageMagick/coders/mono.c \
../lib/ImageMagick/coders/mpc.c \
../lib/ImageMagick/coders/mpeg.c \
../lib/ImageMagick/coders/mpr.c \
../lib/ImageMagick/coders/msl.c \
../lib/ImageMagick/coders/mtv.c \
../lib/ImageMagick/coders/mvg.c \
../lib/ImageMagick/coders/null.c \
../lib/ImageMagick/coders/otb.c \
../lib/ImageMagick/coders/palm.c \
../lib/ImageMagick/coders/pango.c \
../lib/ImageMagick/coders/pattern.c \
../lib/ImageMagick/coders/pcd.c \
../lib/ImageMagick/coders/pcl.c \
../lib/ImageMagick/coders/pcx.c \
../lib/ImageMagick/coders/pdb.c \
../lib/ImageMagick/coders/pdf.c \
../lib/ImageMagick/coders/pes.c \
../lib/ImageMagick/coders/pgx.c \
../lib/ImageMagick/coders/pict.c \
../lib/ImageMagick/coders/pix.c \
../lib/ImageMagick/coders/plasma.c \
../lib/ImageMagick/coders/png.c \
../lib/ImageMagick/coders/pnm.c \
../lib/ImageMagick/coders/ps.c \
../lib/ImageMagick/coders/ps2.c \
../lib/ImageMagick/coders/ps3.c \
../lib/ImageMagick/coders/psd.c \
../lib/ImageMagick/coders/pwp.c \
../lib/ImageMagick/coders/raw.c \
../lib/ImageMagick/coders/rgb.c \
../lib/ImageMagick/coders/rgf.c \
../lib/ImageMagick/coders/rla.c \
../lib/ImageMagick/coders/rle.c \
../lib/ImageMagick/coders/scr.c \
../lib/ImageMagick/coders/screenshot.c \
../lib/ImageMagick/coders/sct.c \
../lib/ImageMagick/coders/sfw.c \
../lib/ImageMagick/coders/sgi.c \
../lib/ImageMagick/coders/sixel.c \
../lib/ImageMagick/coders/stegano.c \
../lib/ImageMagick/coders/sun.c \
../lib/ImageMagick/coders/svg.c \
../lib/ImageMagick/coders/tga.c \
../lib/ImageMagick/coders/thumbnail.c \
../lib/ImageMagick/coders/tiff.c \
../lib/ImageMagick/coders/tile.c \
../lib/ImageMagick/coders/tim.c \
../lib/ImageMagick/coders/ttf.c \
../lib/ImageMagick/coders/txt.c \
../lib/ImageMagick/coders/uil.c \
../lib/ImageMagick/coders/url.c \
../lib/ImageMagick/coders/uyvy.c \
../lib/ImageMagick/coders/vicar.c \
../lib/ImageMagick/coders/vid.c \
../lib/ImageMagick/coders/viff.c \
../lib/ImageMagick/coders/vips.c \
../lib/ImageMagick/coders/wbmp.c \
../lib/ImageMagick/coders/webp.c \
../lib/ImageMagick/coders/wmf.c \
../lib/ImageMagick/coders/wpg.c \
../lib/ImageMagick/coders/x.c \
../lib/ImageMagick/coders/xbm.c \
../lib/ImageMagick/coders/xc.c \
../lib/ImageMagick/coders/xcf.c \
../lib/ImageMagick/coders/xpm.c \
../lib/ImageMagick/coders/xps.c \
../lib/ImageMagick/coders/xtrn.c \
../lib/ImageMagick/coders/xwd.c \
../lib/ImageMagick/coders/ycbcr.c \
../lib/ImageMagick/coders/yuv.c 

O_SRCS += \
../lib/ImageMagick/coders/MagickCore_libMagickCore_7_Q16HDRI_la-aai.o \
../lib/ImageMagick/coders/MagickCore_libMagickCore_7_Q16HDRI_la-art.o \
../lib/ImageMagick/coders/MagickCore_libMagickCore_7_Q16HDRI_la-avs.o \
../lib/ImageMagick/coders/MagickCore_libMagickCore_7_Q16HDRI_la-bgr.o \
../lib/ImageMagick/coders/MagickCore_libMagickCore_7_Q16HDRI_la-bmp.o \
../lib/ImageMagick/coders/MagickCore_libMagickCore_7_Q16HDRI_la-braille.o \
../lib/ImageMagick/coders/MagickCore_libMagickCore_7_Q16HDRI_la-cals.o \
../lib/ImageMagick/coders/MagickCore_libMagickCore_7_Q16HDRI_la-caption.o \
../lib/ImageMagick/coders/MagickCore_libMagickCore_7_Q16HDRI_la-cin.o \
../lib/ImageMagick/coders/MagickCore_libMagickCore_7_Q16HDRI_la-cip.o \
../lib/ImageMagick/coders/MagickCore_libMagickCore_7_Q16HDRI_la-clip.o \
../lib/ImageMagick/coders/MagickCore_libMagickCore_7_Q16HDRI_la-cmyk.o \
../lib/ImageMagick/coders/MagickCore_libMagickCore_7_Q16HDRI_la-cube.o \
../lib/ImageMagick/coders/MagickCore_libMagickCore_7_Q16HDRI_la-cut.o \
../lib/ImageMagick/coders/MagickCore_libMagickCore_7_Q16HDRI_la-dcm.o \
../lib/ImageMagick/coders/MagickCore_libMagickCore_7_Q16HDRI_la-dds.o \
../lib/ImageMagick/coders/MagickCore_libMagickCore_7_Q16HDRI_la-debug.o \
../lib/ImageMagick/coders/MagickCore_libMagickCore_7_Q16HDRI_la-dib.o \
../lib/ImageMagick/coders/MagickCore_libMagickCore_7_Q16HDRI_la-djvu.o \
../lib/ImageMagick/coders/MagickCore_libMagickCore_7_Q16HDRI_la-dng.o \
../lib/ImageMagick/coders/MagickCore_libMagickCore_7_Q16HDRI_la-dot.o \
../lib/ImageMagick/coders/MagickCore_libMagickCore_7_Q16HDRI_la-dpx.o \
../lib/ImageMagick/coders/MagickCore_libMagickCore_7_Q16HDRI_la-ept.o \
../lib/ImageMagick/coders/MagickCore_libMagickCore_7_Q16HDRI_la-exr.o \
../lib/ImageMagick/coders/MagickCore_libMagickCore_7_Q16HDRI_la-fax.o \
../lib/ImageMagick/coders/MagickCore_libMagickCore_7_Q16HDRI_la-fits.o \
../lib/ImageMagick/coders/MagickCore_libMagickCore_7_Q16HDRI_la-gif.o \
../lib/ImageMagick/coders/MagickCore_libMagickCore_7_Q16HDRI_la-gradient.o \
../lib/ImageMagick/coders/MagickCore_libMagickCore_7_Q16HDRI_la-gray.o \
../lib/ImageMagick/coders/MagickCore_libMagickCore_7_Q16HDRI_la-hald.o \
../lib/ImageMagick/coders/MagickCore_libMagickCore_7_Q16HDRI_la-hdr.o \
../lib/ImageMagick/coders/MagickCore_libMagickCore_7_Q16HDRI_la-histogram.o \
../lib/ImageMagick/coders/MagickCore_libMagickCore_7_Q16HDRI_la-hrz.o \
../lib/ImageMagick/coders/MagickCore_libMagickCore_7_Q16HDRI_la-html.o \
../lib/ImageMagick/coders/MagickCore_libMagickCore_7_Q16HDRI_la-icon.o \
../lib/ImageMagick/coders/MagickCore_libMagickCore_7_Q16HDRI_la-info.o \
../lib/ImageMagick/coders/MagickCore_libMagickCore_7_Q16HDRI_la-inline.o \
../lib/ImageMagick/coders/MagickCore_libMagickCore_7_Q16HDRI_la-ipl.o \
../lib/ImageMagick/coders/MagickCore_libMagickCore_7_Q16HDRI_la-jbig.o \
../lib/ImageMagick/coders/MagickCore_libMagickCore_7_Q16HDRI_la-jnx.o \
../lib/ImageMagick/coders/MagickCore_libMagickCore_7_Q16HDRI_la-jpeg.o \
../lib/ImageMagick/coders/MagickCore_libMagickCore_7_Q16HDRI_la-json.o \
../lib/ImageMagick/coders/MagickCore_libMagickCore_7_Q16HDRI_la-label.o \
../lib/ImageMagick/coders/MagickCore_libMagickCore_7_Q16HDRI_la-mac.o \
../lib/ImageMagick/coders/MagickCore_libMagickCore_7_Q16HDRI_la-magick.o \
../lib/ImageMagick/coders/MagickCore_libMagickCore_7_Q16HDRI_la-map.o \
../lib/ImageMagick/coders/MagickCore_libMagickCore_7_Q16HDRI_la-mask.o \
../lib/ImageMagick/coders/MagickCore_libMagickCore_7_Q16HDRI_la-mat.o \
../lib/ImageMagick/coders/MagickCore_libMagickCore_7_Q16HDRI_la-matte.o \
../lib/ImageMagick/coders/MagickCore_libMagickCore_7_Q16HDRI_la-meta.o \
../lib/ImageMagick/coders/MagickCore_libMagickCore_7_Q16HDRI_la-miff.o \
../lib/ImageMagick/coders/MagickCore_libMagickCore_7_Q16HDRI_la-mono.o \
../lib/ImageMagick/coders/MagickCore_libMagickCore_7_Q16HDRI_la-mpc.o \
../lib/ImageMagick/coders/MagickCore_libMagickCore_7_Q16HDRI_la-mpeg.o \
../lib/ImageMagick/coders/MagickCore_libMagickCore_7_Q16HDRI_la-mpr.o \
../lib/ImageMagick/coders/MagickCore_libMagickCore_7_Q16HDRI_la-msl.o \
../lib/ImageMagick/coders/MagickCore_libMagickCore_7_Q16HDRI_la-mtv.o \
../lib/ImageMagick/coders/MagickCore_libMagickCore_7_Q16HDRI_la-mvg.o \
../lib/ImageMagick/coders/MagickCore_libMagickCore_7_Q16HDRI_la-null.o \
../lib/ImageMagick/coders/MagickCore_libMagickCore_7_Q16HDRI_la-otb.o \
../lib/ImageMagick/coders/MagickCore_libMagickCore_7_Q16HDRI_la-palm.o \
../lib/ImageMagick/coders/MagickCore_libMagickCore_7_Q16HDRI_la-pango.o \
../lib/ImageMagick/coders/MagickCore_libMagickCore_7_Q16HDRI_la-pattern.o \
../lib/ImageMagick/coders/MagickCore_libMagickCore_7_Q16HDRI_la-pcd.o \
../lib/ImageMagick/coders/MagickCore_libMagickCore_7_Q16HDRI_la-pcl.o \
../lib/ImageMagick/coders/MagickCore_libMagickCore_7_Q16HDRI_la-pcx.o \
../lib/ImageMagick/coders/MagickCore_libMagickCore_7_Q16HDRI_la-pdb.o \
../lib/ImageMagick/coders/MagickCore_libMagickCore_7_Q16HDRI_la-pdf.o \
../lib/ImageMagick/coders/MagickCore_libMagickCore_7_Q16HDRI_la-pes.o \
../lib/ImageMagick/coders/MagickCore_libMagickCore_7_Q16HDRI_la-pgx.o \
../lib/ImageMagick/coders/MagickCore_libMagickCore_7_Q16HDRI_la-pict.o \
../lib/ImageMagick/coders/MagickCore_libMagickCore_7_Q16HDRI_la-pix.o \
../lib/ImageMagick/coders/MagickCore_libMagickCore_7_Q16HDRI_la-plasma.o \
../lib/ImageMagick/coders/MagickCore_libMagickCore_7_Q16HDRI_la-png.o \
../lib/ImageMagick/coders/MagickCore_libMagickCore_7_Q16HDRI_la-pnm.o \
../lib/ImageMagick/coders/MagickCore_libMagickCore_7_Q16HDRI_la-ps.o \
../lib/ImageMagick/coders/MagickCore_libMagickCore_7_Q16HDRI_la-ps2.o \
../lib/ImageMagick/coders/MagickCore_libMagickCore_7_Q16HDRI_la-ps3.o \
../lib/ImageMagick/coders/MagickCore_libMagickCore_7_Q16HDRI_la-psd.o \
../lib/ImageMagick/coders/MagickCore_libMagickCore_7_Q16HDRI_la-pwp.o \
../lib/ImageMagick/coders/MagickCore_libMagickCore_7_Q16HDRI_la-raw.o \
../lib/ImageMagick/coders/MagickCore_libMagickCore_7_Q16HDRI_la-rgb.o \
../lib/ImageMagick/coders/MagickCore_libMagickCore_7_Q16HDRI_la-rgf.o \
../lib/ImageMagick/coders/MagickCore_libMagickCore_7_Q16HDRI_la-rla.o \
../lib/ImageMagick/coders/MagickCore_libMagickCore_7_Q16HDRI_la-rle.o \
../lib/ImageMagick/coders/MagickCore_libMagickCore_7_Q16HDRI_la-scr.o \
../lib/ImageMagick/coders/MagickCore_libMagickCore_7_Q16HDRI_la-screenshot.o \
../lib/ImageMagick/coders/MagickCore_libMagickCore_7_Q16HDRI_la-sct.o \
../lib/ImageMagick/coders/MagickCore_libMagickCore_7_Q16HDRI_la-sfw.o \
../lib/ImageMagick/coders/MagickCore_libMagickCore_7_Q16HDRI_la-sgi.o \
../lib/ImageMagick/coders/MagickCore_libMagickCore_7_Q16HDRI_la-sixel.o \
../lib/ImageMagick/coders/MagickCore_libMagickCore_7_Q16HDRI_la-stegano.o \
../lib/ImageMagick/coders/MagickCore_libMagickCore_7_Q16HDRI_la-sun.o \
../lib/ImageMagick/coders/MagickCore_libMagickCore_7_Q16HDRI_la-svg.o \
../lib/ImageMagick/coders/MagickCore_libMagickCore_7_Q16HDRI_la-tga.o \
../lib/ImageMagick/coders/MagickCore_libMagickCore_7_Q16HDRI_la-thumbnail.o \
../lib/ImageMagick/coders/MagickCore_libMagickCore_7_Q16HDRI_la-tiff.o \
../lib/ImageMagick/coders/MagickCore_libMagickCore_7_Q16HDRI_la-tile.o \
../lib/ImageMagick/coders/MagickCore_libMagickCore_7_Q16HDRI_la-tim.o \
../lib/ImageMagick/coders/MagickCore_libMagickCore_7_Q16HDRI_la-ttf.o \
../lib/ImageMagick/coders/MagickCore_libMagickCore_7_Q16HDRI_la-txt.o \
../lib/ImageMagick/coders/MagickCore_libMagickCore_7_Q16HDRI_la-uil.o \
../lib/ImageMagick/coders/MagickCore_libMagickCore_7_Q16HDRI_la-url.o \
../lib/ImageMagick/coders/MagickCore_libMagickCore_7_Q16HDRI_la-uyvy.o \
../lib/ImageMagick/coders/MagickCore_libMagickCore_7_Q16HDRI_la-vicar.o \
../lib/ImageMagick/coders/MagickCore_libMagickCore_7_Q16HDRI_la-vid.o \
../lib/ImageMagick/coders/MagickCore_libMagickCore_7_Q16HDRI_la-viff.o \
../lib/ImageMagick/coders/MagickCore_libMagickCore_7_Q16HDRI_la-vips.o \
../lib/ImageMagick/coders/MagickCore_libMagickCore_7_Q16HDRI_la-wbmp.o \
../lib/ImageMagick/coders/MagickCore_libMagickCore_7_Q16HDRI_la-wmf.o \
../lib/ImageMagick/coders/MagickCore_libMagickCore_7_Q16HDRI_la-wpg.o \
../lib/ImageMagick/coders/MagickCore_libMagickCore_7_Q16HDRI_la-x.o \
../lib/ImageMagick/coders/MagickCore_libMagickCore_7_Q16HDRI_la-xbm.o \
../lib/ImageMagick/coders/MagickCore_libMagickCore_7_Q16HDRI_la-xc.o \
../lib/ImageMagick/coders/MagickCore_libMagickCore_7_Q16HDRI_la-xcf.o \
../lib/ImageMagick/coders/MagickCore_libMagickCore_7_Q16HDRI_la-xpm.o \
../lib/ImageMagick/coders/MagickCore_libMagickCore_7_Q16HDRI_la-xps.o \
../lib/ImageMagick/coders/MagickCore_libMagickCore_7_Q16HDRI_la-xtrn.o \
../lib/ImageMagick/coders/MagickCore_libMagickCore_7_Q16HDRI_la-xwd.o \
../lib/ImageMagick/coders/MagickCore_libMagickCore_7_Q16HDRI_la-ycbcr.o \
../lib/ImageMagick/coders/MagickCore_libMagickCore_7_Q16HDRI_la-yuv.o 

OBJS += \
./lib/ImageMagick/coders/aai.o \
./lib/ImageMagick/coders/art.o \
./lib/ImageMagick/coders/avs.o \
./lib/ImageMagick/coders/bgr.o \
./lib/ImageMagick/coders/bmp.o \
./lib/ImageMagick/coders/braille.o \
./lib/ImageMagick/coders/cals.o \
./lib/ImageMagick/coders/caption.o \
./lib/ImageMagick/coders/cin.o \
./lib/ImageMagick/coders/cip.o \
./lib/ImageMagick/coders/clip.o \
./lib/ImageMagick/coders/clipboard.o \
./lib/ImageMagick/coders/cmyk.o \
./lib/ImageMagick/coders/cube.o \
./lib/ImageMagick/coders/cut.o \
./lib/ImageMagick/coders/dcm.o \
./lib/ImageMagick/coders/dds.o \
./lib/ImageMagick/coders/debug.o \
./lib/ImageMagick/coders/dib.o \
./lib/ImageMagick/coders/djvu.o \
./lib/ImageMagick/coders/dng.o \
./lib/ImageMagick/coders/dot.o \
./lib/ImageMagick/coders/dps.o \
./lib/ImageMagick/coders/dpx.o \
./lib/ImageMagick/coders/emf.o \
./lib/ImageMagick/coders/ept.o \
./lib/ImageMagick/coders/exr.o \
./lib/ImageMagick/coders/fax.o \
./lib/ImageMagick/coders/fits.o \
./lib/ImageMagick/coders/flif.o \
./lib/ImageMagick/coders/fpx.o \
./lib/ImageMagick/coders/gif.o \
./lib/ImageMagick/coders/gradient.o \
./lib/ImageMagick/coders/gray.o \
./lib/ImageMagick/coders/hald.o \
./lib/ImageMagick/coders/hdr.o \
./lib/ImageMagick/coders/heic.o \
./lib/ImageMagick/coders/histogram.o \
./lib/ImageMagick/coders/hrz.o \
./lib/ImageMagick/coders/html.o \
./lib/ImageMagick/coders/icon.o \
./lib/ImageMagick/coders/info.o \
./lib/ImageMagick/coders/inline.o \
./lib/ImageMagick/coders/ipl.o \
./lib/ImageMagick/coders/jbig.o \
./lib/ImageMagick/coders/jnx.o \
./lib/ImageMagick/coders/jp2.o \
./lib/ImageMagick/coders/jpeg.o \
./lib/ImageMagick/coders/json.o \
./lib/ImageMagick/coders/label.o \
./lib/ImageMagick/coders/mac.o \
./lib/ImageMagick/coders/magick.o \
./lib/ImageMagick/coders/map.o \
./lib/ImageMagick/coders/mask.o \
./lib/ImageMagick/coders/mat.o \
./lib/ImageMagick/coders/matte.o \
./lib/ImageMagick/coders/meta.o \
./lib/ImageMagick/coders/miff.o \
./lib/ImageMagick/coders/mono.o \
./lib/ImageMagick/coders/mpc.o \
./lib/ImageMagick/coders/mpeg.o \
./lib/ImageMagick/coders/mpr.o \
./lib/ImageMagick/coders/msl.o \
./lib/ImageMagick/coders/mtv.o \
./lib/ImageMagick/coders/mvg.o \
./lib/ImageMagick/coders/null.o \
./lib/ImageMagick/coders/otb.o \
./lib/ImageMagick/coders/palm.o \
./lib/ImageMagick/coders/pango.o \
./lib/ImageMagick/coders/pattern.o \
./lib/ImageMagick/coders/pcd.o \
./lib/ImageMagick/coders/pcl.o \
./lib/ImageMagick/coders/pcx.o \
./lib/ImageMagick/coders/pdb.o \
./lib/ImageMagick/coders/pdf.o \
./lib/ImageMagick/coders/pes.o \
./lib/ImageMagick/coders/pgx.o \
./lib/ImageMagick/coders/pict.o \
./lib/ImageMagick/coders/pix.o \
./lib/ImageMagick/coders/plasma.o \
./lib/ImageMagick/coders/png.o \
./lib/ImageMagick/coders/pnm.o \
./lib/ImageMagick/coders/ps.o \
./lib/ImageMagick/coders/ps2.o \
./lib/ImageMagick/coders/ps3.o \
./lib/ImageMagick/coders/psd.o \
./lib/ImageMagick/coders/pwp.o \
./lib/ImageMagick/coders/raw.o \
./lib/ImageMagick/coders/rgb.o \
./lib/ImageMagick/coders/rgf.o \
./lib/ImageMagick/coders/rla.o \
./lib/ImageMagick/coders/rle.o \
./lib/ImageMagick/coders/scr.o \
./lib/ImageMagick/coders/screenshot.o \
./lib/ImageMagick/coders/sct.o \
./lib/ImageMagick/coders/sfw.o \
./lib/ImageMagick/coders/sgi.o \
./lib/ImageMagick/coders/sixel.o \
./lib/ImageMagick/coders/stegano.o \
./lib/ImageMagick/coders/sun.o \
./lib/ImageMagick/coders/svg.o \
./lib/ImageMagick/coders/tga.o \
./lib/ImageMagick/coders/thumbnail.o \
./lib/ImageMagick/coders/tiff.o \
./lib/ImageMagick/coders/tile.o \
./lib/ImageMagick/coders/tim.o \
./lib/ImageMagick/coders/ttf.o \
./lib/ImageMagick/coders/txt.o \
./lib/ImageMagick/coders/uil.o \
./lib/ImageMagick/coders/url.o \
./lib/ImageMagick/coders/uyvy.o \
./lib/ImageMagick/coders/vicar.o \
./lib/ImageMagick/coders/vid.o \
./lib/ImageMagick/coders/viff.o \
./lib/ImageMagick/coders/vips.o \
./lib/ImageMagick/coders/wbmp.o \
./lib/ImageMagick/coders/webp.o \
./lib/ImageMagick/coders/wmf.o \
./lib/ImageMagick/coders/wpg.o \
./lib/ImageMagick/coders/x.o \
./lib/ImageMagick/coders/xbm.o \
./lib/ImageMagick/coders/xc.o \
./lib/ImageMagick/coders/xcf.o \
./lib/ImageMagick/coders/xpm.o \
./lib/ImageMagick/coders/xps.o \
./lib/ImageMagick/coders/xtrn.o \
./lib/ImageMagick/coders/xwd.o \
./lib/ImageMagick/coders/ycbcr.o \
./lib/ImageMagick/coders/yuv.o 

C_DEPS += \
./lib/ImageMagick/coders/aai.d \
./lib/ImageMagick/coders/art.d \
./lib/ImageMagick/coders/avs.d \
./lib/ImageMagick/coders/bgr.d \
./lib/ImageMagick/coders/bmp.d \
./lib/ImageMagick/coders/braille.d \
./lib/ImageMagick/coders/cals.d \
./lib/ImageMagick/coders/caption.d \
./lib/ImageMagick/coders/cin.d \
./lib/ImageMagick/coders/cip.d \
./lib/ImageMagick/coders/clip.d \
./lib/ImageMagick/coders/clipboard.d \
./lib/ImageMagick/coders/cmyk.d \
./lib/ImageMagick/coders/cube.d \
./lib/ImageMagick/coders/cut.d \
./lib/ImageMagick/coders/dcm.d \
./lib/ImageMagick/coders/dds.d \
./lib/ImageMagick/coders/debug.d \
./lib/ImageMagick/coders/dib.d \
./lib/ImageMagick/coders/djvu.d \
./lib/ImageMagick/coders/dng.d \
./lib/ImageMagick/coders/dot.d \
./lib/ImageMagick/coders/dps.d \
./lib/ImageMagick/coders/dpx.d \
./lib/ImageMagick/coders/emf.d \
./lib/ImageMagick/coders/ept.d \
./lib/ImageMagick/coders/exr.d \
./lib/ImageMagick/coders/fax.d \
./lib/ImageMagick/coders/fits.d \
./lib/ImageMagick/coders/flif.d \
./lib/ImageMagick/coders/fpx.d \
./lib/ImageMagick/coders/gif.d \
./lib/ImageMagick/coders/gradient.d \
./lib/ImageMagick/coders/gray.d \
./lib/ImageMagick/coders/hald.d \
./lib/ImageMagick/coders/hdr.d \
./lib/ImageMagick/coders/heic.d \
./lib/ImageMagick/coders/histogram.d \
./lib/ImageMagick/coders/hrz.d \
./lib/ImageMagick/coders/html.d \
./lib/ImageMagick/coders/icon.d \
./lib/ImageMagick/coders/info.d \
./lib/ImageMagick/coders/inline.d \
./lib/ImageMagick/coders/ipl.d \
./lib/ImageMagick/coders/jbig.d \
./lib/ImageMagick/coders/jnx.d \
./lib/ImageMagick/coders/jp2.d \
./lib/ImageMagick/coders/jpeg.d \
./lib/ImageMagick/coders/json.d \
./lib/ImageMagick/coders/label.d \
./lib/ImageMagick/coders/mac.d \
./lib/ImageMagick/coders/magick.d \
./lib/ImageMagick/coders/map.d \
./lib/ImageMagick/coders/mask.d \
./lib/ImageMagick/coders/mat.d \
./lib/ImageMagick/coders/matte.d \
./lib/ImageMagick/coders/meta.d \
./lib/ImageMagick/coders/miff.d \
./lib/ImageMagick/coders/mono.d \
./lib/ImageMagick/coders/mpc.d \
./lib/ImageMagick/coders/mpeg.d \
./lib/ImageMagick/coders/mpr.d \
./lib/ImageMagick/coders/msl.d \
./lib/ImageMagick/coders/mtv.d \
./lib/ImageMagick/coders/mvg.d \
./lib/ImageMagick/coders/null.d \
./lib/ImageMagick/coders/otb.d \
./lib/ImageMagick/coders/palm.d \
./lib/ImageMagick/coders/pango.d \
./lib/ImageMagick/coders/pattern.d \
./lib/ImageMagick/coders/pcd.d \
./lib/ImageMagick/coders/pcl.d \
./lib/ImageMagick/coders/pcx.d \
./lib/ImageMagick/coders/pdb.d \
./lib/ImageMagick/coders/pdf.d \
./lib/ImageMagick/coders/pes.d \
./lib/ImageMagick/coders/pgx.d \
./lib/ImageMagick/coders/pict.d \
./lib/ImageMagick/coders/pix.d \
./lib/ImageMagick/coders/plasma.d \
./lib/ImageMagick/coders/png.d \
./lib/ImageMagick/coders/pnm.d \
./lib/ImageMagick/coders/ps.d \
./lib/ImageMagick/coders/ps2.d \
./lib/ImageMagick/coders/ps3.d \
./lib/ImageMagick/coders/psd.d \
./lib/ImageMagick/coders/pwp.d \
./lib/ImageMagick/coders/raw.d \
./lib/ImageMagick/coders/rgb.d \
./lib/ImageMagick/coders/rgf.d \
./lib/ImageMagick/coders/rla.d \
./lib/ImageMagick/coders/rle.d \
./lib/ImageMagick/coders/scr.d \
./lib/ImageMagick/coders/screenshot.d \
./lib/ImageMagick/coders/sct.d \
./lib/ImageMagick/coders/sfw.d \
./lib/ImageMagick/coders/sgi.d \
./lib/ImageMagick/coders/sixel.d \
./lib/ImageMagick/coders/stegano.d \
./lib/ImageMagick/coders/sun.d \
./lib/ImageMagick/coders/svg.d \
./lib/ImageMagick/coders/tga.d \
./lib/ImageMagick/coders/thumbnail.d \
./lib/ImageMagick/coders/tiff.d \
./lib/ImageMagick/coders/tile.d \
./lib/ImageMagick/coders/tim.d \
./lib/ImageMagick/coders/ttf.d \
./lib/ImageMagick/coders/txt.d \
./lib/ImageMagick/coders/uil.d \
./lib/ImageMagick/coders/url.d \
./lib/ImageMagick/coders/uyvy.d \
./lib/ImageMagick/coders/vicar.d \
./lib/ImageMagick/coders/vid.d \
./lib/ImageMagick/coders/viff.d \
./lib/ImageMagick/coders/vips.d \
./lib/ImageMagick/coders/wbmp.d \
./lib/ImageMagick/coders/webp.d \
./lib/ImageMagick/coders/wmf.d \
./lib/ImageMagick/coders/wpg.d \
./lib/ImageMagick/coders/x.d \
./lib/ImageMagick/coders/xbm.d \
./lib/ImageMagick/coders/xc.d \
./lib/ImageMagick/coders/xcf.d \
./lib/ImageMagick/coders/xpm.d \
./lib/ImageMagick/coders/xps.d \
./lib/ImageMagick/coders/xtrn.d \
./lib/ImageMagick/coders/xwd.d \
./lib/ImageMagick/coders/ycbcr.d \
./lib/ImageMagick/coders/yuv.d 


# Each subdirectory must supply rules for building sources it contributes
lib/ImageMagick/coders/%.o: ../lib/ImageMagick/coders/%.c
	@echo 'Building file: $<'
	@echo 'Invoking: GCC C Compiler'
	gcc -O0 -g3 -Wall -c -fmessage-length=0 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@)" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '


