################################################################################
# Automatically-generated file. Do not edit!
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
O_SRCS += \
../lib/ImageMagick/coders/.libs/MagickCore_libMagickCore_7_Q16HDRI_la-aai.o \
../lib/ImageMagick/coders/.libs/MagickCore_libMagickCore_7_Q16HDRI_la-art.o \
../lib/ImageMagick/coders/.libs/MagickCore_libMagickCore_7_Q16HDRI_la-avs.o \
../lib/ImageMagick/coders/.libs/MagickCore_libMagickCore_7_Q16HDRI_la-bgr.o \
../lib/ImageMagick/coders/.libs/MagickCore_libMagickCore_7_Q16HDRI_la-bmp.o \
../lib/ImageMagick/coders/.libs/MagickCore_libMagickCore_7_Q16HDRI_la-braille.o \
../lib/ImageMagick/coders/.libs/MagickCore_libMagickCore_7_Q16HDRI_la-cals.o \
../lib/ImageMagick/coders/.libs/MagickCore_libMagickCore_7_Q16HDRI_la-caption.o \
../lib/ImageMagick/coders/.libs/MagickCore_libMagickCore_7_Q16HDRI_la-cin.o \
../lib/ImageMagick/coders/.libs/MagickCore_libMagickCore_7_Q16HDRI_la-cip.o \
../lib/ImageMagick/coders/.libs/MagickCore_libMagickCore_7_Q16HDRI_la-clip.o \
../lib/ImageMagick/coders/.libs/MagickCore_libMagickCore_7_Q16HDRI_la-cmyk.o \
../lib/ImageMagick/coders/.libs/MagickCore_libMagickCore_7_Q16HDRI_la-cube.o \
../lib/ImageMagick/coders/.libs/MagickCore_libMagickCore_7_Q16HDRI_la-cut.o \
../lib/ImageMagick/coders/.libs/MagickCore_libMagickCore_7_Q16HDRI_la-dcm.o \
../lib/ImageMagick/coders/.libs/MagickCore_libMagickCore_7_Q16HDRI_la-dds.o \
../lib/ImageMagick/coders/.libs/MagickCore_libMagickCore_7_Q16HDRI_la-debug.o \
../lib/ImageMagick/coders/.libs/MagickCore_libMagickCore_7_Q16HDRI_la-dib.o \
../lib/ImageMagick/coders/.libs/MagickCore_libMagickCore_7_Q16HDRI_la-djvu.o \
../lib/ImageMagick/coders/.libs/MagickCore_libMagickCore_7_Q16HDRI_la-dng.o \
../lib/ImageMagick/coders/.libs/MagickCore_libMagickCore_7_Q16HDRI_la-dot.o \
../lib/ImageMagick/coders/.libs/MagickCore_libMagickCore_7_Q16HDRI_la-dpx.o \
../lib/ImageMagick/coders/.libs/MagickCore_libMagickCore_7_Q16HDRI_la-ept.o \
../lib/ImageMagick/coders/.libs/MagickCore_libMagickCore_7_Q16HDRI_la-exr.o \
../lib/ImageMagick/coders/.libs/MagickCore_libMagickCore_7_Q16HDRI_la-fax.o \
../lib/ImageMagick/coders/.libs/MagickCore_libMagickCore_7_Q16HDRI_la-fits.o \
../lib/ImageMagick/coders/.libs/MagickCore_libMagickCore_7_Q16HDRI_la-gif.o \
../lib/ImageMagick/coders/.libs/MagickCore_libMagickCore_7_Q16HDRI_la-gradient.o \
../lib/ImageMagick/coders/.libs/MagickCore_libMagickCore_7_Q16HDRI_la-gray.o \
../lib/ImageMagick/coders/.libs/MagickCore_libMagickCore_7_Q16HDRI_la-hald.o \
../lib/ImageMagick/coders/.libs/MagickCore_libMagickCore_7_Q16HDRI_la-hdr.o \
../lib/ImageMagick/coders/.libs/MagickCore_libMagickCore_7_Q16HDRI_la-histogram.o \
../lib/ImageMagick/coders/.libs/MagickCore_libMagickCore_7_Q16HDRI_la-hrz.o \
../lib/ImageMagick/coders/.libs/MagickCore_libMagickCore_7_Q16HDRI_la-html.o \
../lib/ImageMagick/coders/.libs/MagickCore_libMagickCore_7_Q16HDRI_la-icon.o \
../lib/ImageMagick/coders/.libs/MagickCore_libMagickCore_7_Q16HDRI_la-info.o \
../lib/ImageMagick/coders/.libs/MagickCore_libMagickCore_7_Q16HDRI_la-inline.o \
../lib/ImageMagick/coders/.libs/MagickCore_libMagickCore_7_Q16HDRI_la-ipl.o \
../lib/ImageMagick/coders/.libs/MagickCore_libMagickCore_7_Q16HDRI_la-jbig.o \
../lib/ImageMagick/coders/.libs/MagickCore_libMagickCore_7_Q16HDRI_la-jnx.o \
../lib/ImageMagick/coders/.libs/MagickCore_libMagickCore_7_Q16HDRI_la-jpeg.o \
../lib/ImageMagick/coders/.libs/MagickCore_libMagickCore_7_Q16HDRI_la-json.o \
../lib/ImageMagick/coders/.libs/MagickCore_libMagickCore_7_Q16HDRI_la-label.o \
../lib/ImageMagick/coders/.libs/MagickCore_libMagickCore_7_Q16HDRI_la-mac.o \
../lib/ImageMagick/coders/.libs/MagickCore_libMagickCore_7_Q16HDRI_la-magick.o \
../lib/ImageMagick/coders/.libs/MagickCore_libMagickCore_7_Q16HDRI_la-map.o \
../lib/ImageMagick/coders/.libs/MagickCore_libMagickCore_7_Q16HDRI_la-mask.o \
../lib/ImageMagick/coders/.libs/MagickCore_libMagickCore_7_Q16HDRI_la-mat.o \
../lib/ImageMagick/coders/.libs/MagickCore_libMagickCore_7_Q16HDRI_la-matte.o \
../lib/ImageMagick/coders/.libs/MagickCore_libMagickCore_7_Q16HDRI_la-meta.o \
../lib/ImageMagick/coders/.libs/MagickCore_libMagickCore_7_Q16HDRI_la-miff.o \
../lib/ImageMagick/coders/.libs/MagickCore_libMagickCore_7_Q16HDRI_la-mono.o \
../lib/ImageMagick/coders/.libs/MagickCore_libMagickCore_7_Q16HDRI_la-mpc.o \
../lib/ImageMagick/coders/.libs/MagickCore_libMagickCore_7_Q16HDRI_la-mpeg.o \
../lib/ImageMagick/coders/.libs/MagickCore_libMagickCore_7_Q16HDRI_la-mpr.o \
../lib/ImageMagick/coders/.libs/MagickCore_libMagickCore_7_Q16HDRI_la-msl.o \
../lib/ImageMagick/coders/.libs/MagickCore_libMagickCore_7_Q16HDRI_la-mtv.o \
../lib/ImageMagick/coders/.libs/MagickCore_libMagickCore_7_Q16HDRI_la-mvg.o \
../lib/ImageMagick/coders/.libs/MagickCore_libMagickCore_7_Q16HDRI_la-null.o \
../lib/ImageMagick/coders/.libs/MagickCore_libMagickCore_7_Q16HDRI_la-otb.o \
../lib/ImageMagick/coders/.libs/MagickCore_libMagickCore_7_Q16HDRI_la-palm.o \
../lib/ImageMagick/coders/.libs/MagickCore_libMagickCore_7_Q16HDRI_la-pango.o \
../lib/ImageMagick/coders/.libs/MagickCore_libMagickCore_7_Q16HDRI_la-pattern.o \
../lib/ImageMagick/coders/.libs/MagickCore_libMagickCore_7_Q16HDRI_la-pcd.o \
../lib/ImageMagick/coders/.libs/MagickCore_libMagickCore_7_Q16HDRI_la-pcl.o \
../lib/ImageMagick/coders/.libs/MagickCore_libMagickCore_7_Q16HDRI_la-pcx.o \
../lib/ImageMagick/coders/.libs/MagickCore_libMagickCore_7_Q16HDRI_la-pdb.o \
../lib/ImageMagick/coders/.libs/MagickCore_libMagickCore_7_Q16HDRI_la-pdf.o \
../lib/ImageMagick/coders/.libs/MagickCore_libMagickCore_7_Q16HDRI_la-pes.o \
../lib/ImageMagick/coders/.libs/MagickCore_libMagickCore_7_Q16HDRI_la-pgx.o \
../lib/ImageMagick/coders/.libs/MagickCore_libMagickCore_7_Q16HDRI_la-pict.o \
../lib/ImageMagick/coders/.libs/MagickCore_libMagickCore_7_Q16HDRI_la-pix.o \
../lib/ImageMagick/coders/.libs/MagickCore_libMagickCore_7_Q16HDRI_la-plasma.o \
../lib/ImageMagick/coders/.libs/MagickCore_libMagickCore_7_Q16HDRI_la-png.o \
../lib/ImageMagick/coders/.libs/MagickCore_libMagickCore_7_Q16HDRI_la-pnm.o \
../lib/ImageMagick/coders/.libs/MagickCore_libMagickCore_7_Q16HDRI_la-ps.o \
../lib/ImageMagick/coders/.libs/MagickCore_libMagickCore_7_Q16HDRI_la-ps2.o \
../lib/ImageMagick/coders/.libs/MagickCore_libMagickCore_7_Q16HDRI_la-ps3.o \
../lib/ImageMagick/coders/.libs/MagickCore_libMagickCore_7_Q16HDRI_la-psd.o \
../lib/ImageMagick/coders/.libs/MagickCore_libMagickCore_7_Q16HDRI_la-pwp.o \
../lib/ImageMagick/coders/.libs/MagickCore_libMagickCore_7_Q16HDRI_la-raw.o \
../lib/ImageMagick/coders/.libs/MagickCore_libMagickCore_7_Q16HDRI_la-rgb.o \
../lib/ImageMagick/coders/.libs/MagickCore_libMagickCore_7_Q16HDRI_la-rgf.o \
../lib/ImageMagick/coders/.libs/MagickCore_libMagickCore_7_Q16HDRI_la-rla.o \
../lib/ImageMagick/coders/.libs/MagickCore_libMagickCore_7_Q16HDRI_la-rle.o \
../lib/ImageMagick/coders/.libs/MagickCore_libMagickCore_7_Q16HDRI_la-scr.o \
../lib/ImageMagick/coders/.libs/MagickCore_libMagickCore_7_Q16HDRI_la-screenshot.o \
../lib/ImageMagick/coders/.libs/MagickCore_libMagickCore_7_Q16HDRI_la-sct.o \
../lib/ImageMagick/coders/.libs/MagickCore_libMagickCore_7_Q16HDRI_la-sfw.o \
../lib/ImageMagick/coders/.libs/MagickCore_libMagickCore_7_Q16HDRI_la-sgi.o \
../lib/ImageMagick/coders/.libs/MagickCore_libMagickCore_7_Q16HDRI_la-sixel.o \
../lib/ImageMagick/coders/.libs/MagickCore_libMagickCore_7_Q16HDRI_la-stegano.o \
../lib/ImageMagick/coders/.libs/MagickCore_libMagickCore_7_Q16HDRI_la-sun.o \
../lib/ImageMagick/coders/.libs/MagickCore_libMagickCore_7_Q16HDRI_la-svg.o \
../lib/ImageMagick/coders/.libs/MagickCore_libMagickCore_7_Q16HDRI_la-tga.o \
../lib/ImageMagick/coders/.libs/MagickCore_libMagickCore_7_Q16HDRI_la-thumbnail.o \
../lib/ImageMagick/coders/.libs/MagickCore_libMagickCore_7_Q16HDRI_la-tiff.o \
../lib/ImageMagick/coders/.libs/MagickCore_libMagickCore_7_Q16HDRI_la-tile.o \
../lib/ImageMagick/coders/.libs/MagickCore_libMagickCore_7_Q16HDRI_la-tim.o \
../lib/ImageMagick/coders/.libs/MagickCore_libMagickCore_7_Q16HDRI_la-ttf.o \
../lib/ImageMagick/coders/.libs/MagickCore_libMagickCore_7_Q16HDRI_la-txt.o \
../lib/ImageMagick/coders/.libs/MagickCore_libMagickCore_7_Q16HDRI_la-uil.o \
../lib/ImageMagick/coders/.libs/MagickCore_libMagickCore_7_Q16HDRI_la-url.o \
../lib/ImageMagick/coders/.libs/MagickCore_libMagickCore_7_Q16HDRI_la-uyvy.o \
../lib/ImageMagick/coders/.libs/MagickCore_libMagickCore_7_Q16HDRI_la-vicar.o \
../lib/ImageMagick/coders/.libs/MagickCore_libMagickCore_7_Q16HDRI_la-vid.o \
../lib/ImageMagick/coders/.libs/MagickCore_libMagickCore_7_Q16HDRI_la-viff.o \
../lib/ImageMagick/coders/.libs/MagickCore_libMagickCore_7_Q16HDRI_la-vips.o \
../lib/ImageMagick/coders/.libs/MagickCore_libMagickCore_7_Q16HDRI_la-wbmp.o \
../lib/ImageMagick/coders/.libs/MagickCore_libMagickCore_7_Q16HDRI_la-wmf.o \
../lib/ImageMagick/coders/.libs/MagickCore_libMagickCore_7_Q16HDRI_la-wpg.o \
../lib/ImageMagick/coders/.libs/MagickCore_libMagickCore_7_Q16HDRI_la-x.o \
../lib/ImageMagick/coders/.libs/MagickCore_libMagickCore_7_Q16HDRI_la-xbm.o \
../lib/ImageMagick/coders/.libs/MagickCore_libMagickCore_7_Q16HDRI_la-xc.o \
../lib/ImageMagick/coders/.libs/MagickCore_libMagickCore_7_Q16HDRI_la-xcf.o \
../lib/ImageMagick/coders/.libs/MagickCore_libMagickCore_7_Q16HDRI_la-xpm.o \
../lib/ImageMagick/coders/.libs/MagickCore_libMagickCore_7_Q16HDRI_la-xps.o \
../lib/ImageMagick/coders/.libs/MagickCore_libMagickCore_7_Q16HDRI_la-xtrn.o \
../lib/ImageMagick/coders/.libs/MagickCore_libMagickCore_7_Q16HDRI_la-xwd.o \
../lib/ImageMagick/coders/.libs/MagickCore_libMagickCore_7_Q16HDRI_la-ycbcr.o \
../lib/ImageMagick/coders/.libs/MagickCore_libMagickCore_7_Q16HDRI_la-yuv.o 


# Each subdirectory must supply rules for building sources it contributes

