################################################################################
# Automatically-generated file. Do not edit!
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
ASM_SRCS += \
../lib/FFmpeg/libavcodec/x86/aacencdsp.asm \
../lib/FFmpeg/libavcodec/x86/aacpsdsp.asm \
../lib/FFmpeg/libavcodec/x86/ac3dsp.asm \
../lib/FFmpeg/libavcodec/x86/ac3dsp_downmix.asm \
../lib/FFmpeg/libavcodec/x86/alacdsp.asm \
../lib/FFmpeg/libavcodec/x86/audiodsp.asm \
../lib/FFmpeg/libavcodec/x86/blockdsp.asm \
../lib/FFmpeg/libavcodec/x86/bswapdsp.asm \
../lib/FFmpeg/libavcodec/x86/cavsidct.asm \
../lib/FFmpeg/libavcodec/x86/dcadsp.asm \
../lib/FFmpeg/libavcodec/x86/dct32.asm \
../lib/FFmpeg/libavcodec/x86/dirac_dwt.asm \
../lib/FFmpeg/libavcodec/x86/diracdsp.asm \
../lib/FFmpeg/libavcodec/x86/dnxhdenc.asm \
../lib/FFmpeg/libavcodec/x86/exrdsp.asm \
../lib/FFmpeg/libavcodec/x86/fft.asm \
../lib/FFmpeg/libavcodec/x86/flac_dsp_gpl.asm \
../lib/FFmpeg/libavcodec/x86/flacdsp.asm \
../lib/FFmpeg/libavcodec/x86/fmtconvert.asm \
../lib/FFmpeg/libavcodec/x86/fpel.asm \
../lib/FFmpeg/libavcodec/x86/g722dsp.asm \
../lib/FFmpeg/libavcodec/x86/h263_loopfilter.asm \
../lib/FFmpeg/libavcodec/x86/h264_chromamc.asm \
../lib/FFmpeg/libavcodec/x86/h264_chromamc_10bit.asm \
../lib/FFmpeg/libavcodec/x86/h264_deblock.asm \
../lib/FFmpeg/libavcodec/x86/h264_deblock_10bit.asm \
../lib/FFmpeg/libavcodec/x86/h264_idct.asm \
../lib/FFmpeg/libavcodec/x86/h264_idct_10bit.asm \
../lib/FFmpeg/libavcodec/x86/h264_intrapred.asm \
../lib/FFmpeg/libavcodec/x86/h264_intrapred_10bit.asm \
../lib/FFmpeg/libavcodec/x86/h264_qpel_10bit.asm \
../lib/FFmpeg/libavcodec/x86/h264_qpel_8bit.asm \
../lib/FFmpeg/libavcodec/x86/h264_weight.asm \
../lib/FFmpeg/libavcodec/x86/h264_weight_10bit.asm \
../lib/FFmpeg/libavcodec/x86/hevc_add_res.asm \
../lib/FFmpeg/libavcodec/x86/hevc_deblock.asm \
../lib/FFmpeg/libavcodec/x86/hevc_idct.asm \
../lib/FFmpeg/libavcodec/x86/hevc_mc.asm \
../lib/FFmpeg/libavcodec/x86/hevc_sao.asm \
../lib/FFmpeg/libavcodec/x86/hevc_sao_10bit.asm \
../lib/FFmpeg/libavcodec/x86/hpeldsp.asm \
../lib/FFmpeg/libavcodec/x86/hpeldsp_vp3.asm \
../lib/FFmpeg/libavcodec/x86/huffyuvdsp.asm \
../lib/FFmpeg/libavcodec/x86/huffyuvdsp_template.asm \
../lib/FFmpeg/libavcodec/x86/huffyuvencdsp.asm \
../lib/FFmpeg/libavcodec/x86/idctdsp.asm \
../lib/FFmpeg/libavcodec/x86/imdct36.asm \
../lib/FFmpeg/libavcodec/x86/jpeg2000dsp.asm \
../lib/FFmpeg/libavcodec/x86/lossless_audiodsp.asm \
../lib/FFmpeg/libavcodec/x86/lossless_videodsp.asm \
../lib/FFmpeg/libavcodec/x86/lossless_videoencdsp.asm \
../lib/FFmpeg/libavcodec/x86/mdct15.asm \
../lib/FFmpeg/libavcodec/x86/me_cmp.asm \
../lib/FFmpeg/libavcodec/x86/mlpdsp.asm \
../lib/FFmpeg/libavcodec/x86/mpegvideoencdsp.asm \
../lib/FFmpeg/libavcodec/x86/opus_pvq_search.asm \
../lib/FFmpeg/libavcodec/x86/pixblockdsp.asm \
../lib/FFmpeg/libavcodec/x86/pngdsp.asm \
../lib/FFmpeg/libavcodec/x86/proresdsp.asm \
../lib/FFmpeg/libavcodec/x86/qpel.asm \
../lib/FFmpeg/libavcodec/x86/qpeldsp.asm \
../lib/FFmpeg/libavcodec/x86/rv34dsp.asm \
../lib/FFmpeg/libavcodec/x86/rv40dsp.asm \
../lib/FFmpeg/libavcodec/x86/sbcdsp.asm \
../lib/FFmpeg/libavcodec/x86/sbrdsp.asm \
../lib/FFmpeg/libavcodec/x86/simple_idct.asm \
../lib/FFmpeg/libavcodec/x86/simple_idct10.asm \
../lib/FFmpeg/libavcodec/x86/simple_idct10_template.asm \
../lib/FFmpeg/libavcodec/x86/svq1enc.asm \
../lib/FFmpeg/libavcodec/x86/synth_filter.asm \
../lib/FFmpeg/libavcodec/x86/takdsp.asm \
../lib/FFmpeg/libavcodec/x86/ttadsp.asm \
../lib/FFmpeg/libavcodec/x86/ttaencdsp.asm \
../lib/FFmpeg/libavcodec/x86/utvideodsp.asm \
../lib/FFmpeg/libavcodec/x86/v210.asm \
../lib/FFmpeg/libavcodec/x86/v210enc.asm \
../lib/FFmpeg/libavcodec/x86/vc1dsp_loopfilter.asm \
../lib/FFmpeg/libavcodec/x86/vc1dsp_mc.asm \
../lib/FFmpeg/libavcodec/x86/videodsp.asm \
../lib/FFmpeg/libavcodec/x86/vorbisdsp.asm \
../lib/FFmpeg/libavcodec/x86/vp3dsp.asm \
../lib/FFmpeg/libavcodec/x86/vp6dsp.asm \
../lib/FFmpeg/libavcodec/x86/vp8dsp.asm \
../lib/FFmpeg/libavcodec/x86/vp8dsp_loopfilter.asm \
../lib/FFmpeg/libavcodec/x86/vp9intrapred.asm \
../lib/FFmpeg/libavcodec/x86/vp9intrapred_16bpp.asm \
../lib/FFmpeg/libavcodec/x86/vp9itxfm.asm \
../lib/FFmpeg/libavcodec/x86/vp9itxfm_16bpp.asm \
../lib/FFmpeg/libavcodec/x86/vp9itxfm_template.asm \
../lib/FFmpeg/libavcodec/x86/vp9lpf.asm \
../lib/FFmpeg/libavcodec/x86/vp9lpf_16bpp.asm \
../lib/FFmpeg/libavcodec/x86/vp9mc.asm \
../lib/FFmpeg/libavcodec/x86/vp9mc_16bpp.asm \
../lib/FFmpeg/libavcodec/x86/xvididct.asm 

C_SRCS += \
../lib/FFmpeg/libavcodec/x86/aacencdsp_init.c \
../lib/FFmpeg/libavcodec/x86/aacpsdsp_init.c \
../lib/FFmpeg/libavcodec/x86/ac3dsp_init.c \
../lib/FFmpeg/libavcodec/x86/alacdsp_init.c \
../lib/FFmpeg/libavcodec/x86/audiodsp_init.c \
../lib/FFmpeg/libavcodec/x86/blockdsp_init.c \
../lib/FFmpeg/libavcodec/x86/bswapdsp_init.c \
../lib/FFmpeg/libavcodec/x86/cavsdsp.c \
../lib/FFmpeg/libavcodec/x86/constants.c \
../lib/FFmpeg/libavcodec/x86/dcadsp_init.c \
../lib/FFmpeg/libavcodec/x86/dct_init.c \
../lib/FFmpeg/libavcodec/x86/dirac_dwt_init.c \
../lib/FFmpeg/libavcodec/x86/diracdsp_init.c \
../lib/FFmpeg/libavcodec/x86/dnxhdenc_init.c \
../lib/FFmpeg/libavcodec/x86/exrdsp_init.c \
../lib/FFmpeg/libavcodec/x86/fdct.c \
../lib/FFmpeg/libavcodec/x86/fdctdsp_init.c \
../lib/FFmpeg/libavcodec/x86/fft_init.c \
../lib/FFmpeg/libavcodec/x86/flacdsp_init.c \
../lib/FFmpeg/libavcodec/x86/fmtconvert_init.c \
../lib/FFmpeg/libavcodec/x86/g722dsp_init.c \
../lib/FFmpeg/libavcodec/x86/h263dsp_init.c \
../lib/FFmpeg/libavcodec/x86/h264_cabac.c \
../lib/FFmpeg/libavcodec/x86/h264_intrapred_init.c \
../lib/FFmpeg/libavcodec/x86/h264_qpel.c \
../lib/FFmpeg/libavcodec/x86/h264chroma_init.c \
../lib/FFmpeg/libavcodec/x86/h264dsp_init.c \
../lib/FFmpeg/libavcodec/x86/hevcdsp_init.c \
../lib/FFmpeg/libavcodec/x86/hpeldsp_init.c \
../lib/FFmpeg/libavcodec/x86/hpeldsp_rnd_template.c \
../lib/FFmpeg/libavcodec/x86/hpeldsp_vp3_init.c \
../lib/FFmpeg/libavcodec/x86/huffyuvdsp_init.c \
../lib/FFmpeg/libavcodec/x86/huffyuvencdsp_init.c \
../lib/FFmpeg/libavcodec/x86/idctdsp_init.c \
../lib/FFmpeg/libavcodec/x86/jpeg2000dsp_init.c \
../lib/FFmpeg/libavcodec/x86/lossless_audiodsp_init.c \
../lib/FFmpeg/libavcodec/x86/lossless_videodsp_init.c \
../lib/FFmpeg/libavcodec/x86/lossless_videoencdsp_init.c \
../lib/FFmpeg/libavcodec/x86/lpc.c \
../lib/FFmpeg/libavcodec/x86/mdct15_init.c \
../lib/FFmpeg/libavcodec/x86/me_cmp_init.c \
../lib/FFmpeg/libavcodec/x86/mlpdsp_init.c \
../lib/FFmpeg/libavcodec/x86/mpegaudiodsp.c \
../lib/FFmpeg/libavcodec/x86/mpegvideo.c \
../lib/FFmpeg/libavcodec/x86/mpegvideodsp.c \
../lib/FFmpeg/libavcodec/x86/mpegvideoenc.c \
../lib/FFmpeg/libavcodec/x86/mpegvideoenc_qns_template.c \
../lib/FFmpeg/libavcodec/x86/mpegvideoenc_template.c \
../lib/FFmpeg/libavcodec/x86/mpegvideoencdsp_init.c \
../lib/FFmpeg/libavcodec/x86/opus_dsp_init.c \
../lib/FFmpeg/libavcodec/x86/pixblockdsp_init.c \
../lib/FFmpeg/libavcodec/x86/pngdsp_init.c \
../lib/FFmpeg/libavcodec/x86/proresdsp_init.c \
../lib/FFmpeg/libavcodec/x86/qpeldsp_init.c \
../lib/FFmpeg/libavcodec/x86/rnd_template.c \
../lib/FFmpeg/libavcodec/x86/rv34dsp_init.c \
../lib/FFmpeg/libavcodec/x86/rv40dsp_init.c \
../lib/FFmpeg/libavcodec/x86/sbcdsp_init.c \
../lib/FFmpeg/libavcodec/x86/sbrdsp_init.c \
../lib/FFmpeg/libavcodec/x86/snowdsp.c \
../lib/FFmpeg/libavcodec/x86/svq1enc_init.c \
../lib/FFmpeg/libavcodec/x86/synth_filter_init.c \
../lib/FFmpeg/libavcodec/x86/takdsp_init.c \
../lib/FFmpeg/libavcodec/x86/ttadsp_init.c \
../lib/FFmpeg/libavcodec/x86/ttaencdsp_init.c \
../lib/FFmpeg/libavcodec/x86/utvideodsp_init.c \
../lib/FFmpeg/libavcodec/x86/v210-init.c \
../lib/FFmpeg/libavcodec/x86/v210enc_init.c \
../lib/FFmpeg/libavcodec/x86/vc1dsp_init.c \
../lib/FFmpeg/libavcodec/x86/vc1dsp_mmx.c \
../lib/FFmpeg/libavcodec/x86/videodsp_init.c \
../lib/FFmpeg/libavcodec/x86/vorbisdsp_init.c \
../lib/FFmpeg/libavcodec/x86/vp3dsp_init.c \
../lib/FFmpeg/libavcodec/x86/vp6dsp_init.c \
../lib/FFmpeg/libavcodec/x86/vp8dsp_init.c \
../lib/FFmpeg/libavcodec/x86/vp9dsp_init.c \
../lib/FFmpeg/libavcodec/x86/vp9dsp_init_10bpp.c \
../lib/FFmpeg/libavcodec/x86/vp9dsp_init_12bpp.c \
../lib/FFmpeg/libavcodec/x86/vp9dsp_init_16bpp.c \
../lib/FFmpeg/libavcodec/x86/vp9dsp_init_16bpp_template.c \
../lib/FFmpeg/libavcodec/x86/w64xmmtest.c \
../lib/FFmpeg/libavcodec/x86/xvididct_init.c 

O_SRCS += \
../lib/FFmpeg/libavcodec/x86/aacencdsp.o \
../lib/FFmpeg/libavcodec/x86/aacencdsp_init.o \
../lib/FFmpeg/libavcodec/x86/aacpsdsp.o \
../lib/FFmpeg/libavcodec/x86/aacpsdsp_init.o \
../lib/FFmpeg/libavcodec/x86/ac3dsp.o \
../lib/FFmpeg/libavcodec/x86/ac3dsp_downmix.o \
../lib/FFmpeg/libavcodec/x86/ac3dsp_init.o \
../lib/FFmpeg/libavcodec/x86/alacdsp.o \
../lib/FFmpeg/libavcodec/x86/alacdsp_init.o \
../lib/FFmpeg/libavcodec/x86/audiodsp.o \
../lib/FFmpeg/libavcodec/x86/audiodsp_init.o \
../lib/FFmpeg/libavcodec/x86/blockdsp.o \
../lib/FFmpeg/libavcodec/x86/blockdsp_init.o \
../lib/FFmpeg/libavcodec/x86/bswapdsp.o \
../lib/FFmpeg/libavcodec/x86/bswapdsp_init.o \
../lib/FFmpeg/libavcodec/x86/cavsdsp.o \
../lib/FFmpeg/libavcodec/x86/cavsidct.o \
../lib/FFmpeg/libavcodec/x86/constants.o \
../lib/FFmpeg/libavcodec/x86/dcadsp.o \
../lib/FFmpeg/libavcodec/x86/dcadsp_init.o \
../lib/FFmpeg/libavcodec/x86/dct32.o \
../lib/FFmpeg/libavcodec/x86/dct_init.o \
../lib/FFmpeg/libavcodec/x86/dirac_dwt.o \
../lib/FFmpeg/libavcodec/x86/dirac_dwt_init.o \
../lib/FFmpeg/libavcodec/x86/diracdsp.o \
../lib/FFmpeg/libavcodec/x86/diracdsp_init.o \
../lib/FFmpeg/libavcodec/x86/dnxhdenc.o \
../lib/FFmpeg/libavcodec/x86/dnxhdenc_init.o \
../lib/FFmpeg/libavcodec/x86/exrdsp.o \
../lib/FFmpeg/libavcodec/x86/exrdsp_init.o \
../lib/FFmpeg/libavcodec/x86/fdct.o \
../lib/FFmpeg/libavcodec/x86/fdctdsp_init.o \
../lib/FFmpeg/libavcodec/x86/fft.o \
../lib/FFmpeg/libavcodec/x86/fft_init.o \
../lib/FFmpeg/libavcodec/x86/flacdsp.o \
../lib/FFmpeg/libavcodec/x86/flacdsp_init.o \
../lib/FFmpeg/libavcodec/x86/fmtconvert.o \
../lib/FFmpeg/libavcodec/x86/fmtconvert_init.o \
../lib/FFmpeg/libavcodec/x86/fpel.o \
../lib/FFmpeg/libavcodec/x86/g722dsp.o \
../lib/FFmpeg/libavcodec/x86/g722dsp_init.o \
../lib/FFmpeg/libavcodec/x86/h263_loopfilter.o \
../lib/FFmpeg/libavcodec/x86/h263dsp_init.o \
../lib/FFmpeg/libavcodec/x86/h264_chromamc.o \
../lib/FFmpeg/libavcodec/x86/h264_chromamc_10bit.o \
../lib/FFmpeg/libavcodec/x86/h264_deblock.o \
../lib/FFmpeg/libavcodec/x86/h264_deblock_10bit.o \
../lib/FFmpeg/libavcodec/x86/h264_idct.o \
../lib/FFmpeg/libavcodec/x86/h264_idct_10bit.o \
../lib/FFmpeg/libavcodec/x86/h264_intrapred.o \
../lib/FFmpeg/libavcodec/x86/h264_intrapred_10bit.o \
../lib/FFmpeg/libavcodec/x86/h264_intrapred_init.o \
../lib/FFmpeg/libavcodec/x86/h264_qpel.o \
../lib/FFmpeg/libavcodec/x86/h264_qpel_10bit.o \
../lib/FFmpeg/libavcodec/x86/h264_qpel_8bit.o \
../lib/FFmpeg/libavcodec/x86/h264_weight.o \
../lib/FFmpeg/libavcodec/x86/h264_weight_10bit.o \
../lib/FFmpeg/libavcodec/x86/h264chroma_init.o \
../lib/FFmpeg/libavcodec/x86/h264dsp_init.o \
../lib/FFmpeg/libavcodec/x86/hevc_add_res.o \
../lib/FFmpeg/libavcodec/x86/hevc_deblock.o \
../lib/FFmpeg/libavcodec/x86/hevc_idct.o \
../lib/FFmpeg/libavcodec/x86/hevc_mc.o \
../lib/FFmpeg/libavcodec/x86/hevc_sao.o \
../lib/FFmpeg/libavcodec/x86/hevc_sao_10bit.o \
../lib/FFmpeg/libavcodec/x86/hevcdsp_init.o \
../lib/FFmpeg/libavcodec/x86/hpeldsp.o \
../lib/FFmpeg/libavcodec/x86/hpeldsp_init.o \
../lib/FFmpeg/libavcodec/x86/hpeldsp_vp3.o \
../lib/FFmpeg/libavcodec/x86/hpeldsp_vp3_init.o \
../lib/FFmpeg/libavcodec/x86/huffyuvdsp.o \
../lib/FFmpeg/libavcodec/x86/huffyuvdsp_init.o \
../lib/FFmpeg/libavcodec/x86/huffyuvencdsp.o \
../lib/FFmpeg/libavcodec/x86/huffyuvencdsp_init.o \
../lib/FFmpeg/libavcodec/x86/idctdsp.o \
../lib/FFmpeg/libavcodec/x86/idctdsp_init.o \
../lib/FFmpeg/libavcodec/x86/imdct36.o \
../lib/FFmpeg/libavcodec/x86/jpeg2000dsp.o \
../lib/FFmpeg/libavcodec/x86/jpeg2000dsp_init.o \
../lib/FFmpeg/libavcodec/x86/lossless_audiodsp.o \
../lib/FFmpeg/libavcodec/x86/lossless_audiodsp_init.o \
../lib/FFmpeg/libavcodec/x86/lossless_videodsp.o \
../lib/FFmpeg/libavcodec/x86/lossless_videodsp_init.o \
../lib/FFmpeg/libavcodec/x86/lossless_videoencdsp.o \
../lib/FFmpeg/libavcodec/x86/lossless_videoencdsp_init.o \
../lib/FFmpeg/libavcodec/x86/lpc.o \
../lib/FFmpeg/libavcodec/x86/mdct15.o \
../lib/FFmpeg/libavcodec/x86/mdct15_init.o \
../lib/FFmpeg/libavcodec/x86/me_cmp.o \
../lib/FFmpeg/libavcodec/x86/me_cmp_init.o \
../lib/FFmpeg/libavcodec/x86/mlpdsp.o \
../lib/FFmpeg/libavcodec/x86/mlpdsp_init.o \
../lib/FFmpeg/libavcodec/x86/mpegaudiodsp.o \
../lib/FFmpeg/libavcodec/x86/mpegvideo.o \
../lib/FFmpeg/libavcodec/x86/mpegvideodsp.o \
../lib/FFmpeg/libavcodec/x86/mpegvideoenc.o \
../lib/FFmpeg/libavcodec/x86/mpegvideoencdsp.o \
../lib/FFmpeg/libavcodec/x86/mpegvideoencdsp_init.o \
../lib/FFmpeg/libavcodec/x86/opus_dsp_init.o \
../lib/FFmpeg/libavcodec/x86/opus_pvq_search.o \
../lib/FFmpeg/libavcodec/x86/pixblockdsp.o \
../lib/FFmpeg/libavcodec/x86/pixblockdsp_init.o \
../lib/FFmpeg/libavcodec/x86/pngdsp.o \
../lib/FFmpeg/libavcodec/x86/pngdsp_init.o \
../lib/FFmpeg/libavcodec/x86/proresdsp.o \
../lib/FFmpeg/libavcodec/x86/proresdsp_init.o \
../lib/FFmpeg/libavcodec/x86/qpel.o \
../lib/FFmpeg/libavcodec/x86/qpeldsp.o \
../lib/FFmpeg/libavcodec/x86/qpeldsp_init.o \
../lib/FFmpeg/libavcodec/x86/rv34dsp.o \
../lib/FFmpeg/libavcodec/x86/rv34dsp_init.o \
../lib/FFmpeg/libavcodec/x86/rv40dsp.o \
../lib/FFmpeg/libavcodec/x86/rv40dsp_init.o \
../lib/FFmpeg/libavcodec/x86/sbcdsp.o \
../lib/FFmpeg/libavcodec/x86/sbcdsp_init.o \
../lib/FFmpeg/libavcodec/x86/sbrdsp.o \
../lib/FFmpeg/libavcodec/x86/sbrdsp_init.o \
../lib/FFmpeg/libavcodec/x86/simple_idct.o \
../lib/FFmpeg/libavcodec/x86/simple_idct10.o \
../lib/FFmpeg/libavcodec/x86/snowdsp.o \
../lib/FFmpeg/libavcodec/x86/svq1enc.o \
../lib/FFmpeg/libavcodec/x86/svq1enc_init.o \
../lib/FFmpeg/libavcodec/x86/synth_filter.o \
../lib/FFmpeg/libavcodec/x86/synth_filter_init.o \
../lib/FFmpeg/libavcodec/x86/takdsp.o \
../lib/FFmpeg/libavcodec/x86/takdsp_init.o \
../lib/FFmpeg/libavcodec/x86/ttadsp.o \
../lib/FFmpeg/libavcodec/x86/ttadsp_init.o \
../lib/FFmpeg/libavcodec/x86/ttaencdsp.o \
../lib/FFmpeg/libavcodec/x86/ttaencdsp_init.o \
../lib/FFmpeg/libavcodec/x86/utvideodsp.o \
../lib/FFmpeg/libavcodec/x86/utvideodsp_init.o \
../lib/FFmpeg/libavcodec/x86/v210-init.o \
../lib/FFmpeg/libavcodec/x86/v210.o \
../lib/FFmpeg/libavcodec/x86/v210enc.o \
../lib/FFmpeg/libavcodec/x86/v210enc_init.o \
../lib/FFmpeg/libavcodec/x86/vc1dsp_init.o \
../lib/FFmpeg/libavcodec/x86/vc1dsp_loopfilter.o \
../lib/FFmpeg/libavcodec/x86/vc1dsp_mc.o \
../lib/FFmpeg/libavcodec/x86/vc1dsp_mmx.o \
../lib/FFmpeg/libavcodec/x86/videodsp.o \
../lib/FFmpeg/libavcodec/x86/videodsp_init.o \
../lib/FFmpeg/libavcodec/x86/vorbisdsp.o \
../lib/FFmpeg/libavcodec/x86/vorbisdsp_init.o \
../lib/FFmpeg/libavcodec/x86/vp3dsp.o \
../lib/FFmpeg/libavcodec/x86/vp3dsp_init.o \
../lib/FFmpeg/libavcodec/x86/vp6dsp.o \
../lib/FFmpeg/libavcodec/x86/vp6dsp_init.o \
../lib/FFmpeg/libavcodec/x86/vp8dsp.o \
../lib/FFmpeg/libavcodec/x86/vp8dsp_init.o \
../lib/FFmpeg/libavcodec/x86/vp8dsp_loopfilter.o \
../lib/FFmpeg/libavcodec/x86/vp9dsp_init.o \
../lib/FFmpeg/libavcodec/x86/vp9dsp_init_10bpp.o \
../lib/FFmpeg/libavcodec/x86/vp9dsp_init_12bpp.o \
../lib/FFmpeg/libavcodec/x86/vp9dsp_init_16bpp.o \
../lib/FFmpeg/libavcodec/x86/vp9intrapred.o \
../lib/FFmpeg/libavcodec/x86/vp9intrapred_16bpp.o \
../lib/FFmpeg/libavcodec/x86/vp9itxfm.o \
../lib/FFmpeg/libavcodec/x86/vp9itxfm_16bpp.o \
../lib/FFmpeg/libavcodec/x86/vp9lpf.o \
../lib/FFmpeg/libavcodec/x86/vp9lpf_16bpp.o \
../lib/FFmpeg/libavcodec/x86/vp9mc.o \
../lib/FFmpeg/libavcodec/x86/vp9mc_16bpp.o \
../lib/FFmpeg/libavcodec/x86/xvididct.o \
../lib/FFmpeg/libavcodec/x86/xvididct_init.o 

OBJS += \
./lib/FFmpeg/libavcodec/x86/aacencdsp.o \
./lib/FFmpeg/libavcodec/x86/aacencdsp_init.o \
./lib/FFmpeg/libavcodec/x86/aacpsdsp.o \
./lib/FFmpeg/libavcodec/x86/aacpsdsp_init.o \
./lib/FFmpeg/libavcodec/x86/ac3dsp.o \
./lib/FFmpeg/libavcodec/x86/ac3dsp_downmix.o \
./lib/FFmpeg/libavcodec/x86/ac3dsp_init.o \
./lib/FFmpeg/libavcodec/x86/alacdsp.o \
./lib/FFmpeg/libavcodec/x86/alacdsp_init.o \
./lib/FFmpeg/libavcodec/x86/audiodsp.o \
./lib/FFmpeg/libavcodec/x86/audiodsp_init.o \
./lib/FFmpeg/libavcodec/x86/blockdsp.o \
./lib/FFmpeg/libavcodec/x86/blockdsp_init.o \
./lib/FFmpeg/libavcodec/x86/bswapdsp.o \
./lib/FFmpeg/libavcodec/x86/bswapdsp_init.o \
./lib/FFmpeg/libavcodec/x86/cavsdsp.o \
./lib/FFmpeg/libavcodec/x86/cavsidct.o \
./lib/FFmpeg/libavcodec/x86/constants.o \
./lib/FFmpeg/libavcodec/x86/dcadsp.o \
./lib/FFmpeg/libavcodec/x86/dcadsp_init.o \
./lib/FFmpeg/libavcodec/x86/dct32.o \
./lib/FFmpeg/libavcodec/x86/dct_init.o \
./lib/FFmpeg/libavcodec/x86/dirac_dwt.o \
./lib/FFmpeg/libavcodec/x86/dirac_dwt_init.o \
./lib/FFmpeg/libavcodec/x86/diracdsp.o \
./lib/FFmpeg/libavcodec/x86/diracdsp_init.o \
./lib/FFmpeg/libavcodec/x86/dnxhdenc.o \
./lib/FFmpeg/libavcodec/x86/dnxhdenc_init.o \
./lib/FFmpeg/libavcodec/x86/exrdsp.o \
./lib/FFmpeg/libavcodec/x86/exrdsp_init.o \
./lib/FFmpeg/libavcodec/x86/fdct.o \
./lib/FFmpeg/libavcodec/x86/fdctdsp_init.o \
./lib/FFmpeg/libavcodec/x86/fft.o \
./lib/FFmpeg/libavcodec/x86/fft_init.o \
./lib/FFmpeg/libavcodec/x86/flac_dsp_gpl.o \
./lib/FFmpeg/libavcodec/x86/flacdsp.o \
./lib/FFmpeg/libavcodec/x86/flacdsp_init.o \
./lib/FFmpeg/libavcodec/x86/fmtconvert.o \
./lib/FFmpeg/libavcodec/x86/fmtconvert_init.o \
./lib/FFmpeg/libavcodec/x86/fpel.o \
./lib/FFmpeg/libavcodec/x86/g722dsp.o \
./lib/FFmpeg/libavcodec/x86/g722dsp_init.o \
./lib/FFmpeg/libavcodec/x86/h263_loopfilter.o \
./lib/FFmpeg/libavcodec/x86/h263dsp_init.o \
./lib/FFmpeg/libavcodec/x86/h264_cabac.o \
./lib/FFmpeg/libavcodec/x86/h264_chromamc.o \
./lib/FFmpeg/libavcodec/x86/h264_chromamc_10bit.o \
./lib/FFmpeg/libavcodec/x86/h264_deblock.o \
./lib/FFmpeg/libavcodec/x86/h264_deblock_10bit.o \
./lib/FFmpeg/libavcodec/x86/h264_idct.o \
./lib/FFmpeg/libavcodec/x86/h264_idct_10bit.o \
./lib/FFmpeg/libavcodec/x86/h264_intrapred.o \
./lib/FFmpeg/libavcodec/x86/h264_intrapred_10bit.o \
./lib/FFmpeg/libavcodec/x86/h264_intrapred_init.o \
./lib/FFmpeg/libavcodec/x86/h264_qpel.o \
./lib/FFmpeg/libavcodec/x86/h264_qpel_10bit.o \
./lib/FFmpeg/libavcodec/x86/h264_qpel_8bit.o \
./lib/FFmpeg/libavcodec/x86/h264_weight.o \
./lib/FFmpeg/libavcodec/x86/h264_weight_10bit.o \
./lib/FFmpeg/libavcodec/x86/h264chroma_init.o \
./lib/FFmpeg/libavcodec/x86/h264dsp_init.o \
./lib/FFmpeg/libavcodec/x86/hevc_add_res.o \
./lib/FFmpeg/libavcodec/x86/hevc_deblock.o \
./lib/FFmpeg/libavcodec/x86/hevc_idct.o \
./lib/FFmpeg/libavcodec/x86/hevc_mc.o \
./lib/FFmpeg/libavcodec/x86/hevc_sao.o \
./lib/FFmpeg/libavcodec/x86/hevc_sao_10bit.o \
./lib/FFmpeg/libavcodec/x86/hevcdsp_init.o \
./lib/FFmpeg/libavcodec/x86/hpeldsp.o \
./lib/FFmpeg/libavcodec/x86/hpeldsp_init.o \
./lib/FFmpeg/libavcodec/x86/hpeldsp_rnd_template.o \
./lib/FFmpeg/libavcodec/x86/hpeldsp_vp3.o \
./lib/FFmpeg/libavcodec/x86/hpeldsp_vp3_init.o \
./lib/FFmpeg/libavcodec/x86/huffyuvdsp.o \
./lib/FFmpeg/libavcodec/x86/huffyuvdsp_init.o \
./lib/FFmpeg/libavcodec/x86/huffyuvdsp_template.o \
./lib/FFmpeg/libavcodec/x86/huffyuvencdsp.o \
./lib/FFmpeg/libavcodec/x86/huffyuvencdsp_init.o \
./lib/FFmpeg/libavcodec/x86/idctdsp.o \
./lib/FFmpeg/libavcodec/x86/idctdsp_init.o \
./lib/FFmpeg/libavcodec/x86/imdct36.o \
./lib/FFmpeg/libavcodec/x86/jpeg2000dsp.o \
./lib/FFmpeg/libavcodec/x86/jpeg2000dsp_init.o \
./lib/FFmpeg/libavcodec/x86/lossless_audiodsp.o \
./lib/FFmpeg/libavcodec/x86/lossless_audiodsp_init.o \
./lib/FFmpeg/libavcodec/x86/lossless_videodsp.o \
./lib/FFmpeg/libavcodec/x86/lossless_videodsp_init.o \
./lib/FFmpeg/libavcodec/x86/lossless_videoencdsp.o \
./lib/FFmpeg/libavcodec/x86/lossless_videoencdsp_init.o \
./lib/FFmpeg/libavcodec/x86/lpc.o \
./lib/FFmpeg/libavcodec/x86/mdct15.o \
./lib/FFmpeg/libavcodec/x86/mdct15_init.o \
./lib/FFmpeg/libavcodec/x86/me_cmp.o \
./lib/FFmpeg/libavcodec/x86/me_cmp_init.o \
./lib/FFmpeg/libavcodec/x86/mlpdsp.o \
./lib/FFmpeg/libavcodec/x86/mlpdsp_init.o \
./lib/FFmpeg/libavcodec/x86/mpegaudiodsp.o \
./lib/FFmpeg/libavcodec/x86/mpegvideo.o \
./lib/FFmpeg/libavcodec/x86/mpegvideodsp.o \
./lib/FFmpeg/libavcodec/x86/mpegvideoenc.o \
./lib/FFmpeg/libavcodec/x86/mpegvideoenc_qns_template.o \
./lib/FFmpeg/libavcodec/x86/mpegvideoenc_template.o \
./lib/FFmpeg/libavcodec/x86/mpegvideoencdsp.o \
./lib/FFmpeg/libavcodec/x86/mpegvideoencdsp_init.o \
./lib/FFmpeg/libavcodec/x86/opus_dsp_init.o \
./lib/FFmpeg/libavcodec/x86/opus_pvq_search.o \
./lib/FFmpeg/libavcodec/x86/pixblockdsp.o \
./lib/FFmpeg/libavcodec/x86/pixblockdsp_init.o \
./lib/FFmpeg/libavcodec/x86/pngdsp.o \
./lib/FFmpeg/libavcodec/x86/pngdsp_init.o \
./lib/FFmpeg/libavcodec/x86/proresdsp.o \
./lib/FFmpeg/libavcodec/x86/proresdsp_init.o \
./lib/FFmpeg/libavcodec/x86/qpel.o \
./lib/FFmpeg/libavcodec/x86/qpeldsp.o \
./lib/FFmpeg/libavcodec/x86/qpeldsp_init.o \
./lib/FFmpeg/libavcodec/x86/rnd_template.o \
./lib/FFmpeg/libavcodec/x86/rv34dsp.o \
./lib/FFmpeg/libavcodec/x86/rv34dsp_init.o \
./lib/FFmpeg/libavcodec/x86/rv40dsp.o \
./lib/FFmpeg/libavcodec/x86/rv40dsp_init.o \
./lib/FFmpeg/libavcodec/x86/sbcdsp.o \
./lib/FFmpeg/libavcodec/x86/sbcdsp_init.o \
./lib/FFmpeg/libavcodec/x86/sbrdsp.o \
./lib/FFmpeg/libavcodec/x86/sbrdsp_init.o \
./lib/FFmpeg/libavcodec/x86/simple_idct.o \
./lib/FFmpeg/libavcodec/x86/simple_idct10.o \
./lib/FFmpeg/libavcodec/x86/simple_idct10_template.o \
./lib/FFmpeg/libavcodec/x86/snowdsp.o \
./lib/FFmpeg/libavcodec/x86/svq1enc.o \
./lib/FFmpeg/libavcodec/x86/svq1enc_init.o \
./lib/FFmpeg/libavcodec/x86/synth_filter.o \
./lib/FFmpeg/libavcodec/x86/synth_filter_init.o \
./lib/FFmpeg/libavcodec/x86/takdsp.o \
./lib/FFmpeg/libavcodec/x86/takdsp_init.o \
./lib/FFmpeg/libavcodec/x86/ttadsp.o \
./lib/FFmpeg/libavcodec/x86/ttadsp_init.o \
./lib/FFmpeg/libavcodec/x86/ttaencdsp.o \
./lib/FFmpeg/libavcodec/x86/ttaencdsp_init.o \
./lib/FFmpeg/libavcodec/x86/utvideodsp.o \
./lib/FFmpeg/libavcodec/x86/utvideodsp_init.o \
./lib/FFmpeg/libavcodec/x86/v210-init.o \
./lib/FFmpeg/libavcodec/x86/v210.o \
./lib/FFmpeg/libavcodec/x86/v210enc.o \
./lib/FFmpeg/libavcodec/x86/v210enc_init.o \
./lib/FFmpeg/libavcodec/x86/vc1dsp_init.o \
./lib/FFmpeg/libavcodec/x86/vc1dsp_loopfilter.o \
./lib/FFmpeg/libavcodec/x86/vc1dsp_mc.o \
./lib/FFmpeg/libavcodec/x86/vc1dsp_mmx.o \
./lib/FFmpeg/libavcodec/x86/videodsp.o \
./lib/FFmpeg/libavcodec/x86/videodsp_init.o \
./lib/FFmpeg/libavcodec/x86/vorbisdsp.o \
./lib/FFmpeg/libavcodec/x86/vorbisdsp_init.o \
./lib/FFmpeg/libavcodec/x86/vp3dsp.o \
./lib/FFmpeg/libavcodec/x86/vp3dsp_init.o \
./lib/FFmpeg/libavcodec/x86/vp6dsp.o \
./lib/FFmpeg/libavcodec/x86/vp6dsp_init.o \
./lib/FFmpeg/libavcodec/x86/vp8dsp.o \
./lib/FFmpeg/libavcodec/x86/vp8dsp_init.o \
./lib/FFmpeg/libavcodec/x86/vp8dsp_loopfilter.o \
./lib/FFmpeg/libavcodec/x86/vp9dsp_init.o \
./lib/FFmpeg/libavcodec/x86/vp9dsp_init_10bpp.o \
./lib/FFmpeg/libavcodec/x86/vp9dsp_init_12bpp.o \
./lib/FFmpeg/libavcodec/x86/vp9dsp_init_16bpp.o \
./lib/FFmpeg/libavcodec/x86/vp9dsp_init_16bpp_template.o \
./lib/FFmpeg/libavcodec/x86/vp9intrapred.o \
./lib/FFmpeg/libavcodec/x86/vp9intrapred_16bpp.o \
./lib/FFmpeg/libavcodec/x86/vp9itxfm.o \
./lib/FFmpeg/libavcodec/x86/vp9itxfm_16bpp.o \
./lib/FFmpeg/libavcodec/x86/vp9itxfm_template.o \
./lib/FFmpeg/libavcodec/x86/vp9lpf.o \
./lib/FFmpeg/libavcodec/x86/vp9lpf_16bpp.o \
./lib/FFmpeg/libavcodec/x86/vp9mc.o \
./lib/FFmpeg/libavcodec/x86/vp9mc_16bpp.o \
./lib/FFmpeg/libavcodec/x86/w64xmmtest.o \
./lib/FFmpeg/libavcodec/x86/xvididct.o \
./lib/FFmpeg/libavcodec/x86/xvididct_init.o 

C_DEPS += \
./lib/FFmpeg/libavcodec/x86/aacencdsp_init.d \
./lib/FFmpeg/libavcodec/x86/aacpsdsp_init.d \
./lib/FFmpeg/libavcodec/x86/ac3dsp_init.d \
./lib/FFmpeg/libavcodec/x86/alacdsp_init.d \
./lib/FFmpeg/libavcodec/x86/audiodsp_init.d \
./lib/FFmpeg/libavcodec/x86/blockdsp_init.d \
./lib/FFmpeg/libavcodec/x86/bswapdsp_init.d \
./lib/FFmpeg/libavcodec/x86/cavsdsp.d \
./lib/FFmpeg/libavcodec/x86/constants.d \
./lib/FFmpeg/libavcodec/x86/dcadsp_init.d \
./lib/FFmpeg/libavcodec/x86/dct_init.d \
./lib/FFmpeg/libavcodec/x86/dirac_dwt_init.d \
./lib/FFmpeg/libavcodec/x86/diracdsp_init.d \
./lib/FFmpeg/libavcodec/x86/dnxhdenc_init.d \
./lib/FFmpeg/libavcodec/x86/exrdsp_init.d \
./lib/FFmpeg/libavcodec/x86/fdct.d \
./lib/FFmpeg/libavcodec/x86/fdctdsp_init.d \
./lib/FFmpeg/libavcodec/x86/fft_init.d \
./lib/FFmpeg/libavcodec/x86/flacdsp_init.d \
./lib/FFmpeg/libavcodec/x86/fmtconvert_init.d \
./lib/FFmpeg/libavcodec/x86/g722dsp_init.d \
./lib/FFmpeg/libavcodec/x86/h263dsp_init.d \
./lib/FFmpeg/libavcodec/x86/h264_cabac.d \
./lib/FFmpeg/libavcodec/x86/h264_intrapred_init.d \
./lib/FFmpeg/libavcodec/x86/h264_qpel.d \
./lib/FFmpeg/libavcodec/x86/h264chroma_init.d \
./lib/FFmpeg/libavcodec/x86/h264dsp_init.d \
./lib/FFmpeg/libavcodec/x86/hevcdsp_init.d \
./lib/FFmpeg/libavcodec/x86/hpeldsp_init.d \
./lib/FFmpeg/libavcodec/x86/hpeldsp_rnd_template.d \
./lib/FFmpeg/libavcodec/x86/hpeldsp_vp3_init.d \
./lib/FFmpeg/libavcodec/x86/huffyuvdsp_init.d \
./lib/FFmpeg/libavcodec/x86/huffyuvencdsp_init.d \
./lib/FFmpeg/libavcodec/x86/idctdsp_init.d \
./lib/FFmpeg/libavcodec/x86/jpeg2000dsp_init.d \
./lib/FFmpeg/libavcodec/x86/lossless_audiodsp_init.d \
./lib/FFmpeg/libavcodec/x86/lossless_videodsp_init.d \
./lib/FFmpeg/libavcodec/x86/lossless_videoencdsp_init.d \
./lib/FFmpeg/libavcodec/x86/lpc.d \
./lib/FFmpeg/libavcodec/x86/mdct15_init.d \
./lib/FFmpeg/libavcodec/x86/me_cmp_init.d \
./lib/FFmpeg/libavcodec/x86/mlpdsp_init.d \
./lib/FFmpeg/libavcodec/x86/mpegaudiodsp.d \
./lib/FFmpeg/libavcodec/x86/mpegvideo.d \
./lib/FFmpeg/libavcodec/x86/mpegvideodsp.d \
./lib/FFmpeg/libavcodec/x86/mpegvideoenc.d \
./lib/FFmpeg/libavcodec/x86/mpegvideoenc_qns_template.d \
./lib/FFmpeg/libavcodec/x86/mpegvideoenc_template.d \
./lib/FFmpeg/libavcodec/x86/mpegvideoencdsp_init.d \
./lib/FFmpeg/libavcodec/x86/opus_dsp_init.d \
./lib/FFmpeg/libavcodec/x86/pixblockdsp_init.d \
./lib/FFmpeg/libavcodec/x86/pngdsp_init.d \
./lib/FFmpeg/libavcodec/x86/proresdsp_init.d \
./lib/FFmpeg/libavcodec/x86/qpeldsp_init.d \
./lib/FFmpeg/libavcodec/x86/rnd_template.d \
./lib/FFmpeg/libavcodec/x86/rv34dsp_init.d \
./lib/FFmpeg/libavcodec/x86/rv40dsp_init.d \
./lib/FFmpeg/libavcodec/x86/sbcdsp_init.d \
./lib/FFmpeg/libavcodec/x86/sbrdsp_init.d \
./lib/FFmpeg/libavcodec/x86/snowdsp.d \
./lib/FFmpeg/libavcodec/x86/svq1enc_init.d \
./lib/FFmpeg/libavcodec/x86/synth_filter_init.d \
./lib/FFmpeg/libavcodec/x86/takdsp_init.d \
./lib/FFmpeg/libavcodec/x86/ttadsp_init.d \
./lib/FFmpeg/libavcodec/x86/ttaencdsp_init.d \
./lib/FFmpeg/libavcodec/x86/utvideodsp_init.d \
./lib/FFmpeg/libavcodec/x86/v210-init.d \
./lib/FFmpeg/libavcodec/x86/v210enc_init.d \
./lib/FFmpeg/libavcodec/x86/vc1dsp_init.d \
./lib/FFmpeg/libavcodec/x86/vc1dsp_mmx.d \
./lib/FFmpeg/libavcodec/x86/videodsp_init.d \
./lib/FFmpeg/libavcodec/x86/vorbisdsp_init.d \
./lib/FFmpeg/libavcodec/x86/vp3dsp_init.d \
./lib/FFmpeg/libavcodec/x86/vp6dsp_init.d \
./lib/FFmpeg/libavcodec/x86/vp8dsp_init.d \
./lib/FFmpeg/libavcodec/x86/vp9dsp_init.d \
./lib/FFmpeg/libavcodec/x86/vp9dsp_init_10bpp.d \
./lib/FFmpeg/libavcodec/x86/vp9dsp_init_12bpp.d \
./lib/FFmpeg/libavcodec/x86/vp9dsp_init_16bpp.d \
./lib/FFmpeg/libavcodec/x86/vp9dsp_init_16bpp_template.d \
./lib/FFmpeg/libavcodec/x86/w64xmmtest.d \
./lib/FFmpeg/libavcodec/x86/xvididct_init.d 


# Each subdirectory must supply rules for building sources it contributes
lib/FFmpeg/libavcodec/x86/%.o: ../lib/FFmpeg/libavcodec/x86/%.asm
	@echo 'Building file: $<'
	@echo 'Invoking: GCC Assembler'
	as  -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

lib/FFmpeg/libavcodec/x86/%.o: ../lib/FFmpeg/libavcodec/x86/%.c
	@echo 'Building file: $<'
	@echo 'Invoking: GCC C Compiler'
	gcc -O0 -g3 -Wall -c -fmessage-length=0 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@)" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '


