################################################################################
# Automatically-generated file. Do not edit!
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
C_SRCS += \
../lib/ImageMagick/MagickCore/accelerate.c \
../lib/ImageMagick/MagickCore/animate.c \
../lib/ImageMagick/MagickCore/annotate.c \
../lib/ImageMagick/MagickCore/artifact.c \
../lib/ImageMagick/MagickCore/attribute.c \
../lib/ImageMagick/MagickCore/blob.c \
../lib/ImageMagick/MagickCore/cache-view.c \
../lib/ImageMagick/MagickCore/cache.c \
../lib/ImageMagick/MagickCore/channel.c \
../lib/ImageMagick/MagickCore/cipher.c \
../lib/ImageMagick/MagickCore/client.c \
../lib/ImageMagick/MagickCore/coder.c \
../lib/ImageMagick/MagickCore/color.c \
../lib/ImageMagick/MagickCore/colormap.c \
../lib/ImageMagick/MagickCore/colorspace.c \
../lib/ImageMagick/MagickCore/compare.c \
../lib/ImageMagick/MagickCore/composite.c \
../lib/ImageMagick/MagickCore/compress.c \
../lib/ImageMagick/MagickCore/configure.c \
../lib/ImageMagick/MagickCore/constitute.c \
../lib/ImageMagick/MagickCore/decorate.c \
../lib/ImageMagick/MagickCore/delegate.c \
../lib/ImageMagick/MagickCore/deprecate.c \
../lib/ImageMagick/MagickCore/display.c \
../lib/ImageMagick/MagickCore/distort.c \
../lib/ImageMagick/MagickCore/distribute-cache.c \
../lib/ImageMagick/MagickCore/draw.c \
../lib/ImageMagick/MagickCore/effect.c \
../lib/ImageMagick/MagickCore/enhance.c \
../lib/ImageMagick/MagickCore/exception.c \
../lib/ImageMagick/MagickCore/feature.c \
../lib/ImageMagick/MagickCore/fourier.c \
../lib/ImageMagick/MagickCore/fx.c \
../lib/ImageMagick/MagickCore/gem.c \
../lib/ImageMagick/MagickCore/geometry.c \
../lib/ImageMagick/MagickCore/histogram.c \
../lib/ImageMagick/MagickCore/identify.c \
../lib/ImageMagick/MagickCore/image-view.c \
../lib/ImageMagick/MagickCore/image.c \
../lib/ImageMagick/MagickCore/layer.c \
../lib/ImageMagick/MagickCore/linked-list.c \
../lib/ImageMagick/MagickCore/list.c \
../lib/ImageMagick/MagickCore/locale.c \
../lib/ImageMagick/MagickCore/log.c \
../lib/ImageMagick/MagickCore/magic.c \
../lib/ImageMagick/MagickCore/magick.c \
../lib/ImageMagick/MagickCore/matrix.c \
../lib/ImageMagick/MagickCore/memory.c \
../lib/ImageMagick/MagickCore/mime.c \
../lib/ImageMagick/MagickCore/module.c \
../lib/ImageMagick/MagickCore/monitor.c \
../lib/ImageMagick/MagickCore/montage.c \
../lib/ImageMagick/MagickCore/morphology.c \
../lib/ImageMagick/MagickCore/nt-base.c \
../lib/ImageMagick/MagickCore/nt-feature.c \
../lib/ImageMagick/MagickCore/opencl.c \
../lib/ImageMagick/MagickCore/option.c \
../lib/ImageMagick/MagickCore/paint.c \
../lib/ImageMagick/MagickCore/pixel.c \
../lib/ImageMagick/MagickCore/policy.c \
../lib/ImageMagick/MagickCore/prepress.c \
../lib/ImageMagick/MagickCore/profile.c \
../lib/ImageMagick/MagickCore/property.c \
../lib/ImageMagick/MagickCore/quantize.c \
../lib/ImageMagick/MagickCore/quantum-export.c \
../lib/ImageMagick/MagickCore/quantum-import.c \
../lib/ImageMagick/MagickCore/quantum.c \
../lib/ImageMagick/MagickCore/random.c \
../lib/ImageMagick/MagickCore/registry.c \
../lib/ImageMagick/MagickCore/resample.c \
../lib/ImageMagick/MagickCore/resize.c \
../lib/ImageMagick/MagickCore/resource.c \
../lib/ImageMagick/MagickCore/segment.c \
../lib/ImageMagick/MagickCore/semaphore.c \
../lib/ImageMagick/MagickCore/shear.c \
../lib/ImageMagick/MagickCore/signature.c \
../lib/ImageMagick/MagickCore/splay-tree.c \
../lib/ImageMagick/MagickCore/static.c \
../lib/ImageMagick/MagickCore/statistic.c \
../lib/ImageMagick/MagickCore/stream.c \
../lib/ImageMagick/MagickCore/string.c \
../lib/ImageMagick/MagickCore/thread.c \
../lib/ImageMagick/MagickCore/threshold.c \
../lib/ImageMagick/MagickCore/timer.c \
../lib/ImageMagick/MagickCore/token.c \
../lib/ImageMagick/MagickCore/transform.c \
../lib/ImageMagick/MagickCore/type.c \
../lib/ImageMagick/MagickCore/utility.c \
../lib/ImageMagick/MagickCore/version.c \
../lib/ImageMagick/MagickCore/vision.c \
../lib/ImageMagick/MagickCore/vms.c \
../lib/ImageMagick/MagickCore/widget.c \
../lib/ImageMagick/MagickCore/xml-tree.c \
../lib/ImageMagick/MagickCore/xwindow.c 

O_SRCS += \
../lib/ImageMagick/MagickCore/libMagickCore_7_Q16HDRI_la-accelerate.o \
../lib/ImageMagick/MagickCore/libMagickCore_7_Q16HDRI_la-animate.o \
../lib/ImageMagick/MagickCore/libMagickCore_7_Q16HDRI_la-annotate.o \
../lib/ImageMagick/MagickCore/libMagickCore_7_Q16HDRI_la-artifact.o \
../lib/ImageMagick/MagickCore/libMagickCore_7_Q16HDRI_la-attribute.o \
../lib/ImageMagick/MagickCore/libMagickCore_7_Q16HDRI_la-blob.o \
../lib/ImageMagick/MagickCore/libMagickCore_7_Q16HDRI_la-cache-view.o \
../lib/ImageMagick/MagickCore/libMagickCore_7_Q16HDRI_la-cache.o \
../lib/ImageMagick/MagickCore/libMagickCore_7_Q16HDRI_la-channel.o \
../lib/ImageMagick/MagickCore/libMagickCore_7_Q16HDRI_la-cipher.o \
../lib/ImageMagick/MagickCore/libMagickCore_7_Q16HDRI_la-client.o \
../lib/ImageMagick/MagickCore/libMagickCore_7_Q16HDRI_la-coder.o \
../lib/ImageMagick/MagickCore/libMagickCore_7_Q16HDRI_la-color.o \
../lib/ImageMagick/MagickCore/libMagickCore_7_Q16HDRI_la-colormap.o \
../lib/ImageMagick/MagickCore/libMagickCore_7_Q16HDRI_la-colorspace.o \
../lib/ImageMagick/MagickCore/libMagickCore_7_Q16HDRI_la-compare.o \
../lib/ImageMagick/MagickCore/libMagickCore_7_Q16HDRI_la-composite.o \
../lib/ImageMagick/MagickCore/libMagickCore_7_Q16HDRI_la-compress.o \
../lib/ImageMagick/MagickCore/libMagickCore_7_Q16HDRI_la-configure.o \
../lib/ImageMagick/MagickCore/libMagickCore_7_Q16HDRI_la-constitute.o \
../lib/ImageMagick/MagickCore/libMagickCore_7_Q16HDRI_la-decorate.o \
../lib/ImageMagick/MagickCore/libMagickCore_7_Q16HDRI_la-delegate.o \
../lib/ImageMagick/MagickCore/libMagickCore_7_Q16HDRI_la-deprecate.o \
../lib/ImageMagick/MagickCore/libMagickCore_7_Q16HDRI_la-display.o \
../lib/ImageMagick/MagickCore/libMagickCore_7_Q16HDRI_la-distort.o \
../lib/ImageMagick/MagickCore/libMagickCore_7_Q16HDRI_la-distribute-cache.o \
../lib/ImageMagick/MagickCore/libMagickCore_7_Q16HDRI_la-draw.o \
../lib/ImageMagick/MagickCore/libMagickCore_7_Q16HDRI_la-effect.o \
../lib/ImageMagick/MagickCore/libMagickCore_7_Q16HDRI_la-enhance.o \
../lib/ImageMagick/MagickCore/libMagickCore_7_Q16HDRI_la-exception.o \
../lib/ImageMagick/MagickCore/libMagickCore_7_Q16HDRI_la-feature.o \
../lib/ImageMagick/MagickCore/libMagickCore_7_Q16HDRI_la-fourier.o \
../lib/ImageMagick/MagickCore/libMagickCore_7_Q16HDRI_la-fx.o \
../lib/ImageMagick/MagickCore/libMagickCore_7_Q16HDRI_la-gem.o \
../lib/ImageMagick/MagickCore/libMagickCore_7_Q16HDRI_la-geometry.o \
../lib/ImageMagick/MagickCore/libMagickCore_7_Q16HDRI_la-histogram.o \
../lib/ImageMagick/MagickCore/libMagickCore_7_Q16HDRI_la-identify.o \
../lib/ImageMagick/MagickCore/libMagickCore_7_Q16HDRI_la-image-view.o \
../lib/ImageMagick/MagickCore/libMagickCore_7_Q16HDRI_la-image.o \
../lib/ImageMagick/MagickCore/libMagickCore_7_Q16HDRI_la-layer.o \
../lib/ImageMagick/MagickCore/libMagickCore_7_Q16HDRI_la-linked-list.o \
../lib/ImageMagick/MagickCore/libMagickCore_7_Q16HDRI_la-list.o \
../lib/ImageMagick/MagickCore/libMagickCore_7_Q16HDRI_la-locale.o \
../lib/ImageMagick/MagickCore/libMagickCore_7_Q16HDRI_la-log.o \
../lib/ImageMagick/MagickCore/libMagickCore_7_Q16HDRI_la-magic.o \
../lib/ImageMagick/MagickCore/libMagickCore_7_Q16HDRI_la-magick.o \
../lib/ImageMagick/MagickCore/libMagickCore_7_Q16HDRI_la-matrix.o \
../lib/ImageMagick/MagickCore/libMagickCore_7_Q16HDRI_la-memory.o \
../lib/ImageMagick/MagickCore/libMagickCore_7_Q16HDRI_la-mime.o \
../lib/ImageMagick/MagickCore/libMagickCore_7_Q16HDRI_la-module.o \
../lib/ImageMagick/MagickCore/libMagickCore_7_Q16HDRI_la-monitor.o \
../lib/ImageMagick/MagickCore/libMagickCore_7_Q16HDRI_la-montage.o \
../lib/ImageMagick/MagickCore/libMagickCore_7_Q16HDRI_la-morphology.o \
../lib/ImageMagick/MagickCore/libMagickCore_7_Q16HDRI_la-opencl.o \
../lib/ImageMagick/MagickCore/libMagickCore_7_Q16HDRI_la-option.o \
../lib/ImageMagick/MagickCore/libMagickCore_7_Q16HDRI_la-paint.o \
../lib/ImageMagick/MagickCore/libMagickCore_7_Q16HDRI_la-pixel.o \
../lib/ImageMagick/MagickCore/libMagickCore_7_Q16HDRI_la-policy.o \
../lib/ImageMagick/MagickCore/libMagickCore_7_Q16HDRI_la-prepress.o \
../lib/ImageMagick/MagickCore/libMagickCore_7_Q16HDRI_la-profile.o \
../lib/ImageMagick/MagickCore/libMagickCore_7_Q16HDRI_la-property.o \
../lib/ImageMagick/MagickCore/libMagickCore_7_Q16HDRI_la-quantize.o \
../lib/ImageMagick/MagickCore/libMagickCore_7_Q16HDRI_la-quantum-export.o \
../lib/ImageMagick/MagickCore/libMagickCore_7_Q16HDRI_la-quantum-import.o \
../lib/ImageMagick/MagickCore/libMagickCore_7_Q16HDRI_la-quantum.o \
../lib/ImageMagick/MagickCore/libMagickCore_7_Q16HDRI_la-random.o \
../lib/ImageMagick/MagickCore/libMagickCore_7_Q16HDRI_la-registry.o \
../lib/ImageMagick/MagickCore/libMagickCore_7_Q16HDRI_la-resample.o \
../lib/ImageMagick/MagickCore/libMagickCore_7_Q16HDRI_la-resize.o \
../lib/ImageMagick/MagickCore/libMagickCore_7_Q16HDRI_la-resource.o \
../lib/ImageMagick/MagickCore/libMagickCore_7_Q16HDRI_la-segment.o \
../lib/ImageMagick/MagickCore/libMagickCore_7_Q16HDRI_la-semaphore.o \
../lib/ImageMagick/MagickCore/libMagickCore_7_Q16HDRI_la-shear.o \
../lib/ImageMagick/MagickCore/libMagickCore_7_Q16HDRI_la-signature.o \
../lib/ImageMagick/MagickCore/libMagickCore_7_Q16HDRI_la-splay-tree.o \
../lib/ImageMagick/MagickCore/libMagickCore_7_Q16HDRI_la-static.o \
../lib/ImageMagick/MagickCore/libMagickCore_7_Q16HDRI_la-statistic.o \
../lib/ImageMagick/MagickCore/libMagickCore_7_Q16HDRI_la-stream.o \
../lib/ImageMagick/MagickCore/libMagickCore_7_Q16HDRI_la-string.o \
../lib/ImageMagick/MagickCore/libMagickCore_7_Q16HDRI_la-thread.o \
../lib/ImageMagick/MagickCore/libMagickCore_7_Q16HDRI_la-threshold.o \
../lib/ImageMagick/MagickCore/libMagickCore_7_Q16HDRI_la-timer.o \
../lib/ImageMagick/MagickCore/libMagickCore_7_Q16HDRI_la-token.o \
../lib/ImageMagick/MagickCore/libMagickCore_7_Q16HDRI_la-transform.o \
../lib/ImageMagick/MagickCore/libMagickCore_7_Q16HDRI_la-type.o \
../lib/ImageMagick/MagickCore/libMagickCore_7_Q16HDRI_la-utility.o \
../lib/ImageMagick/MagickCore/libMagickCore_7_Q16HDRI_la-version.o \
../lib/ImageMagick/MagickCore/libMagickCore_7_Q16HDRI_la-vision.o \
../lib/ImageMagick/MagickCore/libMagickCore_7_Q16HDRI_la-widget.o \
../lib/ImageMagick/MagickCore/libMagickCore_7_Q16HDRI_la-xml-tree.o \
../lib/ImageMagick/MagickCore/libMagickCore_7_Q16HDRI_la-xwindow.o 

OBJS += \
./lib/ImageMagick/MagickCore/accelerate.o \
./lib/ImageMagick/MagickCore/animate.o \
./lib/ImageMagick/MagickCore/annotate.o \
./lib/ImageMagick/MagickCore/artifact.o \
./lib/ImageMagick/MagickCore/attribute.o \
./lib/ImageMagick/MagickCore/blob.o \
./lib/ImageMagick/MagickCore/cache-view.o \
./lib/ImageMagick/MagickCore/cache.o \
./lib/ImageMagick/MagickCore/channel.o \
./lib/ImageMagick/MagickCore/cipher.o \
./lib/ImageMagick/MagickCore/client.o \
./lib/ImageMagick/MagickCore/coder.o \
./lib/ImageMagick/MagickCore/color.o \
./lib/ImageMagick/MagickCore/colormap.o \
./lib/ImageMagick/MagickCore/colorspace.o \
./lib/ImageMagick/MagickCore/compare.o \
./lib/ImageMagick/MagickCore/composite.o \
./lib/ImageMagick/MagickCore/compress.o \
./lib/ImageMagick/MagickCore/configure.o \
./lib/ImageMagick/MagickCore/constitute.o \
./lib/ImageMagick/MagickCore/decorate.o \
./lib/ImageMagick/MagickCore/delegate.o \
./lib/ImageMagick/MagickCore/deprecate.o \
./lib/ImageMagick/MagickCore/display.o \
./lib/ImageMagick/MagickCore/distort.o \
./lib/ImageMagick/MagickCore/distribute-cache.o \
./lib/ImageMagick/MagickCore/draw.o \
./lib/ImageMagick/MagickCore/effect.o \
./lib/ImageMagick/MagickCore/enhance.o \
./lib/ImageMagick/MagickCore/exception.o \
./lib/ImageMagick/MagickCore/feature.o \
./lib/ImageMagick/MagickCore/fourier.o \
./lib/ImageMagick/MagickCore/fx.o \
./lib/ImageMagick/MagickCore/gem.o \
./lib/ImageMagick/MagickCore/geometry.o \
./lib/ImageMagick/MagickCore/histogram.o \
./lib/ImageMagick/MagickCore/identify.o \
./lib/ImageMagick/MagickCore/image-view.o \
./lib/ImageMagick/MagickCore/image.o \
./lib/ImageMagick/MagickCore/layer.o \
./lib/ImageMagick/MagickCore/linked-list.o \
./lib/ImageMagick/MagickCore/list.o \
./lib/ImageMagick/MagickCore/locale.o \
./lib/ImageMagick/MagickCore/log.o \
./lib/ImageMagick/MagickCore/magic.o \
./lib/ImageMagick/MagickCore/magick.o \
./lib/ImageMagick/MagickCore/matrix.o \
./lib/ImageMagick/MagickCore/memory.o \
./lib/ImageMagick/MagickCore/mime.o \
./lib/ImageMagick/MagickCore/module.o \
./lib/ImageMagick/MagickCore/monitor.o \
./lib/ImageMagick/MagickCore/montage.o \
./lib/ImageMagick/MagickCore/morphology.o \
./lib/ImageMagick/MagickCore/nt-base.o \
./lib/ImageMagick/MagickCore/nt-feature.o \
./lib/ImageMagick/MagickCore/opencl.o \
./lib/ImageMagick/MagickCore/option.o \
./lib/ImageMagick/MagickCore/paint.o \
./lib/ImageMagick/MagickCore/pixel.o \
./lib/ImageMagick/MagickCore/policy.o \
./lib/ImageMagick/MagickCore/prepress.o \
./lib/ImageMagick/MagickCore/profile.o \
./lib/ImageMagick/MagickCore/property.o \
./lib/ImageMagick/MagickCore/quantize.o \
./lib/ImageMagick/MagickCore/quantum-export.o \
./lib/ImageMagick/MagickCore/quantum-import.o \
./lib/ImageMagick/MagickCore/quantum.o \
./lib/ImageMagick/MagickCore/random.o \
./lib/ImageMagick/MagickCore/registry.o \
./lib/ImageMagick/MagickCore/resample.o \
./lib/ImageMagick/MagickCore/resize.o \
./lib/ImageMagick/MagickCore/resource.o \
./lib/ImageMagick/MagickCore/segment.o \
./lib/ImageMagick/MagickCore/semaphore.o \
./lib/ImageMagick/MagickCore/shear.o \
./lib/ImageMagick/MagickCore/signature.o \
./lib/ImageMagick/MagickCore/splay-tree.o \
./lib/ImageMagick/MagickCore/static.o \
./lib/ImageMagick/MagickCore/statistic.o \
./lib/ImageMagick/MagickCore/stream.o \
./lib/ImageMagick/MagickCore/string.o \
./lib/ImageMagick/MagickCore/thread.o \
./lib/ImageMagick/MagickCore/threshold.o \
./lib/ImageMagick/MagickCore/timer.o \
./lib/ImageMagick/MagickCore/token.o \
./lib/ImageMagick/MagickCore/transform.o \
./lib/ImageMagick/MagickCore/type.o \
./lib/ImageMagick/MagickCore/utility.o \
./lib/ImageMagick/MagickCore/version.o \
./lib/ImageMagick/MagickCore/vision.o \
./lib/ImageMagick/MagickCore/vms.o \
./lib/ImageMagick/MagickCore/widget.o \
./lib/ImageMagick/MagickCore/xml-tree.o \
./lib/ImageMagick/MagickCore/xwindow.o 

C_DEPS += \
./lib/ImageMagick/MagickCore/accelerate.d \
./lib/ImageMagick/MagickCore/animate.d \
./lib/ImageMagick/MagickCore/annotate.d \
./lib/ImageMagick/MagickCore/artifact.d \
./lib/ImageMagick/MagickCore/attribute.d \
./lib/ImageMagick/MagickCore/blob.d \
./lib/ImageMagick/MagickCore/cache-view.d \
./lib/ImageMagick/MagickCore/cache.d \
./lib/ImageMagick/MagickCore/channel.d \
./lib/ImageMagick/MagickCore/cipher.d \
./lib/ImageMagick/MagickCore/client.d \
./lib/ImageMagick/MagickCore/coder.d \
./lib/ImageMagick/MagickCore/color.d \
./lib/ImageMagick/MagickCore/colormap.d \
./lib/ImageMagick/MagickCore/colorspace.d \
./lib/ImageMagick/MagickCore/compare.d \
./lib/ImageMagick/MagickCore/composite.d \
./lib/ImageMagick/MagickCore/compress.d \
./lib/ImageMagick/MagickCore/configure.d \
./lib/ImageMagick/MagickCore/constitute.d \
./lib/ImageMagick/MagickCore/decorate.d \
./lib/ImageMagick/MagickCore/delegate.d \
./lib/ImageMagick/MagickCore/deprecate.d \
./lib/ImageMagick/MagickCore/display.d \
./lib/ImageMagick/MagickCore/distort.d \
./lib/ImageMagick/MagickCore/distribute-cache.d \
./lib/ImageMagick/MagickCore/draw.d \
./lib/ImageMagick/MagickCore/effect.d \
./lib/ImageMagick/MagickCore/enhance.d \
./lib/ImageMagick/MagickCore/exception.d \
./lib/ImageMagick/MagickCore/feature.d \
./lib/ImageMagick/MagickCore/fourier.d \
./lib/ImageMagick/MagickCore/fx.d \
./lib/ImageMagick/MagickCore/gem.d \
./lib/ImageMagick/MagickCore/geometry.d \
./lib/ImageMagick/MagickCore/histogram.d \
./lib/ImageMagick/MagickCore/identify.d \
./lib/ImageMagick/MagickCore/image-view.d \
./lib/ImageMagick/MagickCore/image.d \
./lib/ImageMagick/MagickCore/layer.d \
./lib/ImageMagick/MagickCore/linked-list.d \
./lib/ImageMagick/MagickCore/list.d \
./lib/ImageMagick/MagickCore/locale.d \
./lib/ImageMagick/MagickCore/log.d \
./lib/ImageMagick/MagickCore/magic.d \
./lib/ImageMagick/MagickCore/magick.d \
./lib/ImageMagick/MagickCore/matrix.d \
./lib/ImageMagick/MagickCore/memory.d \
./lib/ImageMagick/MagickCore/mime.d \
./lib/ImageMagick/MagickCore/module.d \
./lib/ImageMagick/MagickCore/monitor.d \
./lib/ImageMagick/MagickCore/montage.d \
./lib/ImageMagick/MagickCore/morphology.d \
./lib/ImageMagick/MagickCore/nt-base.d \
./lib/ImageMagick/MagickCore/nt-feature.d \
./lib/ImageMagick/MagickCore/opencl.d \
./lib/ImageMagick/MagickCore/option.d \
./lib/ImageMagick/MagickCore/paint.d \
./lib/ImageMagick/MagickCore/pixel.d \
./lib/ImageMagick/MagickCore/policy.d \
./lib/ImageMagick/MagickCore/prepress.d \
./lib/ImageMagick/MagickCore/profile.d \
./lib/ImageMagick/MagickCore/property.d \
./lib/ImageMagick/MagickCore/quantize.d \
./lib/ImageMagick/MagickCore/quantum-export.d \
./lib/ImageMagick/MagickCore/quantum-import.d \
./lib/ImageMagick/MagickCore/quantum.d \
./lib/ImageMagick/MagickCore/random.d \
./lib/ImageMagick/MagickCore/registry.d \
./lib/ImageMagick/MagickCore/resample.d \
./lib/ImageMagick/MagickCore/resize.d \
./lib/ImageMagick/MagickCore/resource.d \
./lib/ImageMagick/MagickCore/segment.d \
./lib/ImageMagick/MagickCore/semaphore.d \
./lib/ImageMagick/MagickCore/shear.d \
./lib/ImageMagick/MagickCore/signature.d \
./lib/ImageMagick/MagickCore/splay-tree.d \
./lib/ImageMagick/MagickCore/static.d \
./lib/ImageMagick/MagickCore/statistic.d \
./lib/ImageMagick/MagickCore/stream.d \
./lib/ImageMagick/MagickCore/string.d \
./lib/ImageMagick/MagickCore/thread.d \
./lib/ImageMagick/MagickCore/threshold.d \
./lib/ImageMagick/MagickCore/timer.d \
./lib/ImageMagick/MagickCore/token.d \
./lib/ImageMagick/MagickCore/transform.d \
./lib/ImageMagick/MagickCore/type.d \
./lib/ImageMagick/MagickCore/utility.d \
./lib/ImageMagick/MagickCore/version.d \
./lib/ImageMagick/MagickCore/vision.d \
./lib/ImageMagick/MagickCore/vms.d \
./lib/ImageMagick/MagickCore/widget.d \
./lib/ImageMagick/MagickCore/xml-tree.d \
./lib/ImageMagick/MagickCore/xwindow.d 


# Each subdirectory must supply rules for building sources it contributes
lib/ImageMagick/MagickCore/%.o: ../lib/ImageMagick/MagickCore/%.c
	@echo 'Building file: $<'
	@echo 'Invoking: GCC C Compiler'
	gcc -O0 -g3 -Wall -c -fmessage-length=0 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@)" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '


